import type {WorkoutRecord} from './workout-records';
import type {SavedTrainingGoal} from './training-goals';
import {progressStats,TRAINING_PARTS} from './training-goals';
import {analysisWindow,exerciseGroups,performanceDays,performanceLabels,type PerformanceMetric} from './progress-analysis';
import {assessmentProtocol,assessmentConditions,type AssessmentResult} from './assessment-results';
export const GOAL_VISUAL_VERSION='goal-visual-v6-cardio-guidance-claims';
export type GoalVisualPoint={date:string;value:number;recordIds:string[];condition:string;notes:string[]};
export type GoalVisualCandidate={id:string;name:string;label:string;unit:string;kind:'exercise'|'summary'|'distribution'|'assessment';link:string;metric?:PerformanceMetric;points:GoalVisualPoint[];target:number|null;direction:'up'|'down'|'observe';conditionsMatch:boolean};
export type GoalVisualCard={candidateId:string;format:'trend'|'comparison'|'target'|'conditions';goal:string;status:'progress'|'review'|'insufficient';interpretation:string;interpretationSource?:'record-check';nextStep:string};
export type GoalVisualReport={fingerprint:string;inputKey:string;headline:string;status:'progress'|'review'|'insufficient';cards:GoalVisualCard[];missing:string[];decision?:{choice:string;reason:string}|null};
type Import={rows?:{id:string;review:string}[]};
type Note={date:string;text:string};
export function eligibleAnalysisRecords(records:WorkoutRecord[],imports:Import[]){const excluded=new Set(imports.flatMap(i=>(i.rows??[]).filter(r=>r.review==='needs-review'||r.review==='ignored').map(r=>r.id)));return records.filter(r=>!r.pending&&!excluded.has(r.id));}
export function goalVisualInputKey(records:WorkoutRecord[],goal:SavedTrainingGoal|null,results:AssessmentResult[],notes:Note[],period:string){return JSON.stringify({version:GOAL_VISUAL_VERSION,period,goal:goal?.revision??0,records:records.map(r=>[r.id,r.revision,r.date]).sort((a,b)=>String(a[0]).localeCompare(String(b[0]))),results:results.map(r=>[r.id,r.revision]).sort((a,b)=>String(a[0]).localeCompare(String(b[0]))),notes:notes.map(n=>[n.date,n.text]).sort((a,b)=>a[0].localeCompare(b[0]))});}
export function goalVisualCandidates(records:WorkoutRecord[],goal:SavedTrainingGoal,results:AssessmentResult[],notes:Note[],period:string){
 const window=analysisWindow(records,period),start=goal.startMode==='date'?goal.startDate:'',rows=window.records.filter(r=>!start||r.date>=start),stats=progressStats(rows),candidates:GoalVisualCandidate[]=[];
 const noteFor=(date:string,rs:WorkoutRecord[])=>[...new Set([...notes.filter(n=>n.date===date).map(n=>n.text),...rs.map(r=>r.trainerNote??'')].filter(Boolean))];
 for(const [i,g]of exerciseGroups(rows).entries()){
  const metrics:PerformanceMetric[]=g.kind==='repetitions'?[...(g.hasWeighted?['kg' as const]:[]),'reps',...(g.records.some(r=>r.sets.some(s=>s.leftReps!==undefined))?['left' as const,'right' as const]:[])]:g.kind==='distance_time'?['distance','duration']:g.kind==='distance'?['distance']:['duration'];
  for(const metric of metrics){const [label,unit]=performanceLabels[metric];
   const points=performanceDays(g.records,metric).filter(p=>p.value!==null).map(p=>{const condition=[...new Set(p.records.flatMap(r=>r.sets.map(s=>g.kind==='incline_speed_time'?`경사 ${s.inclinePercent}% · ${s.speedKph}km/h · ${s.durationSeconds}초`:g.kind==='repetitions'?`${r.loadType==='weighted'?s.kg+'kg':r.loadType==='bodyweight'?'맨몸':'중량 미상'} × ${s.reps}회`:g.kind==='distance_time'?`${s.distanceMeters}m · ${s.durationSeconds}초`:g.kind)))].join(' / ');return {date:p.date,value:p.value!,recordIds:p.records.map(r=>r.id),condition:`${p.records.reduce((n,r)=>n+r.sets.length,0)}${g.kind==='repetitions'?'세트':'구간'} · ${condition}`,notes:noteFor(p.date,p.records)};});
   if(points.length)candidates.push({id:`exercise-${i}-${metric}`,name:g.name,label:metric==='reps'?'수업일 총 횟수 (모든 세트 합계)':label,unit,kind:'exercise',link:g.key,metric,points,target:null,direction:'observe',conditionsMatch:new Set(points.map(p=>JSON.stringify(g.records.filter(r=>r.date===p.date).flatMap(r=>r.sets.map(s=>({kind:g.kind,load:r.loadType,kg:metric==='kg'?undefined:s.kg,reps:['reps','left','right'].includes(metric)?undefined:s.reps,left: ['reps','left','right'].includes(metric)?undefined:s.leftReps,right:['reps','left','right'].includes(metric)?undefined:s.rightReps,duration:metric==='duration'?undefined:s.durationSeconds,distance:metric==='distance'?undefined:s.distanceMeters,incline:s.inclinePercent,speed:s.speedKph})))))).size===1});
  }
 }
 for(const metric of ['sets','volume'] as const){const points=stats.trend.flatMap(d=>{const v=metric==='sets'?d.sets:d.volume;if(v===null||metric==='sets'&&!v)return [];const rs=rows.filter(r=>r.date===d.date);return [{date:d.date,value:v,recordIds:rs.map(r=>r.id),condition:metric==='volume'&&d.excludedVolume?'중량 미상·맨몸 볼륨 제외':'수업일 합계',notes:noteFor(d.date,rs)}];});if(points.length)candidates.push({id:`summary-${metric}`,name:metric==='sets'?'수업별 세트':'수업별 볼륨',label:performanceLabels[metric][0],unit:performanceLabels[metric][1],kind:'summary',link:'summary',metric,points,target:null,direction:'observe',conditionsMatch:false});}
 const classified=TRAINING_PARTS.reduce((n,p)=>n+(stats.parts[p]??0),0),distribution=goal.distribution;
 if(classified)for(const part of TRAINING_PARTS){const count=stats.parts[part]??0;if(!count)continue;const target=goal.startMode!=='unknown'&&distribution.mode==='percent'?(distribution.shares[part]??0):null;candidates.push({id:'body-'+part,name:part+' 훈련 비중',label:'세트 비중',unit:'%',kind:'distribution',link:part,points:[{date:stats.trend.at(-1)!.date,value:Math.round(count/classified*1000)/10,recordIds:rows.filter(r=>r.bodyPart===part).map(r=>r.id),condition:`${count} / ${classified}세트 · 주동근 기준`,notes:[]}],target,direction:'observe',conditionsMatch:true});}
 if(distribution.mode==='split'&&goal.startMode!=='unknown'){const lower=stats.parts['하체']??0,upper=TRAINING_PARTS.filter(p=>p!=='하체'&&p!=='코어').reduce((n,p)=>n+(stats.parts[p]??0),0);if(lower+upper)candidates.push({id:'body-upper',name:'상·하체 배분',label:'상체 비중',unit:'%',kind:'distribution',link:'하체',points:[{date:stats.trend.at(-1)!.date,value:Math.round(upper/(upper+lower)*1000)/10,recordIds:rows.map(r=>r.id),condition:`상체 ${upper}세트 / 하체 ${lower}세트 · 코어 제외`,notes:[]}],target:distribution.upper,direction:'observe',conditionsMatch:true});}
 const a=goal.assessment,fields=a?.draft?.fields??[];
 if(a?.confirmed&&fields.length){const protocol=assessmentProtocol(a,fields),conditions=assessmentConditions(a),matching=results.filter(r=>assessmentProtocol(r.assessment,r.fields)===protocol&&r.conditions===conditions&&(!window.from||r.date>=window.from)&&(!window.to||r.date<=window.to)&&(!start||r.date>=start)).sort((a,b)=>a.date.localeCompare(b.date));
  fields.forEach((field,i)=>{const points=matching.filter(r=>r.values[i]!==null).map(r=>({date:r.date,value:r.values[i]!,recordIds:[r.id],condition:r.conditions,notes:[r.stopReason,r.note,r.effort===null?'':`체감 강도 ${r.effort}/10`].filter(Boolean)}));if(points.length)candidates.push({id:`assessment-${i}`,name:field.label,label:a.draft!.title,unit:field.unit,kind:'assessment',link:'assessment',points,target:goal.startMode!=='unknown'?field.target:null,direction:field.direction,conditionsMatch:true});});
 }
 return {candidates,from:window.from,to:window.to,days:stats.days,startUnknown:goal.startMode==='unknown'};
}
