"use client";
import {useEffect,useId,useRef,useState,type RefObject} from 'react';
import {Icon} from './icons';
import {useWorkspaceTextScale,WORKSPACE_TEXT_SCALES} from '../lib/workspace-text-scale';
export function AnalysisTools({memberId,contentRef,online,busy,canRegenerate,onRegenerate,kind='analysis',exportContent,regenerateMessage,hideRegenerate=false,workspaceMenu=false,contentLabel,extraActions}:{contentLabel?:string;workspaceMenu?:boolean;hideRegenerate?:boolean;extraActions?:React.ReactNode;kind?:'analysis'|'records'|'lesson';exportContent?:()=>HTMLElement;regenerateMessage?:string;memberId:string;contentRef:RefObject<HTMLDivElement|null>;online:boolean;busy:boolean;canRegenerate:boolean;onRegenerate:()=>Promise<void>}){
 const label=contentLabel||(kind==='records'?'판독 기록':kind==='lesson'?'다음 수업':'분석 내용');
 const id=useId(),menu=useRef<HTMLDivElement>(null),trigger=useRef<HTMLButtonElement>(null),[notice,setNotice]=useState(''),[printing,setPrinting]=useState(false);
 const noticeTimer=useRef<ReturnType<typeof setTimeout>|null>(null);
 useEffect(()=>()=>{if(noticeTimer.current!==null)clearTimeout(noticeTimer.current);},[]);
 function showNotice(message:string,duration=3000){
  if(noticeTimer.current!==null)clearTimeout(noticeTimer.current);
  setNotice(message);
  noticeTimer.current=setTimeout(()=>{setNotice('');noticeTimer.current=null;},duration);
 }
 const [scale,size]=useWorkspaceTextScale(memberId);
 useEffect(()=>{if(contentRef.current)contentRef.current.style.zoom=String(scale/100);},[scale,contentRef]);
 function clean(){if(exportContent)return exportContent();const copy=contentRef.current?.cloneNode(true) as HTMLElement|undefined;if(!copy)return;copy.style.zoom='1';copy.style.height='auto';copy.style.overflow='visible';copy.querySelectorAll('.previous-lesson li>button').forEach(button=>{const text=document.createElement('div');text.textContent=button.textContent;button.replaceWith(text);});copy.querySelectorAll('button,form,input,select,textarea,.ai-usage,.live-review-banner,.live-processing').forEach(e=>e.remove());copy.querySelectorAll('details').forEach(e=>e.setAttribute('open',''));return copy;}
 function close(){menu.current?.hidePopover();trigger.current?.focus();}
 async function copy(){close();const el=clean();if(!el)return;try{const holder=document.createElement('div');holder.style.cssText='position:fixed;left:-10000px;width:700px';holder.append(el);document.body.append(holder);const text=el.innerText;holder.remove();await navigator.clipboard.writeText(text);showNotice(`${label}을 복사했어요.`);}catch{showNotice('클립보드에 접근할 수 없어요. 브라우저 권한을 확인해주세요.',6000);}}
 async function print(){close();const content=clean();if(!content||printing)return;setPrinting(true);const frame=document.createElement('iframe');frame.title=`${label} PDF 인쇄`;frame.style.cssText='position:fixed;right:0;bottom:0;width:1px;height:1px;border:0';document.body.append(frame);try{const doc=frame.contentDocument!;doc.open();doc.write(`<!doctype html><html lang="ko"><head><title>${kind==='records'?'판독 기록':kind==='lesson'?'다음 수업':'진행 분석'}</title></head><body></body></html>`);doc.close();document.querySelectorAll('style,link[rel="stylesheet"]').forEach(el=>doc.head.append(el.cloneNode(true)));const style=doc.createElement('style');style.textContent='@page{size:A4;margin:16mm}html,body{height:auto!important;overflow:visible!important;background:white!important;color:#202920!important}.pane-body{overflow:visible!important;height:auto!important;max-height:none!important;padding:0!important;zoom:1!important}h1{font-size:26px}article,.quiet-card{break-inside:avoid}button{display:none!important}';doc.head.append(style);doc.body.append(content);await Promise.all([...doc.querySelectorAll<HTMLLinkElement>('link')].map(l=>l.sheet?Promise.resolve():new Promise<void>(resolve=>{l.onload=()=>resolve();l.onerror=()=>resolve();setTimeout(resolve,3000);})));await doc.fonts.ready;frame.contentWindow!.focus();frame.contentWindow!.print();showNotice('인쇄 창에서 PDF로 저장을 선택하세요.');}catch{showNotice('인쇄 창을 열지 못했어요. 다시 시도해주세요.',6000);}finally{setPrinting(false);setTimeout(()=>frame.remove(),60000);}}
 function position(){const b=trigger.current?.getBoundingClientRect(),el=menu.current;if(b&&el){el.style.left=Math.max(8,Math.min(innerWidth-308,b.right-300))+'px';el.style.top=Math.max(8,Math.min(b.bottom+6,innerHeight-280))+'px';}}
 return <div className="analysis-actions"><span role="status">{notice}</span><button ref={trigger} popoverTarget={id} className="icon-button" aria-label={workspaceMenu?'작업 화면 메뉴':kind==='records'?'기록 수정 메뉴':kind==='lesson'?'다음 수업 메뉴':'진행 분석 메뉴'} title={workspaceMenu?'작업 화면 설정':kind==='records'?'기록 설정':kind==='lesson'?'다음 수업 설정':'분석 설정'} onClick={position}><Icon name="more"/></button><div id={id} ref={menu} popover="auto" className="analysis-options"><strong>글자 크기 · 작업 화면 공통</strong><div className="analysis-font-sizes">{WORKSPACE_TEXT_SCALES.map(v=><button key={v} aria-pressed={scale===v} onClick={()=>size(v)}>{v}%</button>)}</div>{!hideRegenerate&&<button disabled={!online||busy||!canRegenerate} onClick={()=>{close();if(window.confirm(regenerateMessage||'최신 기록으로 AI 분석을 다시 생성할까요? AI 이용량이 차감됩니다.'))void onRegenerate();}}>다시 생성</button>}<button onClick={()=>void copy()}>클립보드에 복사</button><button disabled={printing} onClick={()=>void print()}>PDF로 저장</button>{extraActions}</div></div>;
}
