"use client";
import {SessionNoteEditor} from './session-note-editor';
import type {SessionNote} from '../lib/session-notes';
import {isReviewAlertVisible,rowAlertKey,unparsedAlertKey,visibleUnparsed} from '../lib/review-alerts';
import {AnalysisTools} from './analysis-tools';
import {recordExport} from '../lib/record-export';
import {WorkoutSelect} from './workout-select';
import {IntervalPattern} from './interval-pattern';
import {repeatedWorkoutPattern} from '../lib/workout-display';
import {MotionHeight} from './motion-height';
import {MeasurementFields} from './measurement-fields';
import {formatWorkoutSet,measurementType,measurementLabels} from '../lib/workout-measurements';
import {useEffect,useRef,useState,type FormEvent} from 'react';
import {Icon} from './icons';
import {ContinuousSourceViewer} from './continuous-source-viewer';
import {type MemberFile} from '../lib/member-files';
import {BODY_PARTS,saveWorkout,validateWorkout,type WorkoutInput,type WorkoutRecord} from '../lib/workout-records';
import {serverAiEnabled,callAi,aiMessage,type SavedImport} from '../lib/server-ai';
export type SourceRow={alertDismissed?:boolean;id:string;input:WorkoutInput;issues:string[];review:string;fileId?:string;importRevision?:number;rowRevision?:number;unparsedIndex?:number;isNew?:boolean;compound?:import('../lib/workout-extraction').ExtractedWorkout['compound'];existing?:WorkoutRecord};
export function sourceRows(imports:SavedImport[],records:WorkoutRecord[]):SourceRow[]{
 const rows:SourceRow[]=imports.flatMap(file=>file.rows.filter(row=>row.review!=='ignored').map(row=>({alertDismissed:!isReviewAlertVisible(file,rowAlertKey(row)),id:row.id,input:row.input,issues:row.issues,review:row.review,fileId:file.id,importRevision:file.revision,rowRevision:row.revision,compound:row.compound})));
 for(const r of records){const i=rows.findIndex(row=>row.id===r.id);const input:WorkoutInput={date:r.date,rawName:r.rawName,exerciseName:r.exerciseName,bodyPart:r.bodyPart,loadType:r.loadType,sets:r.sets,sourceName:r.sourceName,sourceHash:r.sourceHash,sourcePage:r.sourcePage,notes:r.notes,...(r.trainerNote!==undefined?{trainerNote:r.trainerNote}:{}),...(r.measurementType?{measurementType:r.measurementType}:{})};if(i>=0)rows[i]={...rows[i],input,existing:r};else rows.push({id:r.id,input,issues:[],review:r.status==='confirmed'?'confirmed':'auto',existing:r});}
 return rows;
}
export function AnalysisSource({sessionNotes=[],memberId,memberName,online,files,imports,rows,selectedFile,onFile,selectedRow,onRow,onUpload,onDirty,originalRequest=0,recordsOnly=false,onOriginal,sourcePage=1,recordJump=0,reviewJump=0,onExplain}:{sessionNotes?:SessionNote[];memberId:string;memberName:string;online:boolean;files:MemberFile[];imports:SavedImport[];rows:SourceRow[];selectedFile:string;onFile:(id:string)=>void;selectedRow:string;onRow:(id:string)=>void;onUpload:()=>void;onDirty:(v:boolean)=>void;originalRequest?:number;recordsOnly?:boolean;onOriginal?:(id:string,page:number)=>void;sourcePage?:number;recordJump?:number;reviewJump?:number;onExplain?:(input:WorkoutInput)=>void}){
 const [tab,setTab]=useState(recordsOnly?'records':'original'),[edit,setEdit]=useState<SourceRow|null>(null),[collapsed,setCollapsed]=useState(false);
 const [regenerating,setRegenerating]=useState(false),[toolNotice,setToolNotice]=useState('');
 const contentRef=useRef<HTMLDivElement>(null),regenerationLock=useRef(false);
 const saving=useRef(false),noteDirty=useRef(new Set<string>());
 function reportDirty(){onDirty(dirty.current||noteDirty.current.size>0);}
 const dirty=useRef(false),scrollRef=useRef<HTMLDivElement>(null),groupRefs=useRef(new Map<string,HTMLElement>()),pageRefs=useRef(new Map<string,HTMLElement>()),rowRefs=useRef(new Map<string,HTMLElement>());
 const chosen=rows.find(r=>r.id===selectedRow);
 const groups=files.map(file=>({id:file.id,file,data:imports.find(i=>i.id===file.id),rows:rows.filter(r=>(r.fileId||r.input.sourceHash)===file.id)}));
 const extra=rows.filter(r=>!files.some(f=>f.id===(r.fileId||r.input.sourceHash)));
 const recordGroups=[...groups,...(extra.length?[{id:'other',file:undefined,data:undefined,rows:extra}]:[])].filter(g=>recordsOnly||selectedFile==='all'||g.id===selectedFile);
 const regenerationFiles=files.filter(f=>f.status==='ready'&&(selectedFile==='all'||f.id===selectedFile));
 async function regenerate(){if(regenerationLock.current)return;if(dirty.current||saving.current){setToolNotice('작성 중인 수정을 먼저 저장하거나 취소해주세요.');return;}regenerationLock.current=true;setRegenerating(true);setToolNotice('원본을 다시 판독하고 있어요…');setEdit(null);let completed=0;try{for(const file of regenerationFiles){const data=imports.find(i=>i.id===file.id);await callAi({action:'read',memberId,fileId:file.id,retry:true,regenerate:true,revision:data?.revision??0});completed++;}setToolNotice(`${completed}개 원본을 다시 판독했어요. 직접 수정한 기록은 유지했어요.`);}catch(e){setToolNotice(`${completed?`${completed}개 완료 · `:''}${aiMessage(e)}`);}finally{regenerationLock.current=false;setRegenerating(false);}}
 function exportRecords(){return recordExport(memberName,recordGroups.map(g=>({name:g.file?.name||'직접 입력·기타 기록',rows:g.rows,unparsed:visibleUnparsed(g.data).map(v=>v.value)})));}
 function scrollTo(el?:HTMLElement){const root=scrollRef.current;if(el&&root){const target=el.getBoundingClientRect(),viewport=root.getBoundingClientRect();if(target.top>=viewport.top+12&&target.top<viewport.bottom-60)return;root.scrollTop+=target.top-viewport.top-12;}}
 function clearEditor(){if(saving.current||regenerationLock.current)return false;if(dirty.current&&!window.confirm('저장하지 않은 수정 내용이 있어요. 버리고 이동할까요?'))return false;dirty.current=false;reportDirty();setEdit(null);return true;}
 function safeSwitch(action:()=>void){if(clearEditor())action();}
 function begin(row:SourceRow){if(saving.current||regenerationLock.current)return;if(edit?.id===row.id){setCollapsed(v=>!v);return;}row=rows.find(r=>r.id===row.id)??row;safeSwitch(()=>{if(!row.isNew)onRow(row.id);else onOriginal?.(row.fileId||row.input.sourceHash,row.input.sourcePage||1);setCollapsed(false);setEdit(row);});}
 function add(file:MemberFile,page:number,data?:SavedImport,index?:number){const raw=index===undefined?undefined:data?.unparsed[index];const same=rows.find(r=>r.input.sourceHash===file.id&&r.input.sourcePage===page&&r.input.date);begin({id:crypto.randomUUID().replaceAll('-','').slice(0,20),isNew:true,unparsedIndex:index,fileId:data?.status==='ready'?file.id:undefined,importRevision:data?.revision,review:'needs-review',issues:raw?[raw.reason]:[],input:{date:same?.input.date||'',rawName:raw?.text.slice(0,100)||'',exerciseName:'',bodyPart:'미분류',loadType:'unknown',sets:[{kg:null,reps:0}],sourceHash:file.id,sourceName:file.name,sourcePage:page,notes:raw?`${raw.text} — ${raw.reason}`.slice(0,1000):''}});}
 useEffect(()=>{if(originalRequest&&!recordsOnly){setTab('original');setEdit(null);dirty.current=false;reportDirty();}},[originalRequest]);
 useEffect(()=>{if(!selectedRow)return;setTab('records');if(edit?.id!==selectedRow)setEdit(null);const t=setTimeout(()=>scrollTo(rowRefs.current.get(selectedRow)),0);return()=>clearTimeout(t);},[selectedRow]);
 useEffect(()=>{if(!recordJump)return;setEdit(null);dirty.current=false;reportDirty();setTab('records');const t=setTimeout(()=>scrollTo(pageRefs.current.get(`${selectedFile}:${sourcePage}`)||groupRefs.current.get(selectedFile)),0);return()=>clearTimeout(t);},[recordJump]);
 useEffect(()=>{if(!reviewJump||saving.current)return;const pending=rows.find(r=>r.review==='needs-review'&&!r.alertDismissed);if(pending){if(edit?.id===pending.id)setCollapsed(false);else begin(pending);const t=setTimeout(()=>scrollTo(rowRefs.current.get(pending.id)),0);return()=>clearTimeout(t);}const group=groups.find(g=>visibleUnparsed(g.data).length);if(group?.data){const {value:raw,index}=visibleUnparsed(group.data)[0];add(group.file,raw.page,group.data,index);const t=setTimeout(()=>scrollTo(scrollRef.current?.querySelector<HTMLElement>('.motion-height:not([aria-hidden=true]) .correction-container')??pageRefs.current.get(`${group.id}:${raw.page}`)),0);return()=>clearTimeout(t);}},[reviewJump]);
 function moveToFile(id:string){safeSwitch(()=>{onFile(id);if(id==='all')scrollRef.current?.scrollTo({top:0});else scrollTo(groupRefs.current.get(id));});}
 function editor(row:SourceRow){return <div className="correction-container"><InlineCorrection onBusy={v=>{saving.current=v;}} onExplain={onExplain} key={row.id} memberId={memberId} row={row} online={online} onDirty={v=>{dirty.current=v;reportDirty();}} onClose={()=>safeSwitch(()=>setEdit(null))} onSaved={()=>{dirty.current=false;reportDirty();setEdit(null);}}/></div>;}
 return <section className={'live-pane live-source'+(recordsOnly?' records-only':'')} aria-label="원본과 판독 기록"><div className="source-switch" hidden={recordsOnly}><button onClick={()=>setTab('records')}>판독 기록</button><button onClick={()=>setTab('original')}>원본 파일</button></div><div className="pdf-toolbar"><WorkoutSelect label="분석 원본 선택" disabled={regenerating} value={selectedFile} onChange={moveToFile} options={[{value:"all",label:"전체 판독 기록 · 이어 보기"},...files.map(f=>({value:f.id,label:f.name}))]}/><button className="icon-button" onClick={onUpload} aria-label="일지 추가"><Icon name="plus" size={16}/></button>{recordsOnly&&<AnalysisTools kind="records" memberId={memberId} contentRef={contentRef} exportContent={exportRecords} online={online} busy={regenerating||imports.some(i=>regenerationFiles.some(f=>f.id===i.id)&&i.status==='processing')} canRegenerate={serverAiEnabled&&regenerationFiles.length>0} onRegenerate={regenerate} regenerateMessage={`${regenerationFiles.length===1?regenerationFiles[0].name:`선택한 원본 ${regenerationFiles.length}개`}을 다시 판독할까요? 저장된 운동 기록은 유지하고 미확인 항목을 다시 읽습니다. AI 이용량이 차감됩니다.`}/>}</div>{toolNotice&&<p className="record-tool-notice" role="status">{toolNotice}</p>}<div ref={scrollRef} className="live-source-scroll"><div ref={contentRef} className="record-content">
 {tab==='original'?<ContinuousSourceViewer memberId={memberId} files={files} selectedFile={selectedFile} sourcePage={chosen?.input.sourcePage||1}/>:<>
 {!files.length&&!rows.length&&<div className="empty-state"><button className="primary" onClick={onUpload}>운동일지 업로드</button></div>}
 {recordGroups.map((group,index)=>{const pages=[...new Set([...group.rows.map(r=>r.input.sourcePage||1),...(group.data?.unparsed.map(r=>r.page)||[]),...(selectedFile===group.id?[sourcePage]:[]),...(edit?.input.sourceHash===group.id?[edit.input.sourcePage]:[]),1])].sort((a,b)=>a-b);return <section key={group.id} ref={el=>{if(el)groupRefs.current.set(group.id,el);else groupRefs.current.delete(group.id);}} className="record-file-group" data-record-file={group.id} aria-label={group.file?.name||'기타 운동 기록'}>
 {pages.map(page=>{const visible=group.rows.filter(r=>(r.input.sourcePage||1)===page),needsReview=visible.filter(r=>r.review==='needs-review'&&!r.alertDismissed).length+visibleUnparsed(group.data).filter(({value})=>value.page===page).length;return <div className="live-paper linked-record-paper" key={page} data-record-page={page} tabIndex={0} aria-label={`${group.file?.name||'기타 기록'} ${page}쪽 판독 카드 · 원본 열기`} onClick={e=>{if(!(e.target as HTMLElement).closest('button,input,select,textarea,a,label,form,summary'))onOriginal?.(group.id,page);}} onKeyDown={e=>{if(e.target===e.currentTarget&&(e.key==='Enter'||e.key===' ')){e.preventDefault();onOriginal?.(group.id,page);}}} ref={el=>{const k=`${group.id}:${page}`;if(el)pageRefs.current.set(k,el);else pageRefs.current.delete(k);}}><header className="record-card-heading"><span className="original-file-number">{String(index+1).padStart(2,'0')}</span><div><h2>{group.file?.name||'직접 입력·기타 기록'}</h2><div className="record-card-meta"><span>판독 기록{pages.length>1||group.file?.contentType==='application/pdf'?` · ${page}쪽`:''}</span><span className="record-status" data-state={group.data?.status||'manual'}>{group.data?.status==='ready'?'판독 완료':group.data?.status==='processing'?'판독 중':group.data?.status==='error'||group.data?.status==='limited'?'판독 확인 필요':'원본별 기록'}</span>{!!needsReview&&<span className="record-needs-review">수정 필요 {needsReview}개</span>}</div></div></header>
 {group.file&&<PageDate key={`${group.id}:${page}`} memberId={memberId} file={group.file} data={group.data} page={page} rows={visible} online={online} onBeforeApply={clearEditor}/>}
 {page===pages[0]&&<FileReviewStatus memberId={memberId} memberName={memberName} online={online} active={group.file} data={group.data} rows={group.rows} onBeforeApply={clearEditor} onRow={r=>{if(edit?.id===r.id)setCollapsed(false);else begin(r);}} onUnparsed={i=>{if(group.file)add(group.file,group.data!.unparsed[i].page,group.data,i);}}/>}
 <div className="live-record-heading"><span>운동 <b className="exercise-count">{visible.length}</b></span></div>{visible.map((row,exerciseIndex)=><div key={row.id} ref={el=>{if(el)rowRefs.current.set(row.id,el);else rowRefs.current.delete(row.id);}} className={'live-record-row '+(row.id===selectedRow?'is-selected':'')} data-expanded={edit?.id===row.id&&!collapsed}><button className="live-record-select" aria-label={`${row.input.exerciseName||row.input.rawName} 판독 값 수정`} aria-expanded={edit?.id===row.id&&!collapsed} onClick={()=>begin(row)}><span className="record-exercise-number">{String(exerciseIndex+1).padStart(2,'0')}</span><span className="record-exercise-info"><strong>{row.input.exerciseName||row.input.rawName||'운동명 확인 필요'}</strong><span className="record-exercise-tags"><span>{row.input.bodyPart}</span><span>{measurementLabels[measurementType(row.input)]}</span>{row.review==='needs-review'&&!row.alertDismissed&&<span className="record-attention-tag">확인 필요</span>}</span>{row.input.date!==visible[0]?.input.date&&<small>{row.input.date||'날짜 확인 필요'}</small>}</span><span className="record-exercise-edit"><Icon name="edit" size={15}/><Icon name="chevron" size={14}/></span><RecordSetSummary input={row.input}/></button>{edit?.id===row.id&&collapsed&&dirty.current&&<small className="collapsed-edit-notice">작성 중인 수정 내용이 있어요 · 다시 눌러 이어서 수정</small>}{row.compound&&<p className="compound-label">{row.compound.rawName} · 분리 {row.compound.index}/{row.compound.total}</p>}<MotionHeight open={edit?.id===row.id&&!collapsed}>{edit?.id===row.id?editor(edit):null}</MotionHeight></div>)}
 {edit?.isNew&&edit.input.sourceHash===group.id&&edit.input.sourcePage===page&&editor(edit)}
 {group.file&&<button className="paper-add" disabled={!online||group.file.status!=='ready'||group.data?.status==='processing'} onClick={()=>add(group.file!,page,group.data)}><Icon name="plus" size={18}/> 운동 추가</button>}
 {[...new Set(visible.map(r=>r.input.date).filter(Boolean))].map(date=><SessionNoteEditor key={`${group.id}:${page}:${date}`} memberId={memberId} date={date} note={sessionNotes.find(n=>n.date===date)} online={online} onBeforeSave={()=>{if(dirty.current||saving.current){setToolNotice('운동 수정을 먼저 저장하거나 취소해주세요.');return false;}return true;}} onDirty={v=>{const key=`${group.id}:${page}:${date}`;if(v)noteDirty.current.add(key);else noteDirty.current.delete(key);reportDirty();}}/>)}
 </div>;})}</section>;})}</>}
 </div></div></section>;
}
function RecordSetSummary({input}:{input:WorkoutInput}){
 if(repeatedWorkoutPattern(input))return <span className="record-set-summary record-interval-summary"><IntervalPattern workout={input}/></span>;
 const cardio=measurementType(input)!=='repetitions';
 const groups: {value:string;start:number;count:number}[]=[];
 input.sets.forEach((set,i)=>{const value=formatWorkoutSet(input,set),last=groups.at(-1);if(last?.value===value)last.count++;else groups.push({value,start:i+1,count:1});});
 return <span className="record-set-summary" aria-label={`${input.sets.length}${cardio?'구간':'세트'}`}>
 {groups.map(group=><span className="record-set-chip" key={group.start}><small>{group.start}{group.count>1?`–${group.start+group.count-1}`:''}{cardio?'구간':'세트'}</small><b>{group.value}</b></span>)}
 </span>;
}
function PageDate({memberId,file,data,page,rows,online,onBeforeApply}:{memberId:string;file:MemberFile;data?:SavedImport;page:number;rows:SourceRow[];online:boolean;onBeforeApply:()=>boolean}){
 const dates=[...new Set(rows.map(r=>r.input.date).filter(Boolean))];const base=dates.length===1?dates[0]:'';
 const [date,setDate]=useState(base),[busy,setBusy]=useState(false),[error,setError]=useState(''),[notice,setNotice]=useState('');
 useEffect(()=>{setDate(base);},[base]);
 async function apply(){if(busy||!date||!data)return;if(!onBeforeApply())return;if(dates.some(d=>d!==date)&&!window.confirm(`${page}쪽의 서로 다른 날짜도 ${date}로 변경할까요?`))return;setBusy(true);setError('');setNotice('');try{await callAi({action:'review',memberId,fileId:file.id,revision:data.revision,operation:'date',page,date});setNotice('이 페이지 날짜를 적용했어요.');}catch(e){setError(aiMessage(e));}finally{setBusy(false);}}
 return <div className="record-page-overview"><div className="page-date"><label>{file.contentType==='application/pdf'?`${page}쪽 날짜`:'운동 날짜'}<input aria-label={`${file.name} ${page}쪽 전체 날짜`} type="date" min="1900-01-01" max="2100-12-31" value={date} onChange={e=>{setDate(e.target.value);setNotice('');}}/></label><button disabled={!online||busy||!date||!rows.length||data?.status!=='ready'} onClick={()=>void apply()}>{busy?'적용 중…':'이 페이지 전체 적용'}</button>{dates.length>1&&<small>서로 다른 날짜 {dates.length}개</small>}{error&&<p className="file-error" role="alert">{error}</p>}{notice&&<small role="status">{notice}</small>}</div><div className="record-page-total"><span>전체 세트·구간</span><strong>{rows.reduce((n,row)=>n+row.input.sets.length,0)}<small>개</small></strong></div></div>;
}
function FileReviewStatus({memberId,memberName,online,active,data,rows,onRow,onUnparsed,onBeforeApply}:{memberId:string;memberName:string;online:boolean;active?:MemberFile;data?:SavedImport;rows:SourceRow[];onRow:(r:SourceRow)=>void;onUnparsed:(i:number)=>void;onBeforeApply:()=>boolean}){
 const [year,setYear]=useState(String(data?.year||new Date().getFullYear())),[error,setError]=useState(''),[busy,setBusy]=useState(false),[now,setNow]=useState(Date.now());
 const pending=rows.filter(r=>r.review==='needs-review'&&!r.alertDismissed),unparsed=visibleUnparsed(data);
 useEffect(()=>{const t=setInterval(()=>setNow(Date.now()),30000);return()=>clearInterval(t);},[]);
 async function bulk(operation:'year'|'member'){if(!data||busy||!onBeforeApply())return;setBusy(true);setError('');try{await callAi({action:'review',memberId,fileId:data.id,revision:data.revision,operation,...(operation==='year'?{year:+year}:{})});}catch(e){setError(aiMessage(e));}finally{setBusy(false);}}
 async function dismiss(alertKey:string){if(!data||busy||!online)return;setBusy(true);setError('');try{await callAi({action:'review',memberId,fileId:data.id,operation:'dismiss-alert',alertKey});}catch(e){setError(aiMessage(e));}finally{setBusy(false);}}
 const dismissButton=(key:string,label:string)=><button className="review-alert-dismiss" aria-label={`${label} 확인 알림 닫기`} title="알림 닫기 · 운동 기록은 유지돼요" disabled={busy||!online||data?.status!=='ready'} onClick={()=>void dismiss(key)}><Icon name="close" size={16}/></button>;
 const stalled=data?.status==='processing'&&!!data.startedAt&&now-data.startedAt.toMillis()>180000;
 return <>{data?.status==='processing'&&<p className="source-reading" role="status">원본 판독 중…</p>}{(data?.status==='error'||data?.status==='limited'||stalled)&&<div className="ai-review-issues"><p>{data?.error||'판독이 지연되고 있어요.'}</p><button disabled={busy||!online} onClick={async()=>{setError('');setBusy(true);try{await callAi({action:'read',memberId,fileId:data!.id,retry:true});}catch(e){setError(aiMessage(e));}finally{setBusy(false);}}}>판독 다시 시도</button></div>}
 {serverAiEnabled&&active?.status==='ready'&&!data&&<p className="source-reading">판독 준비 중…</p>}
 {!!(pending.length+unparsed.length)&&<div className="source-bulk review-checklist"><strong>확인할 내용 {pending.length+unparsed.length}개</strong><ul>{pending.map(r=><li key={r.id}><button onClick={()=>onRow(r)}><span><strong>{r.input.sourcePage}쪽 · {r.input.exerciseName||r.input.rawName||'운동명'}</strong><small>{[...new Set(r.issues)].join(' · ')||'판독 값 확인'}</small></span><Icon name="edit" size={16}/></button>{dismissButton(rowAlertKey(r),r.input.exerciseName||r.input.rawName||'운동')}</li>)}{unparsed.map(({value:v,index:i})=><li key={unparsedAlertKey(v)}><button onClick={()=>onUnparsed(i)}><span><strong>{v.page}쪽 · {v.text}</strong><small>{v.reason}</small></span><Icon name="edit" size={16}/></button>{dismissButton(unparsedAlertKey(v),`${v.page}쪽 ${v.text}`)}</li>)}</ul>{!data?.memberConfirmed&&pending.some(r=>r.issues.some(i=>i.includes('이름')))&&<button disabled={busy||!online} onClick={()=>void bulk('member')}>{memberName} 회원의 일지 맞아요</button>}</div>}
 {data?.status==='ready'&&<details className="record-year-setting"><summary>기본 연도 · {data.year||new Date().getFullYear()}년</summary><label>원본에 연도가 없는 기록<input aria-label="기본 기록 연도" type="number" min={1900} max={2100} value={year} onChange={e=>setYear(e.target.value)}/></label><button disabled={busy||!online||!/^\d{4}$/.test(year)||+year<1900||+year>2100} onClick={()=>void bulk('year')}>연도 적용</button><small>직접 확정한 날짜는 페이지 날짜에서 수정하세요.</small></details>}{error&&<p className="file-error" role="alert">{error}</p>}</>;
}

function InlineCorrection({memberId,row,online,onDirty,onClose,onSaved,onExplain,onBusy}:{memberId:string;row:SourceRow;online:boolean;onDirty:(v:boolean)=>void;onClose:()=>void;onSaved:()=>void;onBusy:(v:boolean)=>void;onExplain?:(input:WorkoutInput)=>void}){
 const form=useRef<HTMLFormElement>(null);
 useEffect(()=>{const el=form.current;el?.scrollIntoView({block:'nearest'});(el?.querySelector<HTMLInputElement>('input:invalid')||el?.querySelector<HTMLInputElement>('input'))?.focus({preventScroll:true});},[]);
 const [input,setInput]=useState(row.input),[remember,setRemember]=useState(false),[busy,setBusy]=useState(false),[error,setError]=useState('');const changed=remember||JSON.stringify(input)!==JSON.stringify(row.input);
 useEffect(()=>{if(!changed)return;const warn=(e:BeforeUnloadEvent)=>{e.preventDefault();e.returnValue='';};window.addEventListener('beforeunload',warn);return()=>window.removeEventListener('beforeunload',warn);},[changed]);
 function edit(patch:Partial<WorkoutInput>){const v={...input,...patch};setInput(v);onDirty(remember||JSON.stringify(v)!==JSON.stringify(row.input));}
 async function submit(e:FormEvent){e.preventDefault();if(busy||!online)return;setError('');setBusy(true);onBusy(true);try{const v=validateWorkout(input);if(row.fileId!==undefined)await callAi({action:'review',memberId,fileId:row.fileId,operation:row.isNew?'add':'row',...(row.unparsedIndex!==undefined?{unparsedIndex:row.unparsedIndex}:{}),rowId:row.id,revision:row.importRevision,rowRevision:row.rowRevision,recordRevision:row.existing?.revision??0,input:v,reason:v.notes,...(remember?{rememberInterpretation:true}:{})});else await saveWorkout(memberId,v,row.existing);onSaved();}catch(e){setError(aiMessage(e));}finally{setBusy(false);onBusy(false);}}
 return <form ref={form} className="inline-correction" onSubmit={e=>void submit(e)}><fieldset disabled={busy}><div className="record-editor-basics"><label>운동명<input aria-label="수정할 운동명" value={input.exerciseName} maxLength={100} required onChange={e=>edit({exerciseName:e.target.value})}/></label><div className="inline-pair"><label>날짜<input aria-label="수정할 운동 날짜" type="date" required value={input.date} min="1900-01-01" max="2100-12-31" onChange={e=>edit({date:e.target.value})}/></label><div className="record-select-field"><span>운동 부위</span><WorkoutSelect label="수정할 운동 부위" value={input.bodyPart} options={BODY_PARTS.map(value=>({value,label:value}))} onChange={bodyPart=>edit({bodyPart})}/></div></div></div><div className="record-editor-section"><MeasurementFields input={input} onChange={edit}/></div><label className="record-editor-section session-note-field">운동 메모<textarea aria-label="운동 메모" rows={2} maxLength={1000} placeholder="예: 스쿼트 중 무릎 불편감 호소. 가동 범위와 중량 조절." value={input.trainerNote??''} onChange={e=>edit({trainerNote:e.target.value})}/></label><details className="record-editor-section record-editor-notes"><summary>메모 · 판독 참고{input.notes.trim()?' · 메모 있음':''}</summary><label>수정 이유·메모<textarea rows={2} placeholder="예: 스키에르그 200m를 마친 시간(초). 구간 사이 60초 휴식." maxLength={1000} value={input.notes} onChange={e=>edit({notes:e.target.value})}/></label>{row.fileId&&<label className="record-confirm"><input type="checkbox" checked={remember} disabled={!input.notes.trim()} onChange={e=>{setRemember(e.target.checked);onDirty(e.target.checked||JSON.stringify(input)!==JSON.stringify(row.input));}}/>이 표기와 설명을 내 계정의 다음 판독에도 참고</label>}{onExplain&&<button className="record-explain-button" type="button" onClick={()=>onExplain(input)}><Icon name="spark" size={15}/> AI 도우미에 질문</button>}</details></fieldset>{error&&<p className="file-error" role="alert">{error}</p>}<div className="button-wrap"><button type="button" disabled={busy} onClick={onClose}>취소</button><button className="primary" disabled={busy||!online||(!changed&&!remember&&!row.isNew&&row.review!=='needs-review')}>{busy?'저장 중…':'수정 반영'}</button></div></form>;
}
