"use client";
import {useEffect,useId,useRef,useState,type RefObject} from 'react';
import {Icon} from './icons';
export function AnalysisTools({memberId,contentRef,online,busy,canRegenerate,onRegenerate}:{memberId:string;contentRef:RefObject<HTMLDivElement|null>;online:boolean;busy:boolean;canRegenerate:boolean;onRegenerate:()=>Promise<void>}){
 const id=useId(),menu=useRef<HTMLDivElement>(null),trigger=useRef<HTMLButtonElement>(null),[scale,setScale]=useState(100),[notice,setNotice]=useState(''),[printing,setPrinting]=useState(false);
 useEffect(()=>{try{const v=Number(localStorage.getItem('tn-analysis-text:'+memberId));if([100,112.5,125,150,200].includes(v))setScale(v);}catch{}},[memberId]);
 useEffect(()=>{if(contentRef.current)contentRef.current.style.zoom=String(scale/100);},[scale,contentRef]);
 function size(v:number){setScale(v);try{localStorage.setItem('tn-analysis-text:'+memberId,String(v));}catch{}}
 function clean(){const copy=contentRef.current?.cloneNode(true) as HTMLElement|undefined;if(!copy)return;copy.style.zoom='1';copy.querySelectorAll('button,form,input,select,textarea,.ai-usage,.live-review-banner,.live-processing').forEach(e=>e.remove());copy.querySelectorAll('details').forEach(e=>e.setAttribute('open',''));return copy;}
 function close(){menu.current?.hidePopover();trigger.current?.focus();}
 async function copy(){close();const el=clean();if(!el)return;try{const holder=document.createElement('div');holder.style.cssText='position:fixed;left:-10000px;width:700px';holder.append(el);document.body.append(holder);const text=el.innerText;holder.remove();await navigator.clipboard.writeText(text);setNotice('분석 내용을 복사했어요.');}catch{setNotice('클립보드에 접근할 수 없어요. 브라우저 권한을 확인해주세요.');}}
 async function print(){close();const content=clean();if(!content||printing)return;setPrinting(true);const frame=document.createElement('iframe');frame.title='분석 PDF 인쇄';frame.style.cssText='position:fixed;right:0;bottom:0;width:1px;height:1px;border:0';document.body.append(frame);try{const doc=frame.contentDocument!;doc.open();doc.write('<!doctype html><html lang="ko"><head><title>진행 분석</title></head><body></body></html>');doc.close();document.querySelectorAll('style,link[rel="stylesheet"]').forEach(el=>doc.head.append(el.cloneNode(true)));const style=doc.createElement('style');style.textContent='@page{size:A4;margin:16mm}html,body{height:auto!important;overflow:visible!important;background:white!important;color:#202920!important}.pane-body{overflow:visible!important;height:auto!important;max-height:none!important;padding:0!important;zoom:1!important}h1{font-size:26px}article,.quiet-card{break-inside:avoid}button{display:none!important}';doc.head.append(style);doc.body.append(content);await Promise.all([...doc.querySelectorAll<HTMLLinkElement>('link')].map(l=>l.sheet?Promise.resolve():new Promise<void>(resolve=>{l.onload=()=>resolve();l.onerror=()=>resolve();setTimeout(resolve,3000);})));await doc.fonts.ready;frame.contentWindow!.focus();frame.contentWindow!.print();setNotice('인쇄 창에서 PDF로 저장을 선택하세요.');}catch{setNotice('인쇄 창을 열지 못했어요. 다시 시도해주세요.');}finally{setPrinting(false);setTimeout(()=>frame.remove(),60000);}}
 function position(){const b=trigger.current?.getBoundingClientRect(),el=menu.current;if(b&&el){el.style.left=Math.max(8,Math.min(innerWidth-308,b.right-300))+'px';el.style.top=Math.max(8,Math.min(b.bottom+6,innerHeight-280))+'px';}}
 return <div className="analysis-actions"><span role="status">{notice}</span><button ref={trigger} popoverTarget={id} className="icon-button" aria-label="진행 분석 메뉴" title="분석 설정" onClick={position}><Icon name="more"/></button><div id={id} ref={menu} popover="auto" className="analysis-options"><strong>글자 크기</strong><div className="analysis-font-sizes">{[100,112.5,125,150,200].map(v=><button key={v} aria-pressed={scale===v} onClick={()=>size(v)}>{v}%</button>)}</div><button disabled={!online||busy||!canRegenerate} onClick={()=>{close();if(window.confirm('최신 기록으로 AI 분석을 다시 생성할까요? AI 이용량이 차감됩니다.'))void onRegenerate();}}>다시 생성</button><button onClick={()=>void copy()}>클립보드에 복사</button><button disabled={printing} onClick={()=>void print()}>PDF로 저장</button></div></div>;
}
