"use client";
import {useEffect,useRef,useState,type FormEvent} from 'react';
import {Icon} from './icons';
import {ContinuousSourceViewer} from './continuous-source-viewer';
import {type MemberFile} from '../lib/member-files';
import {BODY_PARTS,saveWorkout,validateWorkout,type WorkoutInput,type WorkoutRecord} from '../lib/workout-records';
import {serverAiEnabled,callAi,aiMessage,type SavedImport} from '../lib/server-ai';
export type SourceRow={id:string;input:WorkoutInput;issues:string[];review:string;fileId?:string;importRevision?:number;unparsedIndex?:number;isNew?:boolean;compound?:import('../lib/workout-extraction').ExtractedWorkout['compound'];existing?:WorkoutRecord};
export function sourceRows(imports:SavedImport[],records:WorkoutRecord[]):SourceRow[]{
 const rows:SourceRow[]=imports.flatMap(file=>file.rows.filter(row=>row.review!=='ignored').map(row=>({id:row.id,input:row.input,issues:row.issues,review:row.review,fileId:file.id,importRevision:file.revision,compound:row.compound})));
 for(const r of records){const i=rows.findIndex(row=>row.id===r.id);const input:WorkoutInput={date:r.date,rawName:r.rawName,exerciseName:r.exerciseName,bodyPart:r.bodyPart,loadType:r.loadType,sets:r.sets,sourceName:r.sourceName,sourceHash:r.sourceHash,sourcePage:r.sourcePage,notes:r.notes};if(i>=0)rows[i]={...rows[i],input,existing:r};else rows.push({id:r.id,input,issues:[],review:r.status==='confirmed'?'confirmed':'auto',existing:r});}
 return rows;
}
export function AnalysisSource({memberId,memberName,online,files,imports,rows,selectedFile,onFile,selectedRow,onRow,onUpload,onDirty,originalRequest=0,recordsOnly=false,onOriginal,sourcePage=1,recordJump=0}:{memberId:string;memberName:string;online:boolean;files:MemberFile[];imports:SavedImport[];rows:SourceRow[];selectedFile:string;onFile:(id:string)=>void;selectedRow:string;onRow:(id:string)=>void;onUpload:()=>void;onDirty:(v:boolean)=>void;originalRequest?:number;recordsOnly?:boolean;onOriginal?:(id:string,page:number)=>void;sourcePage?:number;recordJump?:number}){
 const [tab,setTab]=useState(recordsOnly?'records':'original'),[edit,setEdit]=useState<SourceRow|null>(null);
 const dirty=useRef(false),scrollRef=useRef<HTMLDivElement>(null),groupRefs=useRef(new Map<string,HTMLElement>()),pageRefs=useRef(new Map<string,HTMLElement>()),rowRefs=useRef(new Map<string,HTMLElement>());
 const chosen=rows.find(r=>r.id===selectedRow);
 const groups=files.map(file=>({id:file.id,file,data:imports.find(i=>i.id===file.id),rows:rows.filter(r=>(r.fileId||r.input.sourceHash)===file.id)}));
 const extra=rows.filter(r=>!files.some(f=>f.id===(r.fileId||r.input.sourceHash)));
 const recordGroups=[...groups,...(extra.length?[{id:'other',file:undefined,data:undefined,rows:extra}]:[])].filter(g=>recordsOnly||selectedFile==='all'||g.id===selectedFile);
 function scrollTo(el?:HTMLElement){const root=scrollRef.current;if(el&&root)root.scrollTop+=el.getBoundingClientRect().top-root.getBoundingClientRect().top-12;}
 function clearEditor(){if(dirty.current&&!window.confirm('저장하지 않은 수정 내용이 있어요. 버리고 이동할까요?'))return false;dirty.current=false;onDirty(false);setEdit(null);return true;}
 function safeSwitch(action:()=>void){if(clearEditor())action();}
 function begin(row:SourceRow){safeSwitch(()=>{if(!row.isNew)onRow(row.id);else onOriginal?.(row.fileId||row.input.sourceHash,row.input.sourcePage||1);setEdit(row);});}
 function add(file:MemberFile,page:number,data?:SavedImport,index?:number){const raw=index===undefined?undefined:data?.unparsed[index];const same=rows.find(r=>r.input.sourceHash===file.id&&r.input.sourcePage===page&&r.input.date);begin({id:crypto.randomUUID().replaceAll('-','').slice(0,20),isNew:true,unparsedIndex:index,fileId:data?.status==='ready'?file.id:undefined,importRevision:data?.revision,review:'needs-review',issues:raw?[raw.reason]:[],input:{date:same?.input.date||'',rawName:raw?.text.slice(0,100)||'',exerciseName:'',bodyPart:'미분류',loadType:'unknown',sets:[{kg:null,reps:0}],sourceHash:file.id,sourceName:file.name,sourcePage:page,notes:raw?`${raw.text} — ${raw.reason}`.slice(0,1000):''}});}
 useEffect(()=>{if(originalRequest&&!recordsOnly){setTab('original');setEdit(null);dirty.current=false;onDirty(false);}},[originalRequest]);
 useEffect(()=>{if(!selectedRow)return;setTab('records');if(edit?.id!==selectedRow)setEdit(null);const t=setTimeout(()=>scrollTo(rowRefs.current.get(selectedRow)),0);return()=>clearTimeout(t);},[selectedRow]);
 useEffect(()=>{if(!recordJump)return;setEdit(null);dirty.current=false;onDirty(false);setTab('records');const t=setTimeout(()=>scrollTo(pageRefs.current.get(`${selectedFile}:${sourcePage}`)||groupRefs.current.get(selectedFile)),0);return()=>clearTimeout(t);},[recordJump]);
 function moveToFile(id:string){safeSwitch(()=>{onFile(id);if(id==='all')scrollRef.current?.scrollTo({top:0});else scrollTo(groupRefs.current.get(id));});}
 function editor(row:SourceRow){return <InlineCorrection key={row.id} memberId={memberId} row={row} online={online} onDirty={v=>{dirty.current=v;onDirty(v);}} onClose={()=>safeSwitch(()=>setEdit(null))} onSaved={()=>{dirty.current=false;onDirty(false);setEdit(null);}}/>;}
 return <section className={'live-pane live-source'+(recordsOnly?' records-only':'')} aria-label="원본과 판독 기록"><div className="source-switch" hidden={recordsOnly}><button onClick={()=>setTab('records')}>판독 기록</button><button onClick={()=>setTab('original')}>원본 파일</button></div><div className="pdf-toolbar"><select aria-label="분석 원본 선택" value={selectedFile} onChange={e=>moveToFile(e.target.value)}><option value="all">전체 판독 기록 · 이어 보기</option>{files.map(f=><option key={f.id} value={f.id}>{f.name}</option>)}</select><button className="icon-button" onClick={onUpload} aria-label="일지 추가"><Icon name="plus" size={16}/></button></div><div ref={scrollRef} className="live-source-scroll">
 {tab==='original'?<ContinuousSourceViewer memberId={memberId} files={files} selectedFile={selectedFile} sourcePage={chosen?.input.sourcePage||1}/>:<>
 {!files.length&&!rows.length&&<div className="empty-state"><button className="primary" onClick={onUpload}>운동일지 업로드</button></div>}
 {recordGroups.map((group,index)=>{const pages=[...new Set([...group.rows.map(r=>r.input.sourcePage||1),...(group.data?.unparsed.map(r=>r.page)||[]),...(selectedFile===group.id?[sourcePage]:[]),...(edit?.input.sourceHash===group.id?[edit.input.sourcePage]:[]),1])].sort((a,b)=>a-b);return <section key={group.id} ref={el=>{if(el)groupRefs.current.set(group.id,el);else groupRefs.current.delete(group.id);}} className="record-file-group" data-record-file={group.id} aria-label={group.file?.name||'기타 운동 기록'}>
 <header className="record-file-heading"><span className="original-file-number">{String(index+1).padStart(2,'0')}</span><div><strong>{group.file?.name||'직접 입력·기타 기록'}</strong><small>{group.data?.status==='ready'?'판독 완료':'원본별 기록'}</small></div></header>
 <FileReviewStatus memberId={memberId} memberName={memberName} online={online} active={group.file} data={group.data} rows={group.rows} onBeforeApply={clearEditor} onRow={begin} onUnparsed={i=>{if(group.file)add(group.file,group.data!.unparsed[i].page,group.data,i);}}/>
 {pages.map(page=>{const visible=group.rows.filter(r=>(r.input.sourcePage||1)===page);return <div className="live-paper linked-record-paper" key={page} data-record-page={page} tabIndex={0} aria-label={`${group.file?.name||'기타 기록'} ${page}쪽 판독 카드 · 원본 열기`} onClick={e=>{if(!(e.target as HTMLElement).closest('button,input,select,textarea,a,label,form,summary'))onOriginal?.(group.id,page);}} onKeyDown={e=>{if(e.target===e.currentTarget&&(e.key==='Enter'||e.key===' ')){e.preventDefault();onOriginal?.(group.id,page);}}} ref={el=>{const k=`${group.id}:${page}`;if(el)pageRefs.current.set(k,el);else pageRefs.current.delete(k);}}><h2 className="paper-title">판독 기록 <small>{group.file?.name||'직접 입력·기타 기록'}{group.file?.contentType==='application/pdf'?` · ${page}쪽`:''}</small></h2>
 {group.file&&<PageDate key={`${group.id}:${page}`} memberId={memberId} file={group.file} data={group.data} page={page} rows={visible} online={online} onBeforeApply={clearEditor}/>}
 <div className="live-record-heading"><span>운동 <b className="exercise-count">{visible.length}</b></span><span>kg × 회</span></div>{visible.map(row=><div key={row.id} ref={el=>{if(el)rowRefs.current.set(row.id,el);else rowRefs.current.delete(row.id);}} className={'live-record-row '+(row.id===selectedRow?'is-selected':'')}><button className="live-record-select" aria-label={`${row.input.exerciseName||row.input.rawName} 판독 값 수정`} aria-expanded={edit?.id===row.id} onClick={()=>begin(row)}><span><strong>{row.input.exerciseName||row.input.rawName||'운동명 확인 필요'}</strong><small>{row.input.date||'날짜 확인 필요'} · {page}쪽</small></span><span>{row.input.sets.map((s,i)=><small key={i}>{row.input.loadType==='bodyweight'?'맨몸':s.kg===null?'?':s.kg} × {s.reps||'?'}</small>)}</span><Icon name="edit" size={14}/></button>{row.compound&&<p className="compound-label">{row.compound.rawName} · 분리 {row.compound.index}/{row.compound.total}</p>}{edit?.id===row.id&&editor(edit)}</div>)}
 {edit?.isNew&&edit.input.sourceHash===group.id&&edit.input.sourcePage===page&&editor(edit)}
 {group.file&&<button className="paper-add" disabled={!online||group.file.status!=='ready'||group.data?.status==='processing'} onClick={()=>add(group.file!,page,group.data)}><Icon name="plus" size={18}/> 운동 추가</button>}
 </div>;})}</section>;})}</>}
 </div></section>;
}
function PageDate({memberId,file,data,page,rows,online,onBeforeApply}:{memberId:string;file:MemberFile;data?:SavedImport;page:number;rows:SourceRow[];online:boolean;onBeforeApply:()=>boolean}){
 const dates=[...new Set(rows.map(r=>r.input.date).filter(Boolean))];const base=dates.length===1?dates[0]:'';
 const [date,setDate]=useState(base),[busy,setBusy]=useState(false),[error,setError]=useState(''),[notice,setNotice]=useState('');
 useEffect(()=>{setDate(base);},[base]);
 async function apply(){if(busy||!date||!data)return;if(!onBeforeApply())return;if(dates.some(d=>d!==date)&&!window.confirm(`${page}쪽의 서로 다른 날짜도 ${date}로 변경할까요?`))return;setBusy(true);setError('');setNotice('');try{await callAi({action:'review',memberId,fileId:file.id,revision:data.revision,operation:'date',page,date});setNotice('이 페이지 날짜를 적용했어요.');}catch(e){setError(aiMessage(e));}finally{setBusy(false);}}
 return <div className="page-date"><label>{file.contentType==='application/pdf'?`${page}쪽 날짜`:'운동 날짜'}<input aria-label={`${file.name} ${page}쪽 전체 날짜`} type="date" min="1900-01-01" max="2100-12-31" value={date} onChange={e=>{setDate(e.target.value);setNotice('');}}/></label><button disabled={!online||busy||!date||!rows.length||data?.status!=='ready'} onClick={()=>void apply()}>{busy?'적용 중…':'이 페이지 전체 적용'}</button>{dates.length>1&&<small>서로 다른 날짜 {dates.length}개</small>}{error&&<p className="file-error" role="alert">{error}</p>}{notice&&<small role="status">{notice}</small>}</div>;
}
function FileReviewStatus({memberId,memberName,online,active,data,rows,onRow,onUnparsed,onBeforeApply}:{memberId:string;memberName:string;online:boolean;active?:MemberFile;data?:SavedImport;rows:SourceRow[];onRow:(r:SourceRow)=>void;onUnparsed:(i:number)=>void;onBeforeApply:()=>boolean}){
 const [year,setYear]=useState(String(data?.year||new Date().getFullYear())),[error,setError]=useState(''),[busy,setBusy]=useState(false),[now,setNow]=useState(Date.now());
 const pending=rows.filter(r=>r.review==='needs-review'),unparsed=data?.unparsed||[];
 useEffect(()=>{const t=setInterval(()=>setNow(Date.now()),30000);return()=>clearInterval(t);},[]);
 async function bulk(operation:'year'|'member'){if(!data||busy||!onBeforeApply())return;setBusy(true);setError('');try{await callAi({action:'review',memberId,fileId:data.id,revision:data.revision,operation,...(operation==='year'?{year:+year}:{})});}catch(e){setError(aiMessage(e));}finally{setBusy(false);}}
 const stalled=data?.status==='processing'&&!!data.startedAt&&now-data.startedAt.toMillis()>180000;
 return <>{data?.status==='processing'&&<p className="source-reading" role="status">원본 판독 중…</p>}{(data?.status==='error'||data?.status==='limited'||stalled)&&<div className="ai-review-issues"><p>{data?.error||'판독이 지연되고 있어요.'}</p><button disabled={busy||!online} onClick={async()=>{setBusy(true);try{await callAi({action:'read',memberId,fileId:data!.id,retry:true});}catch(e){setError(aiMessage(e));}finally{setBusy(false);}}}>판독 다시 시도</button></div>}
 {serverAiEnabled&&active?.status==='ready'&&!data&&<p className="source-reading">판독 준비 중…</p>}
 {!!(pending.length+unparsed.length)&&<div className="source-bulk review-checklist"><strong>확인할 내용 {pending.length+unparsed.length}개</strong><ul>{pending.map(r=><li key={r.id}><button onClick={()=>onRow(r)}><span><strong>{r.input.sourcePage}쪽 · {r.input.exerciseName||r.input.rawName||'운동명'}</strong><small>{[...new Set(r.issues)].join(' · ')||'판독 값 확인'}</small></span><Icon name="edit" size={16}/></button></li>)}{unparsed.map((v,i)=><li key={`raw-${i}`}><button onClick={()=>onUnparsed(i)}><span><strong>{v.page}쪽 · {v.text}</strong><small>{v.reason}</small></span><Icon name="edit" size={16}/></button></li>)}</ul>{!data?.memberConfirmed&&pending.some(r=>r.issues.some(i=>i.includes('이름')))&&<button disabled={busy||!online} onClick={()=>void bulk('member')}>{memberName} 회원의 일지 맞아요</button>}</div>}
 {data?.status==='ready'&&<details className="record-year-setting"><summary>기본 연도 · {data.year||new Date().getFullYear()}년</summary><label>원본에 연도가 없는 기록<input aria-label="기본 기록 연도" type="number" min={1900} max={2100} value={year} onChange={e=>setYear(e.target.value)}/></label><button disabled={busy||!online||!/^\d{4}$/.test(year)||+year<1900||+year>2100} onClick={()=>void bulk('year')}>연도 적용</button><small>직접 확정한 날짜는 페이지 날짜에서 수정하세요.</small></details>}{error&&<p className="file-error" role="alert">{error}</p>}</>;
}

function InlineCorrection({memberId,row,online,onDirty,onClose,onSaved}:{memberId:string;row:SourceRow;online:boolean;onDirty:(v:boolean)=>void;onClose:()=>void;onSaved:()=>void}){
 const form=useRef<HTMLFormElement>(null);
 useEffect(()=>{const el=form.current;el?.scrollIntoView({block:'nearest'});(el?.querySelector<HTMLInputElement>('input:invalid')||el?.querySelector<HTMLInputElement>('input'))?.focus({preventScroll:true});},[]);
 const [input,setInput]=useState(row.input),[busy,setBusy]=useState(false),[error,setError]=useState('');const changed=JSON.stringify(input)!==JSON.stringify(row.input);
 useEffect(()=>{if(!changed)return;const warn=(e:BeforeUnloadEvent)=>{e.preventDefault();e.returnValue='';};window.addEventListener('beforeunload',warn);return()=>window.removeEventListener('beforeunload',warn);},[changed]);
 function edit(patch:Partial<WorkoutInput>){const v={...input,...patch};setInput(v);onDirty(JSON.stringify(v)!==JSON.stringify(row.input));}
 async function submit(e:FormEvent){e.preventDefault();if(busy||!online)return;setError('');setBusy(true);try{const v=validateWorkout(input);if(row.fileId!==undefined)await callAi({action:'review',memberId,fileId:row.fileId,operation:row.isNew?'add':'row',...(row.unparsedIndex!==undefined?{unparsedIndex:row.unparsedIndex}:{}),rowId:row.id,revision:row.importRevision,input:v,reason:v.notes});else await saveWorkout(memberId,v,row.existing);onSaved();}catch(e){setError(aiMessage(e));}finally{setBusy(false);}}
 return <form ref={form} className="inline-correction" onSubmit={e=>void submit(e)}><fieldset disabled={busy}><label>운동명<input aria-label="수정할 운동명" value={input.exerciseName} maxLength={100} required onChange={e=>edit({exerciseName:e.target.value})}/></label><div className="inline-pair"><label>날짜<input aria-label="수정할 운동 날짜" type="date" required value={input.date} min="1900-01-01" max="2100-12-31" onChange={e=>edit({date:e.target.value})}/></label><label>운동 부위<select aria-label="수정할 운동 부위" value={input.bodyPart} onChange={e=>edit({bodyPart:e.target.value})}>{BODY_PARTS.map(v=><option key={v}>{v}</option>)}</select></label></div><label>중량 기준<select value={input.loadType} onChange={e=>edit({loadType:e.target.value as WorkoutInput['loadType'],sets:input.sets.map(s=>({...s,kg:null}))})}><option value="weighted">kg</option><option value="bodyweight">맨몸</option><option value="unknown">미상</option></select></label>{input.sets.map((s,i)=><div className="inline-set" key={i}><span>{i+1}세트</span><input type="number" aria-label={`수정 ${i+1}세트 중량`} min="0.01" max={2000} step="any" required={input.loadType==='weighted'} disabled={input.loadType!=='weighted'} value={s.kg??''} placeholder="kg" onChange={e=>edit({sets:input.sets.map((s,j)=>i===j?{...s,kg:e.target.value===''?null:+e.target.value}:s)})}/><span>×</span><input type="number" aria-label={`수정 ${i+1}세트 횟수`} min={1} max={1000} step={1} required value={s.reps||''} placeholder="회" onChange={e=>edit({sets:input.sets.map((s,j)=>i===j?{...s,reps:+e.target.value}:s)})}/><button type="button" aria-label={`수정 ${i+1}세트 삭제`} disabled={input.sets.length<=1} onClick={()=>edit({sets:input.sets.filter((_,j)=>j!==i)})}>−</button></div>)}<button type="button" disabled={input.sets.length>=8} onClick={()=>edit({sets:[...input.sets,{kg:null,reps:0}]})}>세트 추가</button><label>수정 이유·메모<textarea rows={2} maxLength={1000} value={input.notes} onChange={e=>edit({notes:e.target.value})}/></label></fieldset><p>원본 재판독 없이 저장해요. 통계는 즉시, AI 의견은 변경 내용을 모아 갱신해요.</p>{error&&<p className="file-error" role="alert">{error}</p>}<div className="button-wrap"><button type="button" disabled={busy} onClick={onClose}>취소</button><button className="primary" disabled={busy||!online||(!changed&&!row.isNew&&row.review!=='needs-review')}>{busy?'저장 중…':'수정 반영'}</button></div></form>;
}
