"use client";
import {useId,useRef,useState} from 'react';
import {Icon} from './icons';
export function AssistantModelMenu({value,disabled,onChange}:{value:'quick'|'deep';disabled:boolean;onChange:(value:'quick'|'deep')=>void}){
 const id=useId(),trigger=useRef<HTMLButtonElement>(null),menu=useRef<HTMLDivElement>(null),[open,setOpen]=useState(false),[position,setPosition]=useState({left:0,top:0});
 function place(){const r=trigger.current?.getBoundingClientRect();if(r)setPosition({left:Math.max(12,Math.min(r.left,window.innerWidth-284)),top:Math.max(12,r.top-170)});}
 function close(){menu.current?.hidePopover();trigger.current?.focus({preventScroll:true});}
 return <><button type="button" ref={trigger} disabled={disabled} className="assistant-model-trigger" popoverTarget={id} aria-label="답변 모델 선택" aria-expanded={open} onClick={place} onKeyDown={e=>{if(e.key==='ArrowUp'||e.key==='ArrowDown'){e.preventDefault();place();menu.current?.showPopover();menu.current?.querySelector<HTMLButtonElement>('button')?.focus();}}}>{value==='deep'?'고급 모델':'기본 모델'}<Icon name="chevron" size={14}/></button><div id={id} ref={menu} popover="auto" className="assistant-model-menu" style={position} role="group" aria-label="답변 모델" onToggle={e=>setOpen(e.newState==='open')} onKeyDown={e=>{if(e.key==='Escape'){e.preventDefault();close();}if(e.key==='ArrowUp'||e.key==='ArrowDown'){e.preventDefault();const buttons=Array.from(menu.current?.querySelectorAll('button')??[]),index=buttons.indexOf(document.activeElement as HTMLButtonElement);buttons[(index+1)%buttons.length]?.focus();}}}>{([{id:'quick',label:'기본 모델',hint:'빠르게 핵심을 정리해요'},{id:'deep',label:'고급 모델',hint:'근거와 대안을 더 자세히 살펴봐요'}] as const).map(mode=><button type="button" key={mode.id} disabled={disabled} aria-pressed={value===mode.id} onClick={()=>{onChange(mode.id);close();}}><span><strong>{mode.label}</strong><small>{mode.hint}</small></span>{value===mode.id&&<Icon name="check" size={16}/>}</button>)}</div></>;
}
