"use client";
import {AnalysisTools} from './analysis-tools';
import {IntervalPattern} from './interval-pattern';
import {repeatedWorkoutPattern} from '../lib/workout-display';
import {WorkoutSelect} from './workout-select';
import {useEffect,useRef,useState} from 'react';
import {callAi,aiMessage,type SavedPlan} from '../lib/server-ai';
import {formatWorkoutSet,type WorkoutSet} from '../lib/workout-measurements';
import type {LessonContext,LessonDraft,LessonItem} from '../lib/lesson-planning';
const actionNames={keep:'유지',review:'조정 검토',assess:'평가'};
export function ConnectedLessonPlan({memberId,inputKey,period,visualKey,plan,online,active,onDirty,onEvidence,onOriginal,onGoal}:{memberId:string;inputKey:string;period:string;visualKey:string;plan:SavedPlan|null;online:boolean;active:boolean;onDirty:(v:boolean)=>void;onEvidence:(link:LessonItem['evidence'][number])=>void;onOriginal:(id:string)=>void;onGoal:()=>void}){
 const contentRef=useRef<HTMLDivElement>(null),pendingGeneration=useRef<string|null>(null);
 const [context,setContext]=useState<LessonContext|null>(null),[draft,setDraft]=useState<LessonDraft|null>(plan?.lesson??null),[reason,setReason]=useState(plan?.reason??''),[dirty,setDirty]=useState(false),[busy,setBusy]=useState(false),[loading,setLoading]=useState(false),[generating,setGenerating]=useState(false),[error,setError]=useState(''),[message,setMessage]=useState(''),[preview,setPreview]=useState(false),[refresh,setRefresh]=useState(0),[editing,setEditing]=useState(''),[adding,setAdding]=useState('');
 const dirtyRef=useRef(dirty);dirtyRef.current=dirty;const dirtyCallback=useRef(onDirty);dirtyCallback.current=onDirty;const requestId=useRef(0),saveRevision=useRef(plan?.revision??0),lock=useRef(false);const cache=useRef(new Map<string,LessonContext>());
 const key=memberId+inputKey+visualKey+(plan?.revision??0);const contextCurrent=!!context&&context.inputKey===inputKey;
 useEffect(()=>{dirtyCallback.current(dirty);},[dirty]);
 useEffect(()=>{if(!dirty)return;const stop=(e:BeforeUnloadEvent)=>{e.preventDefault();e.returnValue='';};window.addEventListener('beforeunload',stop);return()=>window.removeEventListener('beforeunload',stop);},[dirty]);
 useEffect(()=>{if(!active||!online||!inputKey)return;let live=true;const id=++requestId.current;setError('');const existing=cache.current.get(key);setContext(existing??null);setLoading(!existing);
  function receive(c:LessonContext){if(!live||id!==requestId.current)return;cache.current.set(key,c);setContext(c);setLoading(false);if(c.status==='processing')pendingGeneration.current=key;const proposalArrived=pendingGeneration.current===key&&c.status==='ready'&&c.draft.source==='ai';if(pendingGeneration.current===key&&c.status!=='processing'){if(proposalArrived)setPreview(true);pendingGeneration.current=null;}if(!dirtyRef.current&&!proposalArrived){setDraft(plan?.lesson??(plan?null:c.draft));setReason(plan?.reason??'');saveRevision.current=plan?.revision??0;}}
  if(existing){receive(existing);return()=>{live=false;};}
  void callAi({action:'lessonContext',memberId,period,inputKey}).then(v=>{if((v as {stale?:boolean}).stale)throw Error('기록 동기화 후 다시 확인해주세요.');receive(v as unknown as LessonContext);}).catch(e=>{if(live){pendingGeneration.current=null;setLoading(false);setError(aiMessage(e));}});return()=>{live=false;};
 },[key,active,online,refresh,memberId,inputKey,period,plan]);
 const pollCount=useRef(0);useEffect(()=>{pollCount.current=0;pendingGeneration.current=null;},[key]);
 useEffect(()=>{if(!active||context?.status!=='processing')return;if(pollCount.current>=45){setError('제안 생성이 지연되고 있어요. 잠시 후 근거를 다시 확인해주세요.');setContext(c=>c?{...c,status:'error'}:c);pendingGeneration.current=null;return;}const timer=setTimeout(()=>{pollCount.current++;cache.current.delete(key);setRefresh(v=>v+1);},4000);return()=>clearTimeout(timer);},[active,context,key]);
 const stale=!!draft&&contextCurrent&&draft.evidenceKey!==context!.evidenceKey,changed=dirty&&(plan?.revision??0)!==saveRevision.current;
 function editItem(id:string,patch:Partial<LessonItem>){setDraft(d=>d?{...d,items:d.items.map(i=>i.id===id?{...i,...patch}:i)}:d);setDirty(true);setMessage('');}
 async function generate(retry=false){if(lock.current||!contextCurrent)return;lock.current=true;setBusy(true);setGenerating(true);pendingGeneration.current=key;pollCount.current=0;setMessage('');setError('');const capturedKey=key,capturedInput=inputKey,capturedBasis=context!.basis,id=++requestId.current;
 try{const response=await callAi({action:'generateLesson',memberId,period,inputKey:capturedInput,basis:capturedBasis,retry}) as unknown as LessonContext&{stale?:boolean};if(id!==requestId.current)return;if(response.stale)throw Error('생성 중 근거가 변경됐어요. 새 근거를 확인해주세요.');if(response.status==='processing'){setContext(response);return;}pendingGeneration.current=null;if(response.status==='error')throw Error(response.generationError||'수업 제안을 생성하지 못했어요.');cache.current.set(capturedKey,response);setContext(response);setPreview(true);}catch(e){if(id===requestId.current){pendingGeneration.current=null;setError(aiMessage(e));}}finally{lock.current=false;setBusy(false);setGenerating(false);}}
 function apply(){if(!context)return;setDraft(structuredClone(context.draft));setDirty(true);saveRevision.current=plan?.revision??0;setPreview(false);setEditing('');setMessage('새 제안을 작업 중인 계획에 반영했습니다. 저장 전까지 기존 계획 유지.');}
 async function save(){if(lock.current||!draft||!contextCurrent||stale||changed)return;lock.current=true;setBusy(true);setError('');try{await callAi({action:'saveConnectedLesson',memberId,period,inputKey,basis:context!.basis,revision:saveRevision.current,draft:{...draft,basis:context!.basis},reason});setDirty(false);setMessage('수업 계획 저장 완료');}catch(e){setError(aiMessage(e));}finally{lock.current=false;setBusy(false);}}
 const available=(context?.candidates??[]).filter(c=>!draft?.items.some(i=>i.id===c.id));const addition=available.find(c=>c.id===adding)??available[0];
 const isGenerating=generating||pendingGeneration.current===key||(contextCurrent&&context?.status==='processing');
 const view=draft;const summary=(i:LessonItem)=>i.measurementType==='assessment'?'설정한 평가':`${i.segments.length}${i.measurementType==='repetitions'?'세트':'구간'}${i.rounds?' × '+i.rounds+'라운드':''}`;
 function exportLesson(){
  const lesson=preview&&contextCurrent?context!.draft:view,root=document.createElement('div');root.className='lesson-export';
  const add=(parent:HTMLElement,tag:string,value:string)=>{const el=document.createElement(tag);el.textContent=value;parent.append(el);return el;};
  add(root,'h1','다음 수업');if(!lesson)return root;
  add(root,'p',`${lesson.from} — ${lesson.to} 기록 기준`);
  if(lesson.source==='ai'&&lesson.before?.length){add(root,'h2','수업 전 고려');const list=add(root,'ul','');lesson.before.forEach(v=>add(list,'li',v));}
  add(root,'h2','운동 프로그램');if(lesson.programSummary)add(root,'p',lesson.programSummary);
  if(lesson.programDates?.length)add(root,'p','참고 수업: '+lesson.programDates.join(' · '));
  lesson.items.forEach((item,n)=>{const article=add(root,'article','');add(article,'h3',`${n+1}. ${item.exerciseName} · ${actionNames[item.action]}`);add(article,'p',`${summary(item)}${item.referenceDate?' · '+item.referenceDate+' 기록':''}`);
   if(item.measurementType==='assessment')add(article,'p',item.protocol);else{const list=add(article,'ol','');item.segments.forEach(s=>add(list,'li',formatWorkoutSet({measurementType:item.measurementType==='assessment'?'duration':item.measurementType,loadType:item.loadType,sets:item.segments},s)));}
   if(item.recoveryNote)add(article,'p',item.recoveryNote);[item.reason,item.guide,item.check].filter(usefulNote).forEach(v=>add(article,'p',v));});
  if(lesson.checks.length){add(root,'h2','수업 중·후 확인');const list=add(root,'ul','');lesson.checks.forEach(v=>add(list,'li',v));}
  if(reason.trim()){add(root,'h2','트레이너 조정 이유·수업 메모');add(root,'p',reason);}
  return root;
 }
 return <><header className="lesson-heading" hidden={isGenerating}><h2>다음 수업</h2><button className="lesson-generate" disabled={busy||isGenerating||!online||!contextCurrent} onClick={()=>void generate()}>AI로 수업 제안</button><AnalysisTools kind="lesson" memberId={memberId} contentRef={contentRef} exportContent={exportLesson} online={online} busy={busy||context?.status==='processing'} canRegenerate={contextCurrent&&!!context?.candidates.length} onRegenerate={()=>generate(true)} regenerateMessage="최신 기록으로 다음 수업 제안을 다시 생성할까요? 저장한 계획과 작성 중인 내용은 유지됩니다. AI 이용량이 차감됩니다."/></header>{isGenerating&&<div className="cl-loading-screen" role="status" aria-live="polite"><span className="cl-loading-spinner" aria-hidden="true"/><h3>다음 수업을 구성하고 있어요</h3><p>기존 프로그램·수행 기록·목표를 함께 확인 중</p></div>}<div ref={contentRef} className="connected-lesson lesson-compact" hidden={isGenerating}>
 {loading&&<p role="status" className="cl-muted">근거 확인 중…</p>}
 {(stale||!!plan&&!plan.lesson)&&<div className="cl-update"><span>새 구성 확인 가능</span><button disabled={busy||!contextCurrent} onClick={()=>setPreview(true)}>새 구성과 비교</button></div>}
 {contextCurrent&&context!.status==='error'&&!error&&<div className="cl-update" role="status"><span>AI 제안 생성 실패</span><button disabled={busy||!online} onClick={()=>void generate()}>다시 시도</button></div>}
 {contextCurrent&&context!.draft.source==='ai'&&!preview&&(!view||view.basis!==context!.draft.basis)&&<button className="cl-link" onClick={()=>setPreview(true)}>새 제안 보기</button>}
 {error&&<div className="file-error" role="alert">{error}<button disabled={busy||!online} onClick={()=>{cache.current.delete(key);setRefresh(x=>x+1);}}>근거 다시 확인</button></div>}
 {preview&&contextCurrent&&<section className="cl-preview"><div className="cl-section-title"><h3>새 제안 <small>{context!.draft.items.length}</small></h3><button className="cl-link" onClick={()=>setPreview(false)}>닫기</button></div><LessonBasis lesson={context!.draft} context={context} onOriginal={onOriginal} onEvidence={onEvidence}/>{!!context!.draft.before?.length&&<section className="cl-before"><h3>수업 전 고려</h3><ul>{context!.draft.before.map((v,n)=><li key={n}>{v}</li>)}</ul></section>}
 {context!.draft.items.map((item,n)=><article className="cl-program-row" key={item.id}><header><span className="cl-index">{String(n+1).padStart(2,'0')}</span><h3>{item.exerciseName}</h3><small>{summary(item)}</small><span className="cl-action">{actionNames[item.action]}</span></header><ProgramValues item={item}/>{usefulNote(item.reason)&&<details className="cl-row-reason"><summary>선택 이유</summary><p>{item.reason}</p>{usefulNote(item.guide)&&<p>{item.guide}</p>}</details>}</article>)}
 {!!context!.draft.checks.length&&<section className="cl-checks"><h3>수업 중·후 확인</h3><ul>{context!.draft.checks.map((v,n)=><li key={n}>{v}</li>)}</ul></section>}
 {dirty&&<p className="cl-muted">새 제안 적용 시 작성 중인 구성 대체</p>}<div className="cl-actions"><button onClick={()=>setPreview(false)}>닫기</button><button className="primary" disabled={busy||!context!.draft.items.length} onClick={apply}>새 구성 적용</button></div></section>}
 {!preview&&!view&&plan&&<div className="cl-legacy">{plan.program.map((r,i)=><article key={i}><strong>{r.exerciseName}</strong><span>{r.sets}세트 · {r.reps}</span></article>)}</div>}
 {!preview&&view&&<><div className="cl-origin">{dirty?'작성 중인 계획':plan?'저장한 수업 계획':view.source==='ai'?'AI 제안':`최근 수업 기반 초안${view.programDates?.[0]?' · '+view.programDates[0].slice(5):''}`}</div><LessonBasis lesson={view} context={context} onOriginal={onOriginal} onEvidence={onEvidence}/>{view.source==='ai'&&!!view.before?.length&&<section className="cl-before"><h3>수업 전 고려</h3><ul>{view.before.map((item,n)=><li key={n}>{item}</li>)}</ul></section>}
 <div className="cl-section-title"><h3>운동 프로그램 <small>{view.items.length}</small></h3></div>
 {view.items.map((item,index)=><article className="cl-program-row" key={item.id}><header><span className="cl-index">{String(index+1).padStart(2,'0')}</span><h3>{item.exerciseName}</h3><small>{summary(item)}</small>{view.source==='ai'&&<span className="cl-action">{actionNames[item.action]}</span>}<button className="cl-row-toggle" disabled={busy} aria-expanded={editing===item.id} aria-label={`${item.exerciseName} 상세·수정`} onClick={()=>setEditing(editing===item.id?'':item.id)}>{editing===item.id?'접기':'상세'}</button></header>
 <ProgramValues item={item}/>
 {editing===item.id&&<div className="cl-row-detail">{view.source==='ai'&&item.goal&&<p className="cl-goal">{item.goal}</p>}{usefulNote(item.reason)&&<p>{item.reason}</p>}{item.measurementType==='assessment'&&<><p className="cl-protocol">{item.protocol}</p><div className="cl-fields">{item.assessmentFields.map(f=><span key={f.label}>{f.label} · {f.unit}</span>)}</div><button className="cl-link" onClick={()=>onEvidence({tab:'goal',key:'',label:'평가 기록'})}>평가 결과 기록 ↗</button></>}
 <footer>{item.recordId&&<button onClick={()=>onOriginal(item.recordId)}>{item.referenceDate?.slice(5)} 원본 ↗</button>}{item.evidence.map((link,n)=><button key={n} onClick={()=>onEvidence(link)}>{link.tab==='trend'?'변화 추이':link.label} ↗</button>)}</footer>
 {editing===item.id&&<div className="cl-editor">{item.measurementType!=='assessment'&&<SegmentEditor item={item} disabled={busy} onChange={segments=>editItem(item.id,{segments})}/>}{item.measurementType!=='repetitions'&&item.measurementType!=='assessment'&&<><label>반복 라운드 · 선택<input aria-label={`${item.exerciseName} 반복 라운드`} type="number" min={1} max={1000} disabled={busy} value={item.rounds??''} onChange={e=>editItem(item.id,{rounds:e.target.value===''?null:Number(e.target.value)})}/></label><label>회복·휴식 조건<input disabled={busy} maxLength={300} value={item.recoveryNote??''} onChange={e=>editItem(item.id,{recoveryNote:e.target.value})}/></label></>}<label>조정 방향<textarea disabled={busy} maxLength={300} rows={2} value={usefulNote(item.guide)?item.guide:''} onChange={e=>editItem(item.id,{guide:e.target.value})}/></label><label>수업에서 확인할 내용<input disabled={busy} maxLength={300} value={item.check} onChange={e=>editItem(item.id,{check:e.target.value})}/></label><button disabled={busy} onClick={()=>{setDraft(d=>d?{...d,items:d.items.filter(i=>i.id!==item.id)}:d);setDirty(true);}}>구성에서 제외</button></div>}
 </div>}
 </article>)}
 {available.length>0&&<div className="cl-add"><WorkoutSelect label="기록에서 운동·평가 추가" value={addition?.id??''} disabled={busy||stale||!contextCurrent||view.items.length>=20} options={available.map(c=>({value:c.id,label:`${c.exerciseName} · ${c.referenceDate?c.referenceDate.slice(5):'평가'}`}))} onChange={setAdding}/><button disabled={busy||stale||!contextCurrent||view.items.length>=20} onClick={()=>{if(addition){setDraft(d=>d?{...d,items:[...d.items,structuredClone(addition)]}:d);setDirty(true);setEditing(addition.id);}}}>운동 추가</button></div>}

 {!!view.checks.length&&<section className="cl-checks"><h3>수업 중·후 확인</h3><ul>{view.checks.map((c,i)=><li key={i}>{c}</li>)}</ul></section>}
 <label className="cl-note">수업 메모<textarea disabled={busy} maxLength={1000} rows={2} value={reason} onChange={e=>{setReason(e.target.value);setDirty(true);}} placeholder="오늘 상태와 조정 이유"/></label>
 {changed&&<p role="alert">다른 화면에서 계획 변경 · 작성 내용 유지</p>}
 <div className="cl-actions">{dirty&&<button disabled={busy} onClick={()=>{setDraft(plan?.lesson??(plan?null:context?.draft??null));setReason(plan?.reason??'');setDirty(false);setEditing('');saveRevision.current=plan?.revision??0;setMessage('변경 취소');}}>변경 취소</button>}<span>{dirty?'저장 전 변경':plan?'저장됨':''}</span><button disabled={busy||!online||!contextCurrent||stale||changed||!view.items.length||!!plan&&!dirty} className="primary" onClick={()=>void save()}>{busy?'저장 중…':'수업 계획 저장'}</button></div></>}
 {!view&&!plan&&!loading&&!error&&<p className="cl-muted">연결할 기록·목표 확인 필요 <button onClick={onGoal}>목표 확인</button></p>}{message&&<p role="status">{message}</p>}
 </div></>;
}
function usefulNote(value:string){return !!value&&!['선택 기간의 최근 수행 기록','수업 전 컨디션·수행 조건 확인'].includes(value);}
function LessonBasis({lesson,context,onOriginal,onEvidence}:{lesson:LessonDraft;context:LessonContext|null;onOriginal:(id:string)=>void;onEvidence:(link:LessonItem['evidence'][number])=>void}){
 if(lesson.source!=='ai'||!lesson.programSummary)return null;
 return <section className="cl-basis-top"><h3>구성 근거</h3><p>{lesson.programSummary}</p>{context?.evidenceKey===lesson.evidenceKey&&context.decision?.reason&&<p className="cl-basis-trainer">트레이너 판단 · {context.decision.reason}</p>}<div>{lesson.programDates?.map(date=>{const id=context?.history?.sessions.find(session=>session.date===date)?.blocks[0]?.exercises[0]?.recordId;return id?<button key={date} className="cl-link" onClick={()=>onOriginal(id)}>{date.slice(5)} 원본 ↗</button>:null;})}<button className="cl-link" onClick={()=>onEvidence({tab:'goal',key:'',label:'목표 평가'})}>목표 평가 ↗</button></div></section>;
}
function ProgramValues({item}:{item:LessonItem}){
 if(item.measurementType==='assessment')return <p className="cl-values-protocol">{item.protocol}</p>;
 const workout={measurementType:item.measurementType,loadType:item.loadType,sets:item.segments};
 if(repeatedWorkoutPattern(workout))return <span className="cl-program-pattern"><IntervalPattern workout={workout}/></span>;
 return <ol className="cl-program-values" aria-label={`${item.exerciseName} 세트·구간 수치`}>{item.segments.map((s,n)=><li key={n}><small>{n+1}</small><span>{formatWorkoutSet(workout,s)}</span></li>)}</ol>;
}

function SegmentEditor({item,disabled,onChange}:{item:LessonItem;disabled:boolean;onChange:(s:WorkoutSet[])=>void}){
 const fields=(s:WorkoutSet):[keyof WorkoutSet,string][]=>item.measurementType==='repetitions'?[...(item.loadType==='weighted'?[['kg','중량 kg']] as [keyof WorkoutSet,string][]:[]),...(s.leftReps!==undefined?[['leftReps','L 횟수'],['rightReps','R 횟수']] as [keyof WorkoutSet,string][]:[['reps','횟수']] as [keyof WorkoutSet,string][])]:item.measurementType==='incline_speed_time'?[['inclinePercent','경사 %'],['speedKph','속도 km/h'],['durationSeconds','시간 초']]:item.measurementType==='distance_time'?[['distanceMeters','거리 m'],['durationSeconds','시간 초']]:item.measurementType==='distance'?[['distanceMeters','거리 m']]:[['durationSeconds','시간 초']];
 function change(n:number,k:keyof WorkoutSet,value:string){const next=item.segments.map((s,i)=>{if(i!==n)return s;const v={...s,[k]:value===''?null:Number(value)};if(k==='leftReps'||k==='rightReps')v.reps=(v.leftReps??0)+(v.rightReps??0);return v;});onChange(next);}
 return <div>{item.segments.map((s,n)=><div className="cl-segment-inputs" key={n}><span>{n+1}</span>{fields(s).map(([k,label])=><label key={k}>{label}<input aria-label={`${item.exerciseName} ${n+1} ${label}`} disabled={disabled} type="number" step={k==='reps'||k==='leftReps'||k==='rightReps'?'1':'any'} value={s[k]??''} onChange={e=>change(n,k,e.target.value)}/></label>)}<button disabled={disabled||item.segments.length===1} onClick={()=>onChange(item.segments.filter((_,i)=>i!==n))}>삭제</button></div>)}<button disabled={disabled||item.segments.length>=8} onClick={()=>onChange([...item.segments,{...item.segments.at(-1)!}])}>{item.measurementType==='repetitions'?'세트':'구간'} 추가</button></div>;
}
