"use client";
import {useEffect,useState} from 'react';
import {AiReanalysisButton} from './ai-reanalysis-button';
import type {ChangeEvidence} from './change-evidence-card';
export type GuidanceSource={id:string;title:string;url:string;type:string};
export type GoalLens={id:string;label:string;status:'recorded'|'check'|'unknown';observation:string;recordIds:string[];interpretation:string;question:string;references:GuidanceSource[]};
export type GoalReview={summary:string;reason:string;nextStep:string;evidenceIds:string[];references:GuidanceSource[];lenses?:GoalLens[]};
export type Direction={id:string;goalAspect?:string|null;scopeObservation?:string;kind:'keep'|'adjust'|'check'|'measure';text:string;reason?:string;check?:string;evidenceIds:string[]};
const aspects:Record<string,string>={muscles:'큰 근육군 참여',aerobic:'유산소 구성',resistance:'저항운동 성격',core:'코어의 역할',placement:'배치·회복',outcomes:'목표 변화 확인'};
const kinds={keep:'유지',adjust:'조정',check:'확인',measure:'재측정'};
const statuses={recorded:'기록 확인',check:'추가 확인',unknown:'정보 없음'};
export function DirectionReview({goal,secondary,window,review,directions,evidence,chosen,onToggle,onEdit,drafts,trainerContext,onSaveContext,onAnalyze,onGoal,onOriginal,onAsk,onPlan,onBack,onDirty,canAnalyze}:{goal:string;secondary?:string;window?:{from:string;to:string}|null;review?:GoalReview|null;directions:Direction[];evidence:ChangeEvidence[];chosen:Record<string,string>;drafts:Record<string,string>;onToggle:(id:string,selected:boolean)=>void;onEdit:(id:string,text:string)=>void;trainerContext:{text:string;revision:number};onSaveContext:(text:string,revision:number)=>Promise<void>;onAnalyze:()=>void;onGoal:()=>void;onOriginal:(id:string)=>void;onAsk?:(question:string,id:string)=>void;onPlan:()=>void;onBack:()=>void;onDirty?:(dirty:boolean)=>void;canAnalyze:boolean}){
 const [note,setNote]=useState(trainerContext.text),[saving,setSaving]=useState(false),[error,setError]=useState(''),[saved,setSaved]=useState(false),[noteOpen,setNoteOpen]=useState(false);
 const dirty=note!==trainerContext.text;
 useEffect(()=>{setNote(trainerContext.text);},[trainerContext.text,trainerContext.revision]);
 useEffect(()=>{onDirty?.(dirty);return()=>onDirty?.(false);},[dirty,onDirty]);
 const lenses=review?.lenses??[],questions=lenses.filter(l=>l.question);
 async function save(){if(saving)return;setSaving(true);setError('');try{await onSaveContext(note,trainerContext.revision);setSaved(true);}catch(e){setError(e instanceof Error?e.message:'저장하지 못했어요. 다시 시도해주세요.');}finally{setSaving(false);}}
 function addQuestion(lens:GoalLens){setNoteOpen(true);setSaved(false);const line=`[${lens.label}] ${lens.question}\n답변: `;setNote(value=>(value+(value?'\n\n':'')+line).slice(0,2000));}
 return <div className="goal-direction">
  <header className="goal-direction-header"><div><h2>목표를 기준으로 본 다음 수업</h2><button className="goal-context-link" onClick={onGoal}>{goal||'회원 목표 설정'}{secondary?` · ${secondary}`:''}</button></div><AiReanalysisButton disabled={!canAnalyze||saving||dirty} onClick={onAnalyze} title={dirty?'지도 맥락을 저장한 후 재분석해주세요.':'최신 기록과 지도 맥락으로 재분석합니다. AI 이용량이 사용됩니다.'}/></header>
  {review?<section className="goal-verdict" aria-label="목표에 대한 종합 판단"><p className="goal-verdict-summary">{review.summary}</p><p>{review.reason}</p><p className="goal-priority"><strong>우선 방향</strong> {review.nextStep}</p></section>:<p className="direction-context">{saved?'지도 맥락을 저장했습니다. AI 재분석을 누르면 새 판단에 반영됩니다.':'AI 분석을 실행하면 회원 목표와 기록을 연결한 방향을 확인할 수 있습니다.'}</p>}
  {lenses.length>0&&<section className="goal-checks" aria-label="목표 기준 운동 구성 점검"><div className="goal-section-heading"><h3>운동 구성 점검</h3>{window&&<small>{window.from} — {window.to} · 최근 기록 기준 28일</small>}</div><p className="goal-section-note">기록 확인은 적절성 판정이 아닙니다. 각 항목을 펼쳐 목표와 연결한 판단을 확인하세요.</p>{lenses.map(lens=><details className="goal-check-row" key={lens.id}><summary><span>{lens.label}</span><span className={`goal-status goal-status-${lens.status}`}>{statuses[lens.status]}</span><span className="goal-observation">{lens.observation}</span></summary><div className="goal-check-detail"><strong>목표와 연결한 판단</strong><p>{lens.interpretation}</p>{lens.recordIds.length>0&&<button className="goal-context-link" onClick={()=>onOriginal(lens.recordIds[0])}>연결된 운동 기록 보기 →</button>}<Sources sources={lens.references}/></div></details>)}</section>}
  {questions.length>0&&<section className="goal-questions" aria-label="다음 수업 전 확인"><h3>다음 수업 전 확인</h3>{questions.map(lens=><div className="goal-question" key={lens.id}><div><small>{lens.label}</small><p>{lens.question}</p></div><button onClick={()=>addQuestion(lens)} disabled={saving}>답변 적기</button></div>)}</section>}
  <details className="goal-coach-context" open={noteOpen} onToggle={e=>setNoteOpen(e.currentTarget.open)}><summary>트레이너의 지도 맥락 {trainerContext.text?'· 저장됨':''}</summary><p>확인한 답변이나 AI 판단과 다르게 보는 이유를 남겨주세요. 다음 재분석과 수업 계획에 반영됩니다.</p><label htmlFor="goal-coach-note">지도 의도·확인한 내용</label><textarea id="goal-coach-note" maxLength={2000} value={note} disabled={saving} placeholder="예: 10월 9일 확인 — 저반복은 의도한 근력 훈련입니다. 개인 유산소는 주 2회 진행 중입니다. 적용 기간과 확인 날짜를 함께 적어주세요." onChange={e=>{setNote(e.target.value);setSaved(false);}}/><div className="goal-context-actions"><small>{note.length}/2,000자</small><button disabled={!dirty||saving} onClick={()=>void save()}>{saving?'저장 중…':'지도 맥락 저장'}</button></div>{error&&<p role="alert">{error}</p>}{saved&&<p role="status">저장했습니다. 상단의 AI 재분석으로 새 판단을 확인하세요.</p>}</details>
  {directions.length>0&&<section aria-label="다음 수업에 반영할 제안"><h3>다음 수업에 반영할 제안</h3><p className="goal-section-note">목표 우선순위에 따라 정리했습니다. 필요한 내용을 선택하고 수정하세요.</p>{directions.map((d,index)=><article className="journey-card direction-choice goal-action-card" key={d.id}><div className="direction-suggestion-label"><small>{goal?`${goal} · `:''}{aspects[d.goalAspect??'']??'수행 기록'}</small><small>{kinds[d.kind]}</small></div><label className="goal-action-title"><input type="checkbox" disabled={saving} checked={Object.hasOwn(chosen,d.id)} onChange={e=>onToggle(d.id,e.target.checked)}/><strong>{chosen[d.id]??drafts[d.id]??d.text}</strong></label>{d.reason&&<p>{d.reason}</p>}{d.check&&<p className="direction-check"><strong>실행·확인 조건</strong>{d.check}</p>}<details><summary>지도 내용 수정·근거 기록</summary>{d.scopeObservation&&<p>{d.scopeObservation}</p>}<textarea aria-label={`지도 내용 ${index+1} 수정`} maxLength={400} disabled={saving||!Object.hasOwn(chosen,d.id)} value={chosen[d.id]??drafts[d.id]??d.text} onChange={e=>onEdit(d.id,e.target.value)}/>{d.evidenceIds.map(id=>{const row=evidence.find(e=>e.id===id);return row?<p key={id}>{row.name} · {row.observation}</p>:null;})}</details></article>)}</section>}
  {review&&<details className="goal-sources"><summary>종합 판단에 참고한 근거</summary><Sources sources={review.references}/></details>}
  {onAsk&&/다이어트|체지방|감량|체중.*관리/.test(goal)&&<div className="goal-consult"><span>운동 기록 밖의 상담</span><button onClick={()=>onAsk(`회원의 등록 목표는 ${JSON.stringify(goal)}입니다. 이 목표에 맞는 식단·영양 상담을 이어가고 싶어요. 운동 기록만으로 식단이나 섭취량을 추정하지 말고, 식사 패턴·선호·알레르기 등 필요한 정보를 먼저 확인해주세요.`,'')}>식단·영양 상담을 AI 도우미에서 이어가기 →</button></div>}
  <div className="journey-actions"><button onClick={onBack}>← 회원 변화</button><button className="primary" disabled={dirty||saving||!review||!Object.keys(chosen).length||Object.values(chosen).some(v=>!v.trim())} onClick={onPlan}>선택한 {Object.keys(chosen).length}개로 수업 계획 →</button></div>
 </div>;
}
function Sources({sources}:{sources:GuidanceSource[]}){return sources.length?<ul className="goal-source-list">{sources.map(source=><li key={source.id}><span>{source.type}</span> <a href={source.url} target="_blank" rel="noreferrer">{source.title} ↗</a></li>)}</ul>:<p className="goal-section-note">개인 기록을 바탕으로 한 관찰입니다.</p>;}
