"use client";
import {useEffect,useState} from 'react';
import {AiReanalysisButton} from './ai-reanalysis-button';
import type {ChangeEvidence} from './change-evidence-card';
import {decisionChoiceLabels,type CoachingDecision} from '../lib/server-ai';
export type GuidanceSource={id:string;title:string;url:string;type:string};
export type GoalLens={id:string;label:string;status:'recorded'|'check'|'unknown';observation:string;recordIds:string[];interpretation:string;question:string;references:GuidanceSource[]};
export type GoalReview={summary:string;reason:string;nextStep:string;evidenceIds:string[];references:GuidanceSource[];lenses?:GoalLens[]};
export type Direction={id:string;goalAspect?:string|null;scopeObservation?:string;kind:'keep'|'adjust'|'check'|'measure';text:string;reason?:string;check?:string;evidenceIds:string[]};
export type DiscussTarget={kind:'lens'|'direction';id:string;label:string;fingerprint:string};
const aspects:Record<string,string>={muscles:'큰 근육군 참여',aerobic:'유산소 구성',resistance:'저항운동 성격',core:'코어의 역할',placement:'배치·회복',outcomes:'목표 변화 확인'};
const kinds={keep:'유지',adjust:'조정',check:'확인',measure:'재측정'};
const statuses={recorded:'기록 확인',check:'추가 확인',unknown:'정보 없음'};
// Which of the member's goals a lens mainly serves. Falls back to the primary goal.
const aspectGoals:Record<string,string[]>={muscles:['근비대','근력','다이어트(체지방 감소)'],aerobic:['심폐·체력','다이어트(체지방 감소)'],resistance:['근력','근비대'],core:['심폐·체력','좌우 균형 발전'],placement:['근력','심폐·체력'],outcomes:['다이어트(체지방 감소)','근비대']};
export function aspectGoal(aspect:string|null|undefined,goals:string[]){return (aspectGoals[aspect??'']??[]).find(g=>goals.includes(g))??goals[0]??'';}
export type AppliedDecision={id:string;version:string};
type DecisionState='shown'|'applied'|'moved'|'older';
/** shown: overlays the same card it was decided on. applied: the current synthesis was given it (id + revision).
 *  moved: same records, but the analysis was re-run and that card is gone. older: decided on other records. */
export function decisionState(d:CoachingDecision,inputKey:string,applied:AppliedDecision[],fingerprints:Record<string,string>):DecisionState{
 if(applied.some(a=>a.id===d.id&&a.version===d.version))return 'applied';
 if(d.inputKey!==inputKey)return 'older';
 return fingerprints[`${d.target.kind}:${d.target.id}`]===d.fingerprint?'shown':'moved';
}
export function activeDecisions(decisions:CoachingDecision[],inputKey:string,applied:AppliedDecision[],fingerprints:Record<string,string>){return decisions.filter(d=>decisionState(d,inputKey,applied,fingerprints)==='shown');}
const stateLabels:Record<DecisionState,string>={shown:'이번 분석에 표시 중',applied:'종합 판단에 반영됨',moved:'분석이 다시 생성되어 해당 카드가 바뀜 · 재분석 때 참고',older:'이전 기록 기준 결정 · 재분석 때 참고'};
export function DirectionReview({goal,secondary,window,review,directions,evidence,chosen,onToggle,onEdit,drafts,trainerContext,onSaveContext,onAnalyze,onGoal,onOriginal,onAsk,onDiscuss,onRemoveDecision,decisions=[],inputKey='',appliedDecisions=[],targetFingerprints={},onPlan,onBack,onDirty,canAnalyze}:{goal:string;secondary?:string;window?:{from:string;to:string}|null;review?:GoalReview|null;directions:Direction[];evidence:ChangeEvidence[];chosen:Record<string,string>;drafts:Record<string,string>;onToggle:(id:string,selected:boolean)=>void;onEdit:(id:string,text:string)=>void;trainerContext:{text:string;revision:number};onSaveContext:(text:string,revision:number)=>Promise<void>;onAnalyze:()=>void;onGoal:()=>void;onOriginal:(id:string)=>void;onAsk?:(question:string,id:string)=>void;onDiscuss?:(target:DiscussTarget,question:string)=>void;onRemoveDecision?:(id:string,removePrinciple:boolean)=>Promise<void>;decisions?:CoachingDecision[];inputKey?:string;appliedDecisions?:AppliedDecision[];targetFingerprints?:Record<string,string>;onPlan:()=>void;onBack:()=>void;onDirty?:(dirty:boolean)=>void;canAnalyze:boolean}){
 const [note,setNote]=useState(trainerContext.text),[saving,setSaving]=useState(false),[error,setError]=useState(''),[saved,setSaved]=useState(false),[noteOpen,setNoteOpen]=useState(false),[removing,setRemoving]=useState('');
 const dirty=note!==trainerContext.text;
 useEffect(()=>{setNote(trainerContext.text);},[trainerContext.text,trainerContext.revision]);
 useEffect(()=>{onDirty?.(dirty);return()=>onDirty?.(false);},[dirty,onDirty]);
 const lenses=review?.lenses??[],questions=lenses.filter(l=>l.question);
 const goals=[goal,...(secondary?secondary.split(' · '):[])].filter(Boolean);
 const active=activeDecisions(decisions,inputKey,appliedDecisions,targetFingerprints),decisionFor=(kind:string,id:string)=>active.find(d=>d.target.kind===kind&&d.target.id===id);
 // Each discussion carries the item's content fingerprint, so a re-run that replaces the card cannot capture it.
 const canDiscuss=(kind:'lens'|'direction',id:string)=>!!onDiscuss&&!!targetFingerprints[`${kind}:${id}`];
 const lensTarget=(l:GoalLens):DiscussTarget=>({kind:'lens',id:l.id,label:l.label,fingerprint:targetFingerprints['lens:'+l.id]??''});
 const directionTarget=(d:Direction,text:string):DiscussTarget=>({kind:'direction',id:d.id,label:`${aspects[d.goalAspect??'']??'수행 기록'} · ${text.slice(0,40)}`,fingerprint:targetFingerprints['direction:'+d.id]??''});
 async function save(){if(saving)return;setSaving(true);setError('');try{await onSaveContext(note,trainerContext.revision);setSaved(true);}catch(e){setError(e instanceof Error?e.message:'저장하지 못했어요. 다시 시도해주세요.');}finally{setSaving(false);}}
 function addQuestion(lens:GoalLens){setNoteOpen(true);setSaved(false);const line=`[${lens.label}] ${lens.question}\n답변: `;setNote(value=>(value+(value?'\n\n':'')+line).slice(0,2000));}
 async function remove(id:string){if(!onRemoveDecision||removing)return;const d=decisions.find(x=>x.id===id);
  // A principle saved for other members is a separate choice; ask instead of deleting it silently.
  const removePrinciple=!!d?.remember&&globalThis.confirm('이 결정과 함께 저장한 "다른 회원에도 참고할 기준"도 지울까요?\n확인: 함께 지움 · 취소: 기준은 유지하고 결정만 되돌림');
  setRemoving(id);setError('');try{await onRemoveDecision(id,removePrinciple);}catch(e){setError(e instanceof Error?e.message:'되돌리지 못했어요. 다시 시도해주세요.');}finally{setRemoving('');}}
 const decisionNote=(d:CoachingDecision)=><div className="goal-decision-note"><span><strong>논의 후 {decisionChoiceLabels[d.choice]}</strong> {d.reason}</span>{onRemoveDecision&&<button disabled={!!removing} onClick={()=>void remove(d.id)}>{removing===d.id?'되돌리는 중…':'되돌리기'}</button>}</div>;
 return <div className="goal-direction">
  <header className="goal-direction-header"><div><h2>목표를 기준으로 본 다음 수업</h2><button className="goal-context-link" onClick={onGoal}>{goal||'회원 목표 설정'}{secondary?` · ${secondary}`:''}</button></div><AiReanalysisButton disabled={!canAnalyze||saving||dirty} onClick={onAnalyze} title={dirty?'지도 맥락을 저장한 후 재분석해주세요.':'최신 기록, 지도 맥락, 논의로 정한 결정으로 재분석합니다. AI 이용량이 사용됩니다.'}/></header>
  {review?<section className="goal-verdict" aria-label="목표에 대한 종합 판단"><p className="goal-verdict-summary">{review.summary}</p><p>{review.reason}</p><p className="goal-priority"><strong>우선 방향</strong> {review.nextStep}</p></section>:<p className="direction-context">{saved?'지도 맥락을 저장했습니다. AI 재분석을 누르면 새 판단에 반영됩니다.':'AI 분석을 실행하면 회원 목표와 기록을 연결한 방향을 확인할 수 있습니다.'}</p>}
  {active.length>0&&<div className="goal-decisions-pending" role="status"><span>논의로 정한 결정 {active.length}개를 아래 항목에 표시했어요. 위의 종합 판단에는 아직 반영 전이에요.</span><button disabled={!canAnalyze||saving||dirty} onClick={onAnalyze}>결정까지 다시 종합</button></div>}
  {lenses.length>0&&<section className="goal-checks" aria-label="목표 기준 운동 구성 점검"><div className="goal-section-heading"><h3>운동 구성 점검</h3>{window&&<small>{window.from} — {window.to} · 최근 기록 기준 28일</small>}</div><p className="goal-section-note">기록 확인은 적절성 판정이 아닙니다. 각 항목을 펼쳐 목표와 연결한 판단을 확인하고, 다르게 보면 논의하세요.</p>{lenses.map(lens=>{const d=decisionFor('lens',lens.id);return <details className="goal-check-row" key={lens.id}><summary><span>{lens.label}</span><span className="goal-status-group">{d&&<span className="goal-status goal-status-decided">결정: {decisionChoiceLabels[d.choice]}</span>}<span className={`goal-status goal-status-${lens.status}`}>{statuses[lens.status]}</span></span><span className="goal-observation">{lens.observation}</span></summary><div className="goal-check-detail"><strong>목표와 연결한 판단</strong><p>{lens.interpretation}</p>{d&&decisionNote(d)}<div className="goal-check-actions">{canDiscuss('lens',lens.id)&&<button className="goal-discuss" onClick={()=>onDiscuss!(lensTarget(lens),'')}>이 판단 논의하기</button>}{lens.recordIds.length>0&&<button className="goal-context-link" onClick={()=>onOriginal(lens.recordIds[0])}>연결된 운동 기록 보기 →</button>}</div><Sources sources={lens.references}/></div></details>;})}</section>}
  {questions.length>0&&<section className="goal-questions" aria-label="다음 수업 전 확인"><h3>다음 수업 전 확인</h3>{questions.map(lens=><div className="goal-question" key={lens.id}><div><small>{lens.label}</small><p>{lens.question}</p></div>{canDiscuss('lens',lens.id)?<button onClick={()=>onDiscuss!(lensTarget(lens),`${lens.question}\n→ `)}>논의하기</button>:<button onClick={()=>addQuestion(lens)} disabled={saving}>답변 적기</button>}</div>)}</section>}
  {directions.length>0&&<section aria-label="다음 수업에 반영할 제안"><h3>다음 수업에 반영할 제안</h3><p className="goal-section-note">목표 우선순위에 따라 정리했습니다. 필요한 내용을 선택하고 수정하거나, 다르게 보면 논의하세요.</p>{directions.map((raw,index)=>{const decision=decisionFor('direction',raw.id),d=decision?.patch?{...raw,text:decision.patch.text,reason:decision.patch.reason||raw.reason,check:decision.patch.check||raw.check}:raw,label=aspectGoal(d.goalAspect,goals);return <article className={'journey-card direction-choice goal-action-card'+(decision?' goal-action-decided':'')} key={d.id}><div className="direction-suggestion-label"><small>{label?`${label} · `:''}{aspects[d.goalAspect??'']??'수행 기록'}</small><small>{decision?.patch?'논의 후 수정됨':kinds[d.kind]}</small></div><label className="goal-action-title"><input type="checkbox" disabled={saving} checked={Object.hasOwn(chosen,d.id)} onChange={e=>onToggle(d.id,e.target.checked)}/><strong>{chosen[d.id]??drafts[d.id]??d.text}</strong></label>{d.reason&&<p>{d.reason}</p>}{d.check&&<p className="direction-check"><strong>실행·확인 조건</strong>{d.check}</p>}{decision&&decisionNote(decision)}{canDiscuss('direction',raw.id)&&<button className="goal-discuss" onClick={()=>onDiscuss!(directionTarget(raw,d.text),'')}>이 제안 논의하기</button>}<details><summary>지도 내용 수정·근거 기록</summary>{d.scopeObservation&&<p>{d.scopeObservation}</p>}<textarea aria-label={`지도 내용 ${index+1} 수정`} maxLength={400} disabled={saving||!Object.hasOwn(chosen,d.id)} value={chosen[d.id]??drafts[d.id]??d.text} onChange={e=>onEdit(d.id,e.target.value)}/>{d.evidenceIds.map(id=>{const row=evidence.find(e=>e.id===id);return row?<p key={id}>{row.name} · {row.observation}</p>:null;})}</details></article>;})}</section>}
  <details className="goal-coach-context" open={noteOpen} onToggle={e=>setNoteOpen(e.currentTarget.open)}><summary>트레이너의 결정과 지도 메모 {decisions.length?`· 결정 ${decisions.length}개`:''}{trainerContext.text?' · 메모 저장됨':''}</summary>
   {decisions.length>0&&<><h4>논의로 정한 결정</h4><ul className="goal-decision-list">{decisions.map(d=>{const state=decisionState(d,inputKey,appliedDecisions,targetFingerprints),shown=state==='shown';return <li key={d.id}><span><strong>{d.target.label}</strong> · {decisionChoiceLabels[d.choice]} — {d.reason}</span><small>{stateLabels[state]}{d.remember?' · 다른 회원 참고 기준 저장됨':''}</small>{onRemoveDecision&&<button disabled={!!removing} onClick={()=>void remove(d.id)}>되돌리기</button>}</li>;})}</ul></>}
   <p>결정으로 정리하기 어려운 배경(회원 사정, 적용 기간 등)을 남겨주세요. 다음 재분석과 수업 계획에 반영됩니다. 질문 문장은 붙여넣지 않아도 돼요. 확인할 내용은 논의하기로 이어가세요.</p><label htmlFor="goal-coach-note">지도 메모</label><textarea id="goal-coach-note" maxLength={2000} value={note} disabled={saving} placeholder="예: 10월 9일 확인 — 저반복은 의도한 근력 훈련입니다. 개인 유산소는 주 2회 진행 중입니다. 적용 기간과 확인 날짜를 함께 적어주세요." onChange={e=>{setNote(e.target.value);setSaved(false);}}/><div className="goal-context-actions"><small>{note.length}/2,000자</small><button disabled={!dirty||saving} onClick={()=>void save()}>{saving?'저장 중…':'지도 메모 저장'}</button></div>{error&&<p role="alert">{error}</p>}{saved&&<p role="status">저장했습니다. 상단의 AI 재분석으로 새 판단을 확인하세요.</p>}</details>
  {review&&<details className="goal-sources"><summary>종합 판단에 참고한 근거</summary><Sources sources={review.references}/></details>}
  {onAsk&&/다이어트|체지방|감량|체중.*관리/.test(goal)&&<div className="goal-consult"><span>운동 기록 밖의 상담</span><button onClick={()=>onAsk(`회원의 등록 목표는 ${JSON.stringify(goal)}입니다. 이 목표에 맞는 식단·영양 상담을 이어가고 싶어요. 운동 기록만으로 식단이나 섭취량을 추정하지 말고, 식사 패턴·선호·알레르기 등 필요한 정보를 먼저 확인해주세요.`,'')}>식단·영양 상담을 AI 도우미에서 이어가기 →</button></div>}
  <div className="journey-actions"><button onClick={onBack}>← 회원 변화</button><button className="primary" disabled={dirty||saving||!review||!Object.keys(chosen).length||Object.values(chosen).some(v=>!v.trim())} onClick={onPlan}>선택한 {Object.keys(chosen).length}개로 수업 계획 →</button></div>
 </div>;
}
function Sources({sources}:{sources:GuidanceSource[]}){return sources.length?<ul className="goal-source-list">{sources.map(source=><li key={source.id}><span>{source.type}</span> <a href={source.url} target="_blank" rel="noreferrer">{source.title} ↗</a></li>)}</ul>:<p className="goal-section-note">개인 기록을 바탕으로 한 관찰입니다.</p>;}
