"use client";
import {useEffect,useRef,useState} from 'react';
import {callAi,aiMessage} from '../lib/server-ai';
import {validateGoalProposal,type GoalProposal} from '../lib/goal-coaching';
import {appendFollowupAnswer,followupPlaceholder} from '../lib/assessment-followup';
import {GoalFieldHelp} from './goal-field-help';
import type {TrainingGoal} from '../lib/training-goals';
export function GoalCoach({memberId,value,onApply,onBusy,online}:{memberId:string;value:TrainingGoal;onApply:(proposal:GoalProposal,id:string,description:string,answers:string)=>void;onBusy:(v:boolean)=>void;online:boolean}){
 const [description,setDescription]=useState(''),[answers,setAnswers]=useState(''),[submittedAnswers,setSubmittedAnswers]=useState(''),[result,setResult]=useState<{proposalId:string;proposal:GoalProposal}|null>(null),[busy,setBusy]=useState(false),[error,setError]=useState(''),[principles,setPrinciples]=useState<{id:string;text:string}[]>([]);const pending=useRef(false),alive=useRef(true);
 useEffect(()=>{alive.current=true;void callAi({action:'listTrainingPrinciples',memberId}).then(v=>{if(alive.current)setPrinciples((v as {principles:{id:string;text:string}[]}).principles);}).catch(()=>{});return()=>{alive.current=false;};},[memberId]);
 async function organize(){if(pending.current||!online)return;pending.current=true;setBusy(true);onBusy(true);setError('');try{const submitted=appendFollowupAnswer(submittedAnswers,answers,result?.proposal.questions??[]);const r=await callAi({action:'draftGoal',memberId,description,answers:submitted}) as {proposalId:string;proposal:unknown;principles:{id:string;text:string}[]};const proposal=validateGoalProposal(r.proposal);if(alive.current){setResult({proposalId:r.proposalId,proposal});setPrinciples(r.principles);setSubmittedAnswers(submitted);setAnswers('');}}catch(e){if(alive.current)setError(aiMessage(e));}finally{pending.current=false;if(alive.current){setBusy(false);onBusy(false);}}}
 async function remove(id:string){if(pending.current)return;pending.current=true;setBusy(true);onBusy(true);try{await callAi({action:'removeTrainingPrinciple',memberId,id});setPrinciples(p=>p.filter(x=>x.id!==id));}catch(e){setError(aiMessage(e));}finally{pending.current=false;setBusy(false);onBusy(false);}}
 const input=<><GoalFieldHelp title="AI와 목표 정리" label={<label htmlFor="gc-description">회원의 목표와 평소 평가 방식</label>} description="목적, 현재 가능한 수준, 목표, 평소 쓰는 평가 방법을 자유롭게 작성. AI가 목표와 평가 초안으로 정리하며 최종 적용은 트레이너가 확인." example="예: 체력 향상 목적, 현재 인터벌 3라운드·목표 5라운드. 운동·회복 시간과 기구 설정도 함께 작성"><textarea id="gc-description" rows={4} maxLength={3000} value={description} disabled={busy} onChange={e=>{setDescription(e.target.value);setResult(null);setAnswers('');setSubmittedAnswers('');}} placeholder="예: 기초체력과 근비대가 목적. 마이마운틴은 현재 6라운드, 우선 10라운드 목표. 기울기 20%, 속도 5km/h로 1분 달리기와 기울기 0%, 속도 3km/h로 1분 걷기를 반복."/></GoalFieldHelp><button type="button" className="ta-organize" disabled={!online||busy||!description.trim()} onClick={()=>void organize()}>{busy?'목표·평가 정리 중…':'AI로 목표·평가 정리'}</button></>;
 return <section className="goal-coach" aria-label="AI 목표 설계"><details open={!value.primary&&!result}><summary>AI와 목표 정리</summary>{input}</details>
 {result&&<div className="ta-draft"><small>AI 제안 · 트레이너 확인 전</small><h3>{result.proposal.detail}</h3><p>{[result.proposal.primary,...result.proposal.secondary].join(' · ')}</p>{result.proposal.initialState&&<p>초기 상태 · {result.proposal.initialState}</p>}<div className="gc-alignment">{result.proposal.alignment.map((a,i)=><article key={i}><strong>{a.goal}</strong><p>{a.assessment||'평가 방법 미정'}</p>{a.gap&&<small>추가 확인 · {a.gap}</small>}</article>)}</div>{result.proposal.questions.length>0&&<div className="ta-questions"><h4>확인할 내용</h4><ul>{result.proposal.questions.map(q=><li key={q}>{q}</li>)}</ul><label>목표 추가 답변<textarea rows={2} maxLength={2000} disabled={busy} value={answers} onChange={e=>setAnswers(e.target.value)} placeholder={followupPlaceholder(result.proposal.questions)}/></label><button disabled={!online||busy||!answers.trim()} onClick={()=>void organize()}>답변 반영</button></div>}<button type="button" className="primary" disabled={busy} onClick={()=>onApply(result.proposal,result.proposalId,description,submittedAnswers)}>{value.coaching?.proposalId===result.proposalId?'제안 다시 반영':'목표·평가 초안 반영'}</button></div>}
 {principles.length>0&&<details className="ta-source"><summary>다음 제안에 참고할 내 기준 {principles.length}</summary>{principles.map(p=><div className="gc-principle" key={p.id}><span>{p.text}</span><button disabled={busy} onClick={()=>void remove(p.id)}>참고 해제</button></div>)}</details>}{error&&<p role="alert" className="file-error">{error}</p>}
 </section>;
}
