"use client";
import {useEffect,useState,type FormEvent} from 'react';
import {collection,getFirestore,onSnapshot,orderBy,query,limit} from 'firebase/firestore';
import {getClientAuth} from '../lib/firebase-client';
import {callAi,aiMessage,serverAiEnabled} from '../lib/server-ai';
import type {WorkoutRecord} from '../lib/workout-records';
export type JudgmentCard={id:string;version:string;title:string;status:string;reason:string;missingFields:string[];evidenceIds:string[];follow_up_metric:string;validation_status:string};
export type JudgmentText={cardId:string;version:string;status:string;observation:string;interpretation:string;question:string;action:string;evidenceIds:string[];caseIds:string[]};
export type JudgmentContext={version:string;cards:JudgmentCard[];cases:{id:string;reason:string;action:string;outcomes:{result:string;note:string}[]}[];criteria:Criteria|null};
type Criteria={revision?:number;scope:string;exerciseName:string;equipment:string;loadBasis:string;side:string;setPurpose:string;loadKg:number;targetReps:number;minSessions:number;windowDays:number;planDate:string};
type Decision={id:string;cardId:string;reason:string;action:string;followUpMetric:string;followUpDate:string;snapshot:{card:JudgmentCard};};
const labels:Record<string,string>={candidate:'검토 후보',needs_information:'추가 정보 필요',not_applicable:'현재 적용 안 함',maintain:'유지',adjust:'조정',check:'추가 확인',as_expected:'기대한 변화 관찰',different:'기대와 다른 결과',unclear:'아직 판단 어려움'};
const defaults:Criteria={scope:'general-adult',exerciseName:'',equipment:'',loadBasis:'',side:'',setPurpose:'',loadKg:0,targetReps:0,minSessions:0,windowDays:0,planDate:''};
export function JudgmentReport({memberId,context,judgments,fingerprint,records,online,onEvidence}:{memberId:string;context?:JudgmentContext;judgments?:JudgmentText[];fingerprint:string;records:WorkoutRecord[];online:boolean;onEvidence:(id:string)=>void}){
 const [decisions,setDecisions]=useState<Decision[]>([]),[outcomes,setOutcomes]=useState<{id:string;decisionId:string;result:string;note:string}[]>([]),[error,setError]=useState(''),[active,setActive]=useState('');
 useEffect(()=>{if(!serverAiEnabled)return;const auth=getClientAuth(),uid=auth.currentUser?.uid;if(!uid)return;const db=getFirestore(auth.app),base=collection(db,'trainers',uid,'members',memberId,'judgmentDecisions'),other=collection(db,'trainers',uid,'members',memberId,'judgmentOutcomes');const fail=(e:unknown)=>setError(aiMessage(e));const offs=[onSnapshot(query(base,orderBy('createdAt','desc'),limit(10)),s=>setDecisions(s.docs.map(d=>({id:d.id,...d.data()} as Decision))),fail),onSnapshot(query(other,orderBy('createdAt','desc'),limit(20)),s=>setOutcomes(s.docs.map(d=>({id:d.id,...d.data()} as {id:string;decisionId:string;result:string;note:string}))),fail)];return()=>offs.forEach(f=>f());},[memberId]);
 return <section className="judgment-report" aria-label="판단 근거와 수업 피드백"><div className="section-title"><h2>기록에서 판단으로</h2></div><p className="record-help">비교 조건을 확인한 범위에서 해석해요. 아래 기준은 전문가 검증 전 초안이며, 내 판단과 이후 결과는 이 회원의 다음 분석에 참고됩니다.</p>
 <details className="judgment-criteria"><summary>내 판단 기준 설정 · 비교 조건과 목표</summary><CriteriaForm key={context?.criteria?.revision??0} memberId={memberId} current={context?.criteria??null} records={records} enabled={serverAiEnabled&&online}/></details>
 {!context&&<p>판독된 기록으로 판단 근거를 준비하고 있어요.</p>}
 {context?.cards.map(card=>{const j=judgments?.find(v=>v.cardId===card.id);return <article className="judgment-card" key={card.id}><header><h3>{card.title}</h3><span className="pill">{labels[card.status]}</span></header><p><strong>관찰</strong> {j?.observation||card.reason}</p>{j?.interpretation&&<p><strong>해석</strong> {j.interpretation}</p>}{j?.question&&<p className="judgment-question">{j.question}</p>}{j?.action&&<p><strong>다음 행동</strong> {j.action}</p>}{card.missingFields.length>0&&<p className="record-help">필요한 정보: {card.missingFields.join(' · ')}</p>}<details><summary>적용 기준·원본 근거</summary><p>{card.reason}</p><small>{card.id} · {card.version} · 검증 전 초안</small><div className="ai-evidence">{card.evidenceIds.map(id=><button key={id} onClick={()=>onEvidence(id)}>{records.find(r=>r.id===id)?.date??'원본'} 기록</button>)}</div>{j?.caseIds.map(id=>{const c=context.cases.find(c=>c.id===id);return c?<p key={id}>참고한 내 판단: {c.reason}{c.outcomes.map((o,i)=><small key={i}> · 이후 결과: {labels[o.result]} — {o.note}</small>)}</p>:null;})}</details><button disabled={!online||!serverAiEnabled||!fingerprint} onClick={()=>setActive(active===card.id?'':card.id)}>이 판단에 의견 남기기</button>{active===card.id&&<DecisionForm memberId={memberId} fingerprint={fingerprint} card={card} online={online} onSaved={()=>setActive('')}/>}</article>;})}
 {decisions.length>0&&<div className="judgment-followups"><h3>내 판단과 이후 결과</h3>{decisions.map(d=><details key={d.id}><summary>{labels[d.action]} · {d.reason}</summary><p>다음 확인: {d.followUpDate} · {d.followUpMetric}</p>{outcomes.filter(o=>o.decisionId===d.id).map(o=><p key={o.id}>{labels[o.result]}: {o.note}</p>)}<OutcomeForm memberId={memberId} decision={d} online={online}/></details>)}</div>}{error&&<p role="alert" className="file-error">{error}</p>}
 </section>;
}
function CriteriaForm({memberId,current,records,enabled}:{memberId:string;current:Criteria|null;records:WorkoutRecord[];enabled:boolean}){
 const [v,setV]=useState<Criteria>(current??defaults),[confirmed,setConfirmed]=useState(false),[busy,setBusy]=useState(false),[message,setMessage]=useState('');const names=[...new Set(records.filter(r=>r.loadType==='weighted').map(r=>r.exerciseName))];
 async function submit(e:FormEvent){e.preventDefault();if(busy||!enabled)return;setBusy(true);setMessage('');try{await callAi({action:'judgmentCriteria',memberId,revision:current?.revision??0,input:{...v,conditionsConfirmed:confirmed}});setMessage('판단 기준을 저장했어요. 기존 판독 결과로 리포트를 갱신합니다.');}catch(e){setMessage(aiMessage(e));}finally{setBusy(false);}}
 return <form className="judgment-form" onSubmit={e=>void submit(e)}><fieldset disabled={busy||!enabled}><p>첫 적용 범위는 일반 성인 PT의 중량 운동이에요. 현재 화면에 있는 해당 종목 기록에만 적용합니다.</p><label>비교할 운동<select aria-label="비교할 운동" required value={v.exerciseName} onChange={e=>setV({...v,exerciseName:e.target.value})}><option value="">운동 선택</option>{names.map(n=><option key={n}>{n}</option>)}</select></label>{([['equipment','기구·자세'],['loadBasis','중량 표기 기준 (예: 한 손 무게)'],['side','좌우·양측 기준'],['setPurpose','세트 목적 (예: 본 운동)']] as const).map(([k,label])=><label key={k}>{label}<input required maxLength={100} value={v[k]} onChange={e=>setV({...v,[k]:e.target.value})}/></label>)}<div className="judgment-form-grid">{([['loadKg','목표 측정 중량 (kg)',2000],['targetReps','목표 반복 횟수',1000],['minSessions','정체 검토 최소 수업 횟수',30],['windowDays','관찰 기간 (일)',365]] as const).map(([k,label,max])=><label key={k}>{label}<input required type="number" min={k==='minSessions'?2:k==='loadKg'?0.01:1} max={max} step={k==='loadKg'?'any':1} value={v[k]||''} onChange={e=>setV({...v,[k]:Number(e.target.value)})}/></label>)}</div><label>계획과 대조할 수업 날짜 (선택)<input type="date" value={v.planDate} onChange={e=>setV({...v,planDate:e.target.value})}/></label><p className="record-help">현재 저장된 수업 계획을 기준으로 연결해요. 계획 저장일 다음 날 이후의 실제 기록과 비교합니다.</p><label className="judgment-confirm"><input type="checkbox" required checked={confirmed} onChange={e=>setConfirmed(e.target.checked)}/>일반 성인 PT 범위에서 이 반복수 지표를 목표 점검에 사용하며, 해당 기록의 기구·중량·좌우·세트 목적이 동일함을 확인했어요.</label><button className="primary" disabled={!confirmed}>판단 기준 저장</button></fieldset>{message&&<p role="status">{message}</p>}</form>;
}
function DecisionForm({memberId,fingerprint,card,online,onSaved}:{memberId:string;fingerprint:string;card:JudgmentCard;online:boolean;onSaved:()=>void}){
 const [busy,setBusy]=useState(false),[error,setError]=useState(''),[id]=useState(()=>crypto.randomUUID());
 async function submit(e:FormEvent<HTMLFormElement>){e.preventDefault();if(busy||!online)return;const f=new FormData(e.currentTarget);setBusy(true);try{await callAi({action:'judgmentDecision',memberId,fingerprint,cardId:card.id,requestId:id,...Object.fromEntries(f)});onSaved();}catch(e){setError(aiMessage(e));}finally{setBusy(false);}}
 return <form className="judgment-form" onSubmit={e=>void submit(e)}><fieldset disabled={busy||!online}><label>내 선택<select aria-label="내 선택" name="choice"><option value="check">추가 확인</option><option value="maintain">유지</option><option value="adjust">조정</option></select></label><label>선택한 이유<textarea name="reason" required maxLength={500} rows={2}/></label><label>선택하지 않은 대안 (선택)<input name="alternative" maxLength={500}/></label><label>판단을 바꿀 조건 (선택)<input name="changeCondition" maxLength={500}/></label><label>다음에 확인할 지표<input name="followUpMetric" required maxLength={200} defaultValue={card.follow_up_metric}/></label><label>다음 확인 날짜<input name="followUpDate" type="date" required/></label><button className="primary">내 판단 저장</button></fieldset>{error&&<p role="alert">{error}</p>}</form>;
}
function OutcomeForm({memberId,decision,online}:{memberId:string;decision:Decision;online:boolean}){
 const [busy,setBusy]=useState(false),[message,setMessage]=useState(''),[id,setId]=useState(()=>crypto.randomUUID());
 async function submit(e:FormEvent<HTMLFormElement>){e.preventDefault();if(busy||!online)return;const form=e.currentTarget,f=new FormData(form);setBusy(true);try{await callAi({action:'judgmentOutcome',memberId,decisionId:decision.id,requestId:id,...Object.fromEntries(f)});setMessage('후속 결과를 저장했어요. 다음 분석에서 참고합니다.');setId(crypto.randomUUID());form.reset();}catch(e){setMessage(aiMessage(e));}finally{setBusy(false);}}
 return <form className="judgment-form" onSubmit={e=>void submit(e)}><fieldset disabled={busy||!online}><label>관찰 결과<select aria-label="관찰 결과" name="result"><option value="unclear">아직 판단 어려움</option><option value="as_expected">기대한 변화 관찰</option><option value="different">기대와 다른 결과</option></select></label><label>관찰 날짜<input name="observedDate" type="date" required/></label><label>실제 수행·결과와 해석<textarea name="note" required maxLength={500} rows={2}/></label><button>후속 결과 저장</button></fieldset>{message&&<p role="status">{message}</p>}</form>;
}
