"use client";
import {useEffect,useRef,useState} from 'react';
import {JudgmentReport} from './judgment-report';
import {Icon} from './icons';
import {BodyMap} from './body-map';
import {ActualTrend,bodyStats,SavedLessonPlan} from './member-analysis';
import {ContinuousSourceViewer} from './continuous-source-viewer';
import {AssistantChat,type SourceSelection} from './assistant-chat';
import {AnalysisSource,sourceRows} from './analysis-source';
import {MemberFiles} from './member-files';
import {listenMemberFiles,type MemberFile} from '../lib/member-files';
import {listenWorkouts,summarizeWorkouts,type WorkoutRecord} from '../lib/workout-records';
import {serverAiEnabled,aiMessage,callAi,listenAiDocument,listenImports,listenUsage,type Analysis,type SavedImport,type SavedPlan,type AiUsage} from '../lib/server-ai';
type Pane='source'|'analysis'|'plan';
export function LiveAnalysisWorkspace({memberId,memberName,goal,online,uploadRequest=0}:{memberId:string;memberName:string;goal:string;online:boolean;uploadRequest?:number}){
 const [files,setFiles]=useState<MemberFile[]>([]),[imports,setImports]=useState<SavedImport[]>([]),[records,setRecords]=useState<WorkoutRecord[]>([]),[analysis,setAnalysis]=useState<Analysis|null>(null),[plan,setPlan]=useState<SavedPlan|null>(null),[usage,setUsage]=useState<AiUsage>({}),[filesLoaded,setFilesLoaded]=useState(false),[importsLoaded,setImportsLoaded]=useState(false),[analysisLoaded,setAnalysisLoaded]=useState(false),[error,setError]=useState('');
 const [mode,setMode]=useState(2),[pane,setPane]=useState<Pane>('analysis'),[tab,setTab]=useState('summary'),[selectedFile,setSelectedFile]=useState(''),[selectedRow,setSelectedRow]=useState(''),[upload,setUpload]=useState(false),[originalRequest,setOriginalRequest]=useState(0),[uploadNotice,setUploadNotice]=useState(''),[busy,setBusy]=useState(false),[now,setNow]=useState(Date.now());
 const [sourceHidden,setSourceHidden]=useState(false),[selectionMode,setSelectionMode]=useState(false),[selection,setSelection]=useState<SourceSelection|null>(null),[sourcePage,setSourcePage]=useState(1),[originalFile,setOriginalFile]=useState(''),[jumpRequest,setJumpRequest]=useState(0);
 const requestedFiles=useRef(new Set<string>()),requestedAnalysis=useRef(false),dirty=useRef(false),analysisScroll=useRef<HTMLDivElement>(null);
 useEffect(()=>{const fail=(e:unknown)=>setError(aiMessage(e));const offs=[listenMemberFiles(memberId,(v,cached)=>{setFiles(v);if(!cached)setFilesLoaded(true);},fail),listenWorkouts(memberId,v=>setRecords(v.filter(r=>!r.pending)),fail)];if(serverAiEnabled)offs.push(listenImports(memberId,v=>{setImports(v);setImportsLoaded(true);},fail),listenAiDocument<Analysis>(memberId,'analysis',v=>{setAnalysis(v);setAnalysisLoaded(true);},fail),listenAiDocument<SavedPlan>(memberId,'plans',setPlan,fail),listenUsage(setUsage,fail));return()=>offs.forEach(f=>f());},[memberId]);
 useEffect(()=>{if(uploadRequest)setUpload(true);},[uploadRequest]);
 useEffect(()=>{const timer=setInterval(()=>setNow(Date.now()),30000);return()=>clearInterval(timer);},[]);
 useEffect(()=>{analysisScroll.current?.scrollTo({top:0});},[tab]);
 const alive=useRef(true);useEffect(()=>{alive.current=true;return()=>{alive.current=false;};},[]);
 useEffect(()=>{
  if(!serverAiEnabled||!filesLoaded||!importsLoaded||!online)return;
  const missing=files.filter(f=>f.status==='ready'&&!f.pending&&!imports.some(i=>i.id===f.id)&&!requestedFiles.current.has(f.id));
  missing.forEach(f=>requestedFiles.current.add(f.id));
  void(async()=>{for(const f of missing){if(!alive.current)return;try{await callAi({action:'read',memberId,fileId:f.id});}catch(e){if(alive.current)setError(aiMessage(e));}}})();
 },[memberId,files,imports,filesLoaded,importsLoaded,online]);
 useEffect(()=>{if(!serverAiEnabled||!analysisLoaded||analysis||!records.length||requestedAnalysis.current||!online)return;requestedAnalysis.current=true;void callAi({action:'report',memberId}).catch(e=>setError(aiMessage(e)));},[memberId,analysisLoaded,analysis,records.length,online]);
 useEffect(()=>{if(filesLoaded&&selectedFile!=='all'&&!files.some(f=>f.id===selectedFile))setSelectedFile(files.find(f=>f.status==='ready')?.id??'');},[files,filesLoaded,selectedFile]);
 useEffect(()=>{if(originalFile&&originalFile!=='all'&&!files.some(f=>f.id===originalFile))setOriginalFile('');},[files,originalFile]);
 const rows=sourceRows(imports,records),pendingRows=rows.filter(r=>r.review==='needs-review'),reading=serverAiEnabled?files.filter(f=>f.status==='uploading'||f.status==='ready'&&!imports.some(i=>i.id===f.id)||imports.some(i=>i.id===f.id&&i.status==='processing')).length:0,report=analysis?.report,processing=analysis?.status==='queued'||analysis?.status==='processing',stats=bodyStats(records),summary=summarizeWorkouts(records);
 const stalled=analysis?.status==='processing'&&!!analysis.startedAt&&now-analysis.startedAt.toMillis()>180000;
 function openRow(id:string){const r=rows.find(r=>r.id===id);if(!r){setError('근거 기록이 변경됐어요. 최신 분석을 기다려주세요.');return;}if(dirty.current&&id!==selectedRow&&!window.confirm('저장하지 않은 수정 내용을 버리고 다른 기록을 볼까요?'))return;if(id!==selectedRow)dirty.current=false;setSelectedRow(id);setSelectedFile(r.input.sourceHash&&files.some(f=>f.id===r.input.sourceHash)?r.input.sourceHash:'all');setOriginalFile(r.input.sourceHash||'all');setSourcePage(r.input.sourcePage||1);setJumpRequest(v=>v+1);setSourceHidden(false);setPane('source');}
 async function retry(){if(!serverAiEnabled||busy)return;setBusy(true);try{await callAi({action:'report',memberId,retry:true});}catch(e){setError(aiMessage(e));}finally{setBusy(false);}}
 function choosePane(next:Pane){setPane(next);if(next==='source')setSourceHidden(false);}
 function original(fileId:string,page:number){setOriginalFile(fileId);setSourcePage(page);setJumpRequest(v=>v+1);setSourceHidden(false);}
 function selectArea(){setSourceHidden(false);setSelectionMode(true);}
 const sourceProps={memberId,memberName,online,files,imports,rows,selectedFile,onFile:(id:string)=>{setSelectedFile(id);setOriginalFile(id);setSourcePage(1);setJumpRequest(v=>v+1);},selectedRow,onRow:openRow,onUpload:()=>setUpload(true),onDirty:(v:boolean)=>{dirty.current=v;},originalRequest};
 return <div className={'live-workspace review-workspace '+(mode===3?'with-assistant ':'')+(sourceHidden?'source-collapsed ':'')+'working-'+pane} aria-label="업로드 기반 분석 작업실">
 <div className="review-toolbar"><div className="review-context"><strong>{memberName}</strong><span>일지 {files.length}개</span><span className="review-status" role="status">{!serverAiEnabled?'AI 연결 대기':reading?`${reading}개 읽는 중`:processing?'분석 갱신 중':analysis?.status==='ready'?'분석 완료':''}</span></div><div className="review-tools"><button aria-pressed={!sourceHidden} onClick={()=>{setSourceHidden(v=>!v);setSelectionMode(false);}}>원본 {sourceHidden?'보기':'접기'}</button><button onClick={()=>setUpload(true)} disabled={!online}><Icon name="plus" size={14}/> 일지 추가</button><div className="segmented" aria-label="화면 구성"><button aria-pressed={mode===2} className={mode===2?'selected':''} onClick={()=>setMode(2)}>2뷰</button><button aria-pressed={mode===3} className={mode===3?'selected':''} onClick={()=>{setMode(3);setSourceHidden(false);}}>3뷰 · AI</button></div></div></div>
 {uploadNotice&&<p className="file-error" role="status">{uploadNotice}</p>}
 <div className="review-columns">
 <section className="review-original" aria-label="원본 일지" hidden={sourceHidden}>
  <div className="review-source-tools"><select aria-label="원본 파일 이동" value={originalFile||selectedFile} onChange={e=>original(e.target.value,1)}><option value="all">전체 원본 이어 보기</option>{files.map(f=><option value={f.id} key={f.id}>{f.name}</option>)}</select><button aria-pressed={selectionMode} title="원본을 드래그해 질문할 영역을 선택하세요" onClick={()=>setSelectionMode(v=>!v)}>⌖ {selectionMode?'선택 취소':'영역 질문'}</button></div>
  {selectionMode&&<p className="selection-hint">질문할 부분을 드래그하세요. <button onClick={()=>setSelectionMode(false)}>취소</button></p>}
  {files.length?<ContinuousSourceViewer memberId={memberId} files={files} selectedFile={originalFile||selectedFile} sourcePage={sourcePage} jumpRequest={jumpRequest} selectionMode={selectionMode} onSelection={v=>{setSelection(v);setSelectionMode(false);setMode(3);}}/>:<div className="empty-state"><Icon name="upload" size={30}/><h3>일지를 올려주세요</h3><p>PDF·PNG·JPEG를 한 화면에서 볼 수 있어요.</p><button className="primary" onClick={()=>setUpload(true)}>일지 추가</button></div>}
 </section>
 <div className="review-work"><nav className="review-tabs" aria-label="작업 화면">{([['analysis','진행 분석'],['plan','다음 수업'],['source','기록 수정']] as [Pane,string][]).map(([id,label])=><button key={id} aria-current={pane===id?'page':undefined} onClick={()=>choosePane(id)}>{label}{id==='source'&&pendingRows.length>0&&<span>{pendingRows.length}</span>}</button>)}</nav>
 <div className="review-content" hidden={pane!=='source'}><AnalysisSource {...sourceProps} recordsOnly/></div>
 <div className="review-content" hidden={pane!=='analysis'}>
 <section className="live-pane live-analysis" aria-label="진행 분석"><div className="analysis-tabs" role="tablist" aria-label="진행 분석 내용">{[['summary','요약'],['body','부위별 분포'],['trend','변화 추이'],['goal','목표·강도']].map(([id,label])=><button key={id} role="tab" aria-selected={tab===id} className={tab===id?'active':''} onClick={()=>setTab(id)}>{label}</button>)}</div><div className="pane-body" ref={analysisScroll}>
 {!serverAiEnabled&&<div className="file-error" role="status"><strong>자동 분석 서버 연결을 준비하고 있어요</strong><p>원본 업로드와 열람은 가능해요. 서버 연결이 완료되면 이 화면에서 자동 판독·요약·다음 수업 제안이 시작됩니다.</p></div>}
 {(reading>0||processing)&&<div className="live-processing" role="status"><span className="ai-reading-dot"/><div><strong>{reading?'일지를 읽어 분석하고 있어요':'수정한 내용으로 의견을 갱신하고 있어요'}</strong><p>{records.length?'확인 가능한 기록부터 표시합니다. 이전 AI 의견은 갱신 전 내용이에요.':'완료된 결과부터 이 화면에 자동으로 표시돼요. 기록을 하나씩 확인할 필요 없어요.'}</p></div></div>}
 {(analysis?.status==='error'||analysis?.status==='limited'||stalled)&&<div className="file-error"><p>{analysis?.error||'분석이 지연되고 있어요.'}</p><button disabled={busy||!online} onClick={()=>void retry()}>분석 다시 시도</button></div>}
 {pendingRows.length>0&&<button className="live-review-banner" onClick={()=>openRow(pendingRows[0].id)}><Icon name="search"/><span><strong>확인하면 더 정확해지는 항목 {pendingRows.length}개</strong><small>분석은 먼저 볼 수 있어요. 잘못 읽힌 값만 원본 옆에서 수정하세요.</small></span><Icon name="arrow"/></button>}
 {tab==='summary'&&<><span className="section-eyebrow">업로드한 일지 기준 · 종합 의견</span><h1>{report?.headline||(reading||processing?'기록을 읽고, 다음 수업을 준비하고 있어요.':serverAiEnabled?'일지를 올리면 분석이 바로 시작돼요.':'원본은 준비됐어요. 자동 분석 연결이 남아 있어요.')}</h1><p className="intro ai-overview">{report?.overview||'운동일지 PDF·PNG·JPEG를 올려주세요. 원본과 진행 분석, 다음 수업을 한 화면에서 확인할 수 있어요.'}</p><div className="summary-metrics"><div><span>기록된 날짜</span><strong>{summary.days.size}<small>일</small></strong></div><div><span>기록된 세트</span><strong>{summary.sets}<small>세트</small></strong></div><div><span>기록 볼륨</span><strong className="live-volume">{summary.volume.toLocaleString()}<small>kg·회</small></strong></div></div>
 <JudgmentReport memberId={memberId} context={analysis?.judgmentContext} judgments={report?.judgments} fingerprint={analysis?.fingerprint??''} records={records} online={online} onEvidence={openRow}/>
 {report?.findings.map((v,i)=><article className="finding" key={i}><span className="finding-index">{String(i+1).padStart(2,'0')}</span><div><h3>{v.title}</h3><p>{v.detail}</p><div className="ai-evidence">{v.evidenceIds.map(id=><button className="text-button" key={id} onClick={()=>openRow(id)}>{records.find(r=>r.id===id)?.date??'근거'} 기록 보기 <Icon name="arrow" size={14}/></button>)}</div></div></article>)}
 {records.length>0&&<><div className="section-title"><h2>부위별 운동 분포</h2><button className="text-button" onClick={()=>setTab('body')}>자세히 보기</button></div><BodyMap stats={stats} compact sourceLabel="실제 판독 기록" onSource={date=>{const r=records.find(r=>r.date===date);if(r)openRow(r.id);}}/></>}
 {!!report?.limitations.length&&<div className="quiet-card"><h3>해석할 때 함께 볼 점</h3><ul>{report.limitations.map((v,i)=><li key={i}>{v}</li>)}</ul></div>}<button className="primary wide next-step" onClick={()=>setPane('plan')}>다음 수업 준비 보기 <Icon name="arrow" size={16}/></button></>}
 {tab==='body'&&<><h1>어느 부위를 얼마나 운동했을까요?</h1><p className="intro">판독·수정된 실제 세트 기록으로 바로 계산해요.</p><BodyMap stats={stats} sourceLabel="실제 판독 기록" onSource={date=>{const r=records.find(r=>r.date===date);if(r)openRow(r.id);}}/></>}
 {tab==='trend'&&<><h1>한 번의 숫자보다, 기록의 흐름.</h1><p className="intro">값을 수정하면 AI 재판독 없이 바로 반영돼요.</p><ActualTrend records={records}/></>}
 {tab==='goal'&&<><h1>목표를 기준으로 강도를 해석해요.</h1><div className="goal-card"><span className="section-eyebrow">회원 목표</span><h3>{goal||'설정된 목표가 없어요'}</h3></div><div className="quiet-card"><h3>무게·횟수만으로 개인 강도를 단정하지 않아요.</h3><p>목표와 실제 수행 노력(RPE/RIR), 컨디션을 함께 확인해야 해요. 없는 나이·성별·측정값을 추정해서 기준을 적용하지 않습니다.</p></div>{report?.questions.map((q,i)=><p key={i}>{q}</p>)}</>}
 <p className="record-help">자동 판독은 잠정 기록입니다. 확인이 필요한 값은 집계에서 제외해요. AI 의견은 최근 {analysis?.scopeLimit??120}개 운동 항목, 그래프·부위 분포는 저장된 전체 기록 기준이에요.</p>{serverAiEnabled&&<details className="ai-usage"><summary>AI 이용량 · 저장된 결과는 재사용해요</summary><p>이번 달 입력 {(usage.inputTokens??0).toLocaleString()} · 출력 {(usage.outputTokens??0).toLocaleString()} 토큰</p><p>예상 모델 원가 ${((usage.usedMicros??0)/1e6).toFixed(4)} / ${((usage.monthlyLimitMicros??1000000)/1e6).toFixed(2)} · 하루 요청 30회 제한</p><p>원본 수정은 재판독하지 않아요. 의견이 달라지는 수정만 모아 재분석하며, 서버·저장소 비용은 별도입니다.</p></details>}{error&&<p className="file-error" role="alert">{error}</p>}
 </div></section></div>
 <div className="review-content" hidden={pane!=='plan'}><section className="live-pane live-plan" aria-label="다음 수업 준비"><div className="pane-body"><span className="pill">{plan?'트레이너가 저장한 계획':'AI 초안 · 트레이너 검토 전'}</span><h2 className="prep-title">종합 의견에서,<br/>오늘의 프로그램으로.</h2><div className="goal-mini"><Icon name="target"/><span>{goal||'목표를 함께 확인해주세요'}</span></div>{!!report?.questions.length&&<div className="quiet-card"><h3>먼저 확인할 것</h3>{report.questions.map((q,i)=><p key={i}>{q}</p>)}</div>}<SavedLessonPlan memberId={memberId} plan={plan} draft={report?.program??[]} fingerprint={analysis?.fingerprint??''} online={online} onEvidence={openRow}/>{!!report?.quests.length&&<div className="quiet-card"><h3>선택 실천 과제</h3><ul>{report.quests.map((q,i)=><li key={i}>{q}</li>)}</ul></div>}</div></section></div></div>
 <div className="review-assistant" hidden={mode!==3}><AssistantChat memberId={memberId} online={online} selection={selection} onClearSelection={()=>setSelection(null)} onSelectArea={selectArea} onClose={()=>setMode(2)} onEvidence={openRow} onOriginal={original}/></div></div>
 {upload&&<UploadDialog onClose={()=>setUpload(false)}><MemberFiles memberId={memberId} memberName={memberName} online={online} onUploaded={(id,result)=>{setUploadNotice(result.failed?`${result.uploaded}개 업로드 완료 · ${result.failed}개 실패. 일지 추가에서 실패한 파일을 다시 올려주세요.`:'');setSelectedFile(id);setOriginalFile(id);setSelectedRow('');setSourcePage(1);setSourceHidden(false);setJumpRequest(v=>v+1);setOriginalRequest(v=>v+1);setPane('analysis');setTab('summary');setUpload(false);}}/></UploadDialog>}
 </div>;
}
function UploadDialog({onClose,children}:{onClose:()=>void;children:React.ReactNode}){const ref=useRef<HTMLDialogElement>(null);useEffect(()=>{const old=document.activeElement as HTMLElement|null;ref.current?.showModal();return()=>old?.focus();},[]);return <dialog ref={ref} className="live-upload-dialog" onCancel={e=>{e.preventDefault();onClose();}}><div className="dialog-title"><div><h2>일지를 올리면 분석이 시작돼요</h2><p>읽은 결과는 저장하므로 다시 열 때 재판독하지 않아요.</p></div><button className="icon-button" aria-label="업로드 닫기" onClick={onClose}><Icon name="close"/></button></div>{children}</dialog>;}
