"use client";
import {MotionHeight} from './motion-height';
import {useId,useRef,useLayoutEffect} from 'react';
import {WorkoutSelect} from './workout-select';
import type {WorkoutInput} from '../lib/workout-records';
import {measurementType,measurementLabels,blankSet,convertWorkoutSets,type MeasurementType} from '../lib/workout-measurements';
export function MeasurementFields({input,onChange}:{input:WorkoutInput;onChange:(patch:Partial<WorkoutInput>)=>void}){
 const prefix=useId(),serial=useRef(0),keys=useRef<string[]>([]),list=useRef<HTMLDivElement>(null),positions=useRef(new Map<string,number>());
 while(keys.current.length<input.sets.length)keys.current.push(prefix+'-'+serial.current++);
 if(keys.current.length>input.sets.length)keys.current.length=input.sets.length;
 useLayoutEffect(()=>{const nodes=list.current?.querySelectorAll<HTMLElement>('.inline-set');if(!nodes)return;const next=new Map<string,number>();nodes.forEach(node=>{const id=node.dataset.motionKey!,top=node.offsetTop;next.set(id,top);const old=positions.current.get(id);if(!matchMedia('(prefers-reduced-motion: reduce)').matches){if(old!==undefined&&old!==top)node.animate([{transform:`translateY(${old-top}px)`},{transform:'none'}],{duration:260,easing:'cubic-bezier(.22,1,.36,1)'});else if(old===undefined&&positions.current.size)node.animate([{opacity:0,transform:'translateY(8px)'},{opacity:1,transform:'none'}],{duration:220,easing:'ease-out'});}});positions.current=next;},[input.sets.length]);
 const kind=measurementType(input),cardio=kind!=='repetitions',incline=kind==='incline_speed_time',sided=!cardio&&input.sets.some(s=>s.leftReps!==undefined||s.rightReps!==undefined);
 function side(index:number,key:'leftReps'|'rightReps',value:string){onChange({sets:input.sets.map((s,i)=>{if(i!==index)return s;const next={...s,[key]:Number(value),leftReps:s.leftReps??0,rightReps:s.rightReps??0};next[key]=Number(value);return {...next,reps:next.leftReps+next.rightReps};})});}
 function set(index:number,key:'kg'|'reps'|'distanceMeters'|'durationSeconds'|'inclinePercent'|'speedKph',value:string){onChange({sets:input.sets.map((s,i)=>i===index?{...s,[key]:value===''?(key==='reps'?0:null):Number(value)}:s)});}
 return <div className="measurement-controls"><div className="measurement-options"><div className="record-select-field"><span>기록 방식</span><WorkoutSelect label="기록 방식" value={kind} options={Object.entries(measurementLabels).map(([value,label])=>({value,label}))} onChange={value=>{const measurementType=value as MeasurementType;onChange({measurementType,loadType:measurementType==='repetitions'?'weighted':'unknown',sets:convertWorkoutSets(input.sets,measurementType)});}}/></div>
 {!cardio&&<div className="record-select-field"><span>중량 기준</span><WorkoutSelect label="중량 기준" value={input.loadType} options={[{value:'weighted',label:'kg'},{value:'bodyweight',label:'맨몸'},{value:'unknown',label:'미상'}]} onChange={value=>onChange({loadType:value as WorkoutInput['loadType'],sets:input.sets.map(s=>({...s,kg:null}))})}/></div>}{!cardio&&<div className="record-select-field"><span>횟수 구분</span><WorkoutSelect label="횟수 구분" value={sided?'sides':'total'} options={[{value:'total',label:'일반 횟수'},{value:'sides',label:'좌우 구분 (L/R)'}]} onChange={value=>onChange({sets:input.sets.map(s=>value==='sides'?{...s,leftReps:0,rightReps:0,reps:0}:{kg:s.kg,reps:0})})}/></div>}</div>{sided&&<p className="measurement-side-hint">L·R 각각의 횟수를 입력하세요. 좌우를 합쳐 1세트로, 운동량은 양쪽 횟수의 합으로 계산해요.</p>}
 <MotionHeight><div ref={list} className="measurement-set-list" data-columns={sided||incline?3:kind==='distance'||kind==='duration'?1:2}><div className="measurement-column-labels" aria-hidden="true"><span>{cardio?'구간':'세트'}</span>{incline&&<><span>경사 (%)</span><span>속도 (km/h)</span></>}{!incline&&kind!=='duration'&&<span>{cardio?'거리 (m)':'중량 (kg)'}</span>}{kind!=='distance'&&<span>{cardio?'시간 (초)':sided?'L · 왼쪽 (회)':'횟수 (회)'}</span>}{sided&&<span>R · 오른쪽 (회)</span>}<span/></div>{input.sets.map((s,i)=><div className="inline-set" key={keys.current[i]} data-motion-key={keys.current[i]}><span>{i+1}{cardio?'구간':'세트'}</span>
 {cardio?<>{incline&&<><label><span className="measurement-visually-hidden">경사 (%)</span><input type="number" aria-label={`${i+1}구간 경사`} min={-100} max={100} step="any" required value={s.inclinePercent??''} onChange={e=>set(i,'inclinePercent',e.target.value)}/></label><label><span className="measurement-visually-hidden">속도 (km/h)</span><input type="number" aria-label={`${i+1}구간 속도`} min={0} max={100} step="any" required value={s.speedKph??''} onChange={e=>set(i,'speedKph',e.target.value)}/></label></>}{!incline&&kind!=='duration'&&<label><span className="measurement-visually-hidden">거리 (m)</span><input type="number" aria-label={`${i+1}구간 거리`} min="0.01" max={1000000} step="any" required value={s.distanceMeters??''} onChange={e=>set(i,'distanceMeters',e.target.value)}/></label>}{kind!=='distance'&&<label><span className="measurement-visually-hidden">시간 (초)</span><input type="number" aria-label={`${i+1}구간 시간`} min="0.01" max={86400} step="any" required value={s.durationSeconds??''} onChange={e=>set(i,'durationSeconds',e.target.value)}/></label>}</>:<><label><span className="measurement-visually-hidden">중량 (kg)</span><input type="number" aria-label={`수정 ${i+1}세트 중량`} min="0.01" max={2000} step="any" required={input.loadType==='weighted'} disabled={input.loadType!=='weighted'} value={s.kg??''} onChange={e=>set(i,'kg',e.target.value)}/></label>{sided?(['leftReps','rightReps'] as const).map((key)=><label key={key}><span className="measurement-visually-hidden">{key==='leftReps'?'L · 왼쪽':'R · 오른쪽'} (회)</span><input type="number" aria-label={`${i+1}세트 ${key==='leftReps'?'L 왼쪽':'R 오른쪽'} 횟수`} min={1} max={1000} step={1} required value={s[key]||''} onChange={e=>side(i,key,e.target.value)}/></label>):<label><span className="measurement-visually-hidden">횟수 (회)</span><input type="number" aria-label={`수정 ${i+1}세트 횟수`} min={1} max={1000} step={1} required value={s.reps||''} onChange={e=>set(i,'reps',e.target.value)}/></label>}</>}
 <button type="button" aria-label={`${i+1}${cardio?'구간':'세트'} 삭제`} disabled={input.sets.length<=1} onClick={()=>{keys.current.splice(i,1);onChange({sets:input.sets.filter((_,j)=>j!==i)});}}>−</button></div>)}</div></MotionHeight>
 <button className="measurement-add" type="button" disabled={input.sets.length>=8} onClick={()=>onChange({sets:[...input.sets,{...blankSet(kind),...(sided?{leftReps:0,rightReps:0}:{})}]})}>+ {cardio?'구간 추가':'세트 추가'}</button></div>;
}
