"use client";
import {useEffect,useRef,useState,type FormEvent} from "react";
import {Icon} from "./icons";
import {inspectPdf} from "../lib/member-files";
import {BODY_PARTS,deleteWorkout,listenWorkouts,saveWorkout,summarizeWorkouts,validateWorkout,workoutError,type WorkoutInput,type WorkoutRecord} from "../lib/workout-records";

export function MemberRecords({memberId,memberName,online}:{memberId:string;memberName:string;online:boolean}){
  const [records,setRecords]=useState<WorkoutRecord[]>([]),[cached,setCached]=useState(true),[loading,setLoading]=useState(true),[error,setError]=useState(""),[attempt,setAttempt]=useState(0),[notice,setNotice]=useState("");
  const [editor,setEditor]=useState<WorkoutRecord|"new"|null>(null),[remove,setRemove]=useState<WorkoutRecord|null>(null),[busy,setBusy]=useState(false);
  const alive=useRef(true);
  useEffect(()=>{alive.current=true;return()=>{alive.current=false;};},[]);
  useEffect(()=>{setLoading(true);setError("");try{return listenWorkouts(memberId,(data,cache)=>{setRecords(data);setCached(cache);if(!cache||data.length)setLoading(false);},e=>{setError(workoutError(e));setRecords([]);setCached(true);setLoading(false);});}catch(e){setError(workoutError(e));setLoading(false);}},[memberId,attempt]);
  const available=online&&!cached&&!loading&&!busy&&!error,summary=summarizeWorkouts(records);
  async function erase(){if(!remove||busy)return;setBusy(true);setError("");try{await deleteWorkout(memberId,remove);if(alive.current){setRemove(null);setNotice("운동 기록을 삭제했어요.");}}catch(e){if(alive.current)setError(workoutError(e));}finally{if(alive.current)setBusy(false);}}
  return <section className="member-records" aria-label="확정 운동 기록">
    <div className="file-section-heading"><div><h2>확정 운동 기록 <span>{records.length}</span></h2><p>원본과 대조해 확인한 기록을 회원에게 저장하세요.</p></div><button className="primary" disabled={!available} onClick={()=>{setNotice("");setEditor("new");}}><Icon name="plus" size={16}/> 기록 입력</button></div>
    <p className="record-help">PDF를 옆에 띄워 직접 입력할 수 있어요. 지금은 AI 자동 판독 없이 트레이너가 확인한 값을 저장합니다.</p>
    {records.length>0&&<><div className="record-metrics"><div><small>기록된 운동 날짜</small><strong>{summary.days.size}<em>일</em></strong></div><div><small>확정된 총세트</small><strong>{summary.sets}<em>세트</em></strong></div><div><small>기록 볼륨</small><strong>{summary.volume.toLocaleString()}<em>kg·회</em></strong></div></div><p className="record-help">볼륨은 중량 × 횟수의 합계예요. 맨몸·중량 미상 {summary.excluded}세트는 제외합니다. 운동·기구가 다르면 볼륨만으로 강도를 비교하지 않아요.</p><div className="record-parts" aria-label="확정 기록 부위별 세트 비중">{Array.from(summary.parts).map(([part,count])=><span key={part}>{part} <strong>{count}세트 · {Math.round(count/summary.sets*100)}%</strong></span>)}</div><p className="record-help">각 운동에서 선택한 주 부위 1곳으로 집계해요. 보조 근육의 자극량을 뜻하지 않습니다.</p></>}
    {loading?<p className="file-empty" role="status">{online?"기록을 불러오고 있어요.":"인터넷 연결을 기다리고 있어요."}</p>:!records.length?<div className="record-empty"><Icon name="edit" size={24}/><h3>첫 운동 기록을 남겨보세요</h3><p>운동 1종목씩 날짜와 세트를 저장하면 실제 데이터가 쌓여요.</p></div>:<ul className="record-list">{records.map(r=><li key={r.id}><div><small>{r.date} · {r.bodyPart} · {r.pending?'동기화 중':'직접 확인'}</small><h3>{r.exerciseName}</h3><p>{r.sets.map(s=>`${s.kg===null?(r.loadType==='bodyweight'?'맨몸':'중량 미상'):s.kg+'kg'} × ${s.reps}회`).join(' / ')}</p><small>{r.sourceName?`${r.sourceName} · ${r.sourcePage}쪽 · 원본은 로컬 파일`:'원본 PDF 없이 직접 입력'}</small></div><div className="saved-file-actions"><button disabled={!available||r.pending} onClick={()=>setEditor(r)} aria-label={r.exerciseName+' 기록 수정'}>확인·수정</button><button disabled={!available||r.pending} onClick={()=>setRemove(r)} aria-label={r.exerciseName+' 기록 삭제'}>삭제</button></div></li>)}</ul>}
    {error&&<div className="file-error" role="alert"><p>{error}</p><button onClick={()=>setAttempt(v=>v+1)}>기록 다시 불러오기</button></div>}{notice&&<p className="file-notice" role="status">{notice}</p>}
    {editor&&<RecordEditor memberId={memberId} memberName={memberName} existing={editor==='new'?undefined:editor} online={online} onClose={()=>setEditor(null)} onSaved={()=>{setEditor(null);setNotice("운동 기록을 저장했어요.");}}/>}
    {remove&&<DeleteDialog record={remove} busy={busy} online={online} error={error} onClose={()=>setRemove(null)} onDelete={()=>void erase()}/>}
  </section>;
}
const blank=():WorkoutInput=>({date:"",rawName:"",exerciseName:"",bodyPart:"미분류",loadType:"weighted",sets:[{kg:null,reps:0}],sourceName:"",sourceHash:"",sourcePage:0,notes:""});
function RecordEditor({memberId,memberName,existing,online,onClose,onSaved}:{memberId:string;memberName:string;existing?:WorkoutRecord;online:boolean;onClose:()=>void;onSaved:()=>void}){
  const [input,setInput]=useState<WorkoutInput>(existing?{date:existing.date,rawName:existing.rawName,exerciseName:existing.exerciseName,bodyPart:existing.bodyPart,loadType:existing.loadType,sets:existing.sets,sourceName:existing.sourceName,sourceHash:existing.sourceHash,sourcePage:existing.sourcePage,notes:existing.notes}:blank);
  const [url,setUrl]=useState(""),[error,setError]=useState(""),[busy,setBusy]=useState(false),[reading,setReading]=useState(false),[dirty,setDirty]=useState(false),[discard,setDiscard]=useState(false),[confirmed,setConfirmed]=useState(false);
  const dialog=useRef<HTMLDialogElement>(null),alive=useRef(true),objectUrl=useRef(""),pending=useRef(false);
  function update(patch:Partial<WorkoutInput>){setInput(v=>({...v,...patch}));setDirty(true);setConfirmed(false);setDiscard(false);}
  useEffect(()=>{alive.current=true;const previous=document.activeElement as HTMLElement|null;dialog.current?.showModal();return()=>{alive.current=false;if(objectUrl.current)URL.revokeObjectURL(objectUrl.current);previous?.focus();};},[]);
  useEffect(()=>{if(!dirty&&!busy)return;const warn=(e:BeforeUnloadEvent)=>{e.preventDefault();e.returnValue="";};window.addEventListener('beforeunload',warn);return()=>window.removeEventListener('beforeunload',warn);},[dirty,busy]);
  function close(){if(busy||reading)return;if(dirty)setDiscard(true);else onClose();}
  async function load(file?:File){if(!file||reading)return;setReading(true);setError("");try{const hash=await inspectPdf(file);if(existing&&hash!==existing.sourceHash)throw new Error("저장된 기록의 원본 PDF와 다른 파일이에요. 원래 PDF를 선택해주세요.");if(!alive.current)return;if(objectUrl.current)URL.revokeObjectURL(objectUrl.current);objectUrl.current=URL.createObjectURL(file);setUrl(objectUrl.current);if(!existing)update({sourceHash:hash,sourceName:file.name,sourcePage:1});}catch(e){if(alive.current)setError(e instanceof Error?e.message:"PDF를 열지 못했어요.");}finally{if(alive.current)setReading(false);}}
  async function submit(e:FormEvent){e.preventDefault();if(pending.current||!online||!confirmed||reading)return;setError("");try{validateWorkout(input);}catch(e){setError(workoutError(e));return;}pending.current=true;setBusy(true);try{await saveWorkout(memberId,input,existing);if(alive.current)onSaved();}catch(e){if(alive.current)setError(workoutError(e));}finally{pending.current=false;if(alive.current)setBusy(false);}}
  return <dialog className="record-editor" ref={dialog} onCancel={e=>{e.preventDefault();close();}}><div className="record-editor-heading"><div><small>{memberName} · 기록 확인</small><h2>{existing?'운동 기록 확인·수정':'운동 기록 입력'}</h2></div><button className="icon-button" aria-label="닫기" onClick={close} disabled={busy||reading}><Icon name="close"/></button></div>
    <div className="record-editor-grid"><section className="record-source"><div className="record-source-heading"><h3>원본 PDF</h3><label className="record-pick">{reading?'파일 확인 중…':url?'PDF 다시 선택':'로컬 PDF 열기'}<input type="file" accept=".pdf,application/pdf" disabled={busy||reading||!!existing&&!existing.sourceHash} aria-label="대조할 PDF 선택" onChange={e=>{void load(e.target.files?.[0]);e.target.value='';}}/></label></div><p>PDF는 이 화면에서만 열려요. 서버에는 입력한 기록과 원본 파일명·식별 정보만 저장합니다.</p>{url&&<a className="record-source-link" href={url} target="_blank" rel="noopener noreferrer">원본을 새 탭에서 열기 ↗</a>}{url?<iframe title="대조용 원본 PDF" src={url+'#page='+Math.max(1,input.sourcePage)}/>:<div className="record-source-empty"><Icon name="file" size={32}/><p>{existing?.sourceName?`${existing.sourceName} 파일을 다시 선택해 대조할 수 있어요.`:'PDF 없이 직접 입력해도 됩니다. 빈 기록에서 시작해요.'}</p></div>}</section>
    <form onSubmit={e=>void submit(e)} className="record-form"><fieldset disabled={busy||reading}><label className="field-label">운동 날짜 <span>연도 포함 · 필수</span><input type="date" required min="1900-01-01" max="2100-12-31" value={input.date} onChange={e=>update({date:e.target.value})}/></label>{input.sourceHash&&<label className="field-label">원본 페이지<input type="number" required min={1} max={10000} step={1} value={input.sourcePage||''} onChange={e=>update({sourcePage:Number(e.target.value)})}/></label>}
    <label className="field-label">원문 운동명 <span>선택</span><input maxLength={100} value={input.rawName} onChange={e=>update({rawName:e.target.value})} placeholder="예: BB sq"/></label><label className="field-label">확인한 운동명 <span>필수</span><input required maxLength={100} value={input.exerciseName} onChange={e=>update({exerciseName:e.target.value})} placeholder="예: 바벨 백 스쿼트"/></label><p className="record-help">원문의 약어와 실제 운동을 구분해 확인해주세요. 서로 다른 운동을 임의로 합치지 않습니다.</p>
    <div className="record-form-pair"><label className="field-label">주 운동 부위<select value={input.bodyPart} onChange={e=>update({bodyPart:e.target.value})}>{BODY_PARTS.map(part=><option key={part}>{part}</option>)}</select></label><label className="field-label">중량 기준<select value={input.loadType} onChange={e=>update({loadType:e.target.value as WorkoutInput['loadType'],sets:input.sets.map(s=>({...s,kg:null}))})}><option value="weighted">외부 중량 (kg)</option><option value="bodyweight">맨몸</option><option value="unknown">중량 미상</option></select></label></div>
    <div className="record-set-heading"><h3>세트 기록</h3><button type="button" disabled={input.sets.length>=8} onClick={()=>update({sets:[...input.sets,{kg:null,reps:0}]})}>세트 추가</button></div><p className="record-help">최대 8세트 · 덤벨은 기록에 적힌 중량을 입력하고, 한 손/양손 기준을 메모에 남겨주세요.</p>
    {input.sets.map((s,i)=><div className="record-set" key={i}><span>{i+1}</span><label>kg<input aria-label={`${i+1}세트 중량`} type="number" required={input.loadType==='weighted'} disabled={input.loadType!=='weighted'} min="0.01" max="2000" step="any" value={s.kg??''} placeholder={input.loadType==='bodyweight'?'맨몸':input.loadType==='unknown'?'미상':'kg'} onChange={e=>update({sets:input.sets.map((v,j)=>i===j?{...v,kg:e.target.value===''?null:Number(e.target.value)}:v)})}/></label><label>회<input aria-label={`${i+1}세트 횟수`} type="number" required min={1} max={1000} step={1} value={s.reps||''} onChange={e=>update({sets:input.sets.map((v,j)=>i===j?{...v,reps:Number(e.target.value)}:v)})}/></label><button type="button" aria-label={`${i+1}세트 삭제`} disabled={input.sets.length===1} onClick={()=>update({sets:input.sets.filter((_,j)=>i!==j)})}><Icon name="close" size={15}/></button></div>)}
    <label className="field-label">기록 메모 <span>선택</span><textarea rows={2} maxLength={1000} value={input.notes} onChange={e=>update({notes:e.target.value})} placeholder="중량 표기 기준, 동작 변형 등"/></label><label className="record-confirm"><input type="checkbox" checked={confirmed} onChange={e=>setConfirmed(e.target.checked)}/> 날짜·운동·세트 값을 확인했어요.</label></fieldset>
    {error&&<p className="file-error" role="alert">{error}</p>}{!online&&<p className="file-error" role="status">인터넷 연결 후 저장할 수 있어요.</p>}{busy&&<p role="status">서버에 저장하고 있어요. 완료될 때까지 기다려주세요.</p>}{discard&&<div className="file-error"><p>입력한 내용이 아직 저장되지 않았어요.</p><button type="button" onClick={onClose}>작성 내용 버리고 닫기</button><button type="button" onClick={()=>setDiscard(false)}>계속 작성</button></div>}
    <div className="dialog-footer"><button type="button" onClick={close} disabled={busy||reading}>취소</button><button className="primary" disabled={busy||reading||!online||!confirmed}>{busy?'저장 중…':'확정하고 저장'}</button></div></form></div></dialog>;
}
function DeleteDialog({record,busy,online,error,onClose,onDelete}:{record:WorkoutRecord;busy:boolean;online:boolean;error:string;onClose:()=>void;onDelete:()=>void}){
 const ref=useRef<HTMLDialogElement>(null);useEffect(()=>{const previous=document.activeElement as HTMLElement|null;ref.current?.showModal();return()=>previous?.focus();},[]);
 return <dialog ref={ref} className="upload-dialog member-dialog" onCancel={e=>{e.preventDefault();if(!busy)onClose();}}><h2>운동 기록을 삭제할까요?</h2><p>{record.date} · {record.exerciseName} 기록이 삭제되고 집계에서도 제외돼요.</p>{error&&<p role="alert" className="file-error">{error}</p>}<div className="dialog-footer"><button onClick={onClose} disabled={busy}>취소</button><button className="member-danger" disabled={busy||!online} onClick={onDelete}>{busy?'삭제 중…':'기록 삭제'}</button></div></dialog>;
}
