"use client";
import {useEffect,useRef,useState} from 'react';
import {BodyMap} from './body-map';
import {RecordEditor} from './member-records';
import {partDefinitions,type Insights} from './workout-insights';
import {listenWorkouts,type WorkoutRecord} from '../lib/workout-records';
import {aiMessage,callAi,listenAiDocument,listenUsage,type Analysis,type SavedPlan,type PlanRow,type AiUsage} from '../lib/server-ai';
function bodyStats(records:WorkoutRecord[]):Insights{
 const parts=partDefinitions.map(p=>{const matching=records.filter(r=>r.bodyPart===p.label);return {...p,sets:matching.reduce((n,r)=>n+r.sets.length,0),occurrences:matching.length,sessionDates:[...new Set(matching.map(r=>r.date))],exercises:[...new Set(matching.map(r=>r.exerciseName))],percent:0};});
 const totalSets=records.reduce((n,r)=>n+r.sets.length,0),classified=parts.reduce((n,p)=>n+p.sets,0),raw=parts.map(p=>classified?p.sets/classified*100:0),rounded=raw.map(Math.floor);
 raw.map((v,i)=>({i,f:v-rounded[i]})).sort((a,b)=>b.f-a.f).slice(0,classified?100-rounded.reduce((a,b)=>a+b,0):0).forEach(v=>rounded[v.i]++);parts.forEach((p,i)=>p.percent=rounded[i]);
 return {parts,totalSets,unknownSets:totalSets-classified,sessionCount:new Set(records.map(r=>r.date)).size,top:[...parts].sort((a,b)=>b.sets-a.sets)[0]};
}
export function MemberAnalysis({memberId,memberName,online}:{memberId:string;memberName:string;online:boolean}){
 const [analysis,setAnalysis]=useState<Analysis|null>(null),[plan,setPlan]=useState<SavedPlan|null>(null),[records,setRecords]=useState<WorkoutRecord[]>([]),[usage,setUsage]=useState<AiUsage>({}),[error,setError]=useState(''),[busy,setBusy]=useState(false),[tab,setTab]=useState('report'),[editor,setEditor]=useState<WorkoutRecord|null>(null),[loaded,setLoaded]=useState(false);
 const requested=useRef(false);
 useEffect(()=>{const fail=(e:unknown)=>setError(aiMessage(e));const offs=[listenAiDocument<Analysis>(memberId,'analysis',v=>{setAnalysis(v);setLoaded(true);},fail),listenAiDocument<SavedPlan>(memberId,'plans',setPlan,fail),listenWorkouts(memberId,v=>setRecords(v.filter(r=>!r.pending)),fail),listenUsage(setUsage,fail)];return()=>offs.forEach(f=>f());},[memberId]);
 useEffect(()=>{if(!loaded||analysis||!records.length||requested.current||!online)return;requested.current=true;void callAi({action:'report',memberId}).catch(e=>setError(aiMessage(e)));},[loaded,analysis,records.length,online,memberId]);
 async function retry(){setBusy(true);setError('');try{await callAi({action:'report',memberId,retry:true});}catch(e){setError(aiMessage(e));}finally{setBusy(false);}}
 const [now,setNow]=useState(Date.now());useEffect(()=>{const timer=setInterval(()=>setNow(Date.now()),30000);return()=>clearInterval(timer);},[]);
 const stale=analysis?.status==='processing'&&!!analysis.startedAt&&now-analysis.startedAt.toMillis()>180000;
 const report=analysis?.report,pending=analysis?.status==='processing'||analysis?.status==='queued',stats=bodyStats(records);
 const openRecord=(id:string)=>{const r=records.find(r=>r.id===id);if(r)setEditor(r);else setError('근거 기록이 변경되거나 삭제됐어요. 최신 분석을 기다려주세요.');};
 return <section className="member-ai" aria-label="진행 분석과 다음 수업"><div className="file-section-heading"><div><span className="section-eyebrow">기록에서 다음 수업까지</span><h2>진행 분석 · 수업 준비</h2><p>기록이 달라지면 필요한 분석만 갱신해요.</p></div><span className="ai-status" role="status">{pending?'분석 준비 중':analysis?.status==='ready'?'저장된 결과':analysis?.status==='limited'?'이용 한도 도달':'분석 대기'}</span></div>
 <div className="saved-ai-tabs" role="tablist" aria-label="분석 보기">{[['report','종합 의견'],['body','부위별 분포'],['trend','변화 추이'],['plan','다음 수업 준비']].map(([id,label])=><button key={id} role="tab" aria-selected={tab===id} onClick={()=>setTab(id)}>{label}</button>)}</div>
 {pending&&<p className="member-notice" role="status">최근 변경 사항을 모아 분석하고 있어요. 이전 결과가 있다면 아래에 유지돼요.</p>}
 {(analysis?.status==='error'||analysis?.status==='limited'||stale)&&<div className="file-error"><p>{analysis?.error||'분석이 지연되고 있어요. 다시 시도할 수 있어요.'}</p><button disabled={busy||!online} onClick={()=>void retry()}>분석 다시 시도</button><small>실제 재분석이 실행되면 AI 이용량에 포함돼요.</small></div>}
 {!!analysis?.excludedCount&&<p className="ai-review-issues">확인 필요·미분류 원문 {analysis.excludedCount}개를 제외한 부분 분석이에요. 운동일지의 ‘기록 보기’에서 보완하세요.</p>}
 <div className="member-ai-content" role="tabpanel">
 {tab==='report'&&(report?<><h3 className="ai-report-title">{report.headline}</h3><p className="ai-overview">{report.overview}</p><div className="ai-findings">{report.findings.map((v,i)=><article key={i}><h4>{v.title}</h4><p>{v.detail}</p><div className="ai-evidence">{v.evidenceIds.map(id=><button key={id} onClick={()=>openRecord(id)}>근거 · {records.find(r=>r.id===id)?.date??'기록'}</button>)}</div></article>)}</div>{report.limitations.length>0&&<div className="ai-report-notes"><h4>해석할 때 함께 볼 점</h4><ul>{report.limitations.map((v,i)=><li key={i}>{v}</li>)}</ul></div>}{report.questions.length>0&&<div className="ai-report-notes"><h4>다음 수업 전에 확인</h4><ul>{report.questions.map((v,i)=><li key={i}>{v}</li>)}</ul></div>}{report.quests.length>0&&<div className="ai-report-notes"><h4>선택 실천 과제</h4><ul>{report.quests.map((v,i)=><li key={i}>{v}</li>)}</ul></div>}</>:<p className="file-empty">일지를 업로드하면 읽기·진행 분석·수업 초안이 순서대로 준비돼요.</p>)}
 {tab==='body'&&<><BodyMap stats={stats} compact sourceLabel="저장된 실제 기록" onSource={date=>{const r=records.find(r=>r.date===date);if(r)setEditor(r);}}/><p className="record-help">전신·미분류는 신체 부위별 비중에서 제외해요. 자동 반영된 잠정 기록을 포함합니다.</p></>}
 {tab==='trend'&&<ActualTrend records={records}/>}
 <div hidden={tab!=='plan'}><SavedLessonPlan memberId={memberId} plan={plan} draft={report?.program??[]} fingerprint={analysis?.fingerprint??''} online={online} onEvidence={openRecord}/></div>
 </div><p className="record-help">AI 종합 의견은 최근 {analysis?.scopeLimit??120}개 운동 항목을 기준으로 해요. 통계·부위 분포에는 저장된 전체 기록을 표시해요. 자동 반영 수치는 트레이너 확인 전의 잠정 기록입니다.</p>
 <details className="ai-usage"><summary>무료 베타 · 이번 달 AI 이용량</summary><div><strong>예상 모델 원가 ${((usage.usedMicros??0)/1e6).toFixed(4)} / ${((usage.monthlyLimitMicros??1000000)/1e6).toFixed(2)}</strong><p>입력 {(usage.inputTokens??0).toLocaleString()} · 출력 {(usage.outputTokens??0).toLocaleString()} 토큰 · 요청 {usage.calls??0}회</p><p>하루 최대 30회. 저장된 결과 열람은 AI 호출 없이 제공해요. 실패·응답 미확인 요청도 한도에서 보수적으로 집계하며, 서버·저장소 비용은 위 원가에 포함되지 않아요.</p>{!!usage.reservedMicros&&<p>처리 중 비용 예약 ${((usage.reservedMicros??0)/1e6).toFixed(4)}</p>}</div></details>{error&&<p className="file-error" role="alert">{error}</p>}
 {editor&&<RecordEditor memberId={memberId} memberName={memberName} existing={editor} online={online} onClose={()=>setEditor(null)} onSaved={()=>setEditor(null)}/>}
 </section>;
}
function ActualTrend({records}:{records:WorkoutRecord[]}){
 const [metric,setMetric]=useState<'sets'|'volume'>('volume');const days=new Map<string,{date:string;sets:number;volume:number}>();for(const r of records){const d=days.get(r.date)??{date:r.date,sets:0,volume:0};d.sets+=r.sets.length;if(r.loadType==='weighted')d.volume+=r.sets.reduce((n,s)=>n+(s.kg??0)*s.reps,0);days.set(r.date,d);}const data=[...days.values()].sort((a,b)=>a.date.localeCompare(b.date)).slice(-20),max=Math.max(1,...data.map(d=>d[metric]))*1.15,x=(i:number)=>70+(data.length>1?i/(data.length-1):.5)*630,y=(v:number)=>235-v/max*195;
 return <><div className="saved-ai-tabs"><button aria-pressed={metric==='volume'} onClick={()=>setMetric('volume')}>기록 볼륨</button><button aria-pressed={metric==='sets'} onClick={()=>setMetric('sets')}>총세트</button></div><p className="record-help">최근 운동 날짜 20개 · {metric==='volume'?'kg·회 · 맨몸/중량 미상 제외':'세트'}</p>{!data.length?<p className="file-empty">아직 표시할 기록이 없어요.</p>:<><svg viewBox="0 0 770 290" className="actual-trend" role="img" aria-label="날짜별 운동 기록 선 그래프">{[0,.5,1].map(n=><g key={n}><line x1={70} x2={715} y1={y(n*max)} y2={y(n*max)} stroke="#e3eae5" strokeDasharray="4 6"/><text x={58} y={y(n*max)+4} textAnchor="end" fill="#6e8075" fontSize={12}>{Math.round(n*max).toLocaleString()}</text></g>)}<polyline points={data.map((d,i)=>`${x(i)},${y(d[metric])}`).join(' ')} fill="none" stroke="#4d7b62" strokeWidth={3}/>{data.map((d,i)=><g key={d.date}><circle cx={x(i)} cy={y(d[metric])} r={5} fill="white" stroke="#4d7b62" strokeWidth={3}><title>{d.date}: {d[metric].toLocaleString()}</title></circle>{(i===0||i===data.length-1)&&<><text x={x(i)} y={y(d[metric])-15} textAnchor="middle" fill="#365944" fontSize={13}>{d[metric].toLocaleString()}</text><text x={x(i)} y={268} textAnchor="middle" fill="#6e8075" fontSize={12}>{d.date}</text></>}</g>)}</svg><details><summary>날짜별 수치 모두 보기</summary><table className="ai-data-table"><thead><tr><th>날짜</th><th>세트</th><th>볼륨 (kg·회)</th></tr></thead><tbody>{data.map(d=><tr key={d.date}><td>{d.date}</td><td>{d.sets}</td><td>{d.volume.toLocaleString()}</td></tr>)}</tbody></table></details></>}<p className="record-help">운동 종류와 기구 구성이 다르면 볼륨만으로 발전이나 운동강도를 판단할 수 없어요.</p></>;
}
function SavedLessonPlan({memberId,plan,draft,fingerprint,online,onEvidence}:{memberId:string;plan:SavedPlan|null;draft:PlanRow[];fingerprint:string;online:boolean;onEvidence:(id:string)=>void}){
 const [rows,setRows]=useState<PlanRow[]>(plan?.program??draft),[reason,setReason]=useState(plan?.reason??''),[base,setBase]=useState(plan?.basedOn??fingerprint),[revision,setRevision]=useState(plan?.revision??0),[dirty,setDirty]=useState(false),[busy,setBusy]=useState(false),[message,setMessage]=useState('');
 useEffect(()=>{if(dirty)return;setRows(plan?.program??draft);setReason(plan?.reason??'');setBase(plan?.basedOn??fingerprint);setRevision(plan?.revision??0);},[plan,draft,fingerprint,dirty]);
 useEffect(()=>{if(!dirty)return;const f=(e:BeforeUnloadEvent)=>{e.preventDefault();e.returnValue='';};window.addEventListener('beforeunload',f);return()=>window.removeEventListener('beforeunload',f);},[dirty]);
 const changed=!!plan&&plan.revision!==revision;
 async function save(){if(busy)return;setBusy(true);setMessage('');try{await callAi({action:'savePlan',memberId,program:rows,reason,basedOn:base,revision});setDirty(false);setMessage('수업 계획을 저장했어요. AI 분석이 바뀌어도 이 계획은 유지돼요.');}catch(e){setMessage(aiMessage(e));}finally{setBusy(false);}}
 function edit(i:number,patch:Partial<PlanRow>){setRows(r=>r.map((v,j)=>i===j?{...v,...patch}:v));setDirty(true);setMessage('');}
 return <div className="saved-lesson"><div className="file-section-heading"><div><h3>{plan?'저장한 수업 계획':'AI가 준비한 수업 초안'}</h3><p>오늘 컨디션을 확인하고 수업 구성을 조정하세요.</p></div>{draft.length>0&&<button disabled={busy} onClick={()=>{if(dirty&&!window.confirm('작성 중인 내용을 새 AI 초안으로 바꿀까요?'))return;setRows(draft);setBase(fingerprint);setDirty(true);}}>최신 AI 초안 가져오기</button>}</div>{base!==fingerprint&&plan&&<p className="member-notice">기록 분석이 갱신됐어요. 기존 수업 계획은 그대로 유지했습니다.</p>}{changed&&<p className="file-error">다른 화면에서 저장한 계획이 있어요. 현재 입력은 유지됩니다. <button onClick={()=>{setDirty(false);setRevision(plan.revision);}}>저장된 최신 계획 불러오기</button></p>}
 {!rows.length&&<p className="file-empty">분석할 기록이 준비되면 근거가 있는 수업 초안이 표시돼요.</p>}
 {rows.map((r,i)=><article className="saved-lesson-row" key={i}><label className="field-label">운동 {i+1}<input value={r.exerciseName} maxLength={100} disabled={busy} onChange={e=>edit(i,{exerciseName:e.target.value})}/></label><div className="record-form-pair"><label className="field-label">세트<input type="number" min={1} max={8} value={r.sets} disabled={busy} onChange={e=>edit(i,{sets:+e.target.value})}/></label><label className="field-label">횟수<input maxLength={100} value={r.reps} disabled={busy} onChange={e=>edit(i,{reps:e.target.value})}/></label></div><label className="field-label">중량·강도 가이드<input maxLength={500} value={r.loadGuide} disabled={busy} onChange={e=>edit(i,{loadGuide:e.target.value})}/></label><p className="record-help">구성 근거: {r.reason}</p><div className="saved-file-actions"><button onClick={()=>onEvidence(r.recordId)}>근거 기록 보기</button><button disabled={busy} onClick={()=>{setRows(rows.filter((_,j)=>j!==i));setDirty(true);}}>이 운동 제외</button></div></article>)}
 <label className="field-label">수정 이유 · 다음 수업 메모<textarea maxLength={1000} rows={3} value={reason} disabled={busy} onChange={e=>{setReason(e.target.value);setDirty(true);}} placeholder="예: 오늘은 수면이 부족해서 세트 수를 줄였어요"/></label><div className="dialog-footer"><span>{dirty?'저장하지 않은 변경이 있어요':plan?'트레이너가 저장한 계획':'아직 저장하지 않은 AI 초안'}</span><button className="primary" disabled={busy||!online||changed||(!dirty&&!!plan)||!rows.length} onClick={()=>void save()}>{busy?'저장 중…':'내 수업 계획으로 저장'}</button></div>{message&&<p role="status">{message}</p>}</div>;
}
