"use client";
import {memberFolderLabels,memberStatus,membersInFolder,type MemberFolder,type MemberStatus} from '../lib/member-status';
import type {DisplayPreferences} from '../lib/display-preferences';
import {MemberActions} from './member-actions';
import {Icon} from './icons';
import type {Member} from '../lib/members';
export function MemberDirectory({members,search,onSearch,onOpen,onCreate,canCreate,preferences,onPreferences,onEdit,onDelete,onUpload,onStatus,online,folder,onFolder}:{folder:MemberFolder;onFolder:(folder:MemberFolder)=>void;onStatus:(member:Member,status:MemberStatus)=>void;onEdit:(member:Member)=>void;onDelete:(member:Member)=>void;onUpload:(member:Member)=>void;online:boolean;members:Member[];search:string;onSearch:(value:string)=>void;onOpen:(id:string)=>void;onCreate:()=>void;canCreate:boolean;preferences:DisplayPreferences;onPreferences:(patch:Partial<DisplayPreferences>)=>void}){
 const sort=preferences.sort,folderMembers=membersInFolder(members,folder);
 function changeFolder(value:MemberFolder){onFolder(value);onSearch('');}
 const visible=folderMembers.filter(m=>m.name.toLocaleLowerCase().includes(search.trim().toLocaleLowerCase()));
 if(sort==='name')visible.sort((a,b)=>a.name.localeCompare(b.name,'ko'));
 return <section className={"member-directory cards-"+preferences.cardSize} aria-label="회원 홈">
  <div className="directory-heading"><div><h1>내 회원 <span>{folderMembers.length}</span></h1></div><div className="directory-tools"><div className="segmented directory-size" aria-label="홈 회원 카드 크기">{[['small','작게'],['medium','보통'],['large','크게']].map(([value,label])=><button key={value} className={preferences.cardSize===value?'selected':''} aria-pressed={preferences.cardSize===value} onClick={()=>onPreferences({cardSize:value as DisplayPreferences['cardSize']})}>{label}</button>)}</div><label className="directory-search"><Icon name="search" size={17}/><input aria-label="홈 회원 검색" placeholder="회원 이름 검색" value={search} onChange={e=>onSearch(e.target.value)}/>{search&&<button className="icon-button" aria-label="회원 검색 지우기" onClick={()=>onSearch('')}><Icon name="close" size={14}/></button>}</label><select aria-label="회원 정렬" value={sort} onChange={e=>onPreferences({sort:e.target.value as DisplayPreferences['sort']})}><option value="recent">최근 등록순</option><option value="name">이름순</option></select></div></div>
  <div className="directory-folders" role="group" aria-label="회원 보관함">{(['active','hidden','ended','all'] as MemberFolder[]).map(value=><button key={value} aria-pressed={folder===value} onClick={()=>changeFolder(value)}><Icon name={value==='hidden'?'eye-off':value==='ended'?'folder':'users'} size={16}/>{memberFolderLabels[value]}<span>{membersInFolder(members,value).length}</span></button>)}</div>
  {folder!=='active'&&folder!=='all'&&<p className="directory-folder-note">{folder==='hidden'?'기본 목록에서 숨긴 회원입니다.':'계약이 종료된 회원을 모아두는 보관함입니다.'} 기록은 그대로 보관되며, 카드 메뉴에서 관리 중으로 복원할 수 있어요.</p>}
  <div className="directory-grid">
   {(folder==='active'||folder==='all')&&<button className="directory-create" disabled={!canCreate} onClick={onCreate}><span><Icon name="plus" size={28}/></span><strong>새 회원 등록</strong></button>}
   {visible.map((member,index)=><article className="directory-card" key={member.id}><button className="directory-card-open" onClick={()=>onOpen(member.id)} aria-label={`${member.name} 기록 열기`}/><div className={'directory-cover tone-'+index%3}><span className="directory-initial">{member.name.slice(0,1)}</span><span className="directory-paper"><Icon name="file" size={29}/><i/><i/><i/></span><span className="directory-enter"><Icon name="arrow" size={19}/></span></div><div className="directory-card-copy"><div className="directory-card-title"><h2>{member.name}</h2><MemberActions member={member} card available={canCreate} online={online} onOpen={()=>onOpen(member.id)} onEdit={()=>onEdit(member)} onDelete={()=>onDelete(member)} onUpload={()=>onUpload(member)} onStatus={status=>onStatus(member,status)}/></div><p>{member.goal||'목표 미설정'}</p>{memberStatus(member.status)!=='active'&&<span className="directory-status">{memberFolderLabels[memberStatus(member.status)]}</span>}<div className="directory-card-meta"><span><Icon name="file" size={13}/> 일지 {member.fileCount}개</span><span>운동 항목 {member.recordCount}개</span></div>{member.pending&&<small>저장 중…</small>}</div></article>)}
  </div>
  {!visible.length&&<div className="directory-empty"><h2>{search.trim()?'이 보관함에 검색한 회원이 없어요':folder==='hidden'?'숨긴 회원이 없어요':folder==='ended'?'계약이 종료된 회원이 없어요':'관리 중인 회원이 없어요'}</h2><p>{search.trim()?'이름을 다시 확인하거나 전체 보관함에서 찾아보세요.':folder==='hidden'||folder==='ended'?'회원 카드의 ··· 메뉴에서 이 보관함으로 이동할 수 있어요.':members.length?'다른 보관함의 회원을 복원하거나 새 회원을 등록해주세요.':'첫 회원을 등록하면 운동일지를 업로드하고 분석을 시작할 수 있어요.'}</p>{search.trim()&&<button onClick={()=>onSearch('')}>검색 지우기</button>}{folder!=='all'&&members.length>0&&<button onClick={()=>onFolder('all')}>전체 회원 보기</button>}</div>}

 </section>;
}
