"use client";
import {useState} from 'react';
import {lessonDates,lessonProgramSummary,splitPatternCandidate} from '../lib/lesson-program-summary';
import type {SourceRow} from './analysis-source';
import type {SessionNote} from '../lib/session-notes';
import {formatWorkoutSet} from '../lib/workout-measurements';
export function recentLessonDates(rows:SourceRow[],today:string){return lessonDates(rows,today).slice(0,2);}
export function PreviousLessons({rows,notes,today,loaded,onEdit,onNext}:{rows:SourceRow[];notes:SessionNote[];today:string;loaded:boolean;onEdit:(id:string)=>void;onNext:()=>void}){
 const [page,setPage]=useState(0);const allDates=lessonDates(rows,today),currentPage=Math.min(page,Math.max(0,Math.ceil(allDates.length/2)-1)),dates=allDates.slice(currentPage*2,currentPage*2+2),pattern=splitPatternCandidate(rows,today);
 return <section className="live-pane previous-lessons" aria-label="이전 수업"><div className="pane-body"><header className="previous-lessons-heading"><div><h2>최근 수업 한눈에 보기</h2><p>부위별 운동 구성을 훑고, 필요한 기록을 눌러 확인하세요.</p></div><button onClick={onNext}>다음 수업 준비 →</button></header>{loaded&&allDates.length>0&&<><aside className="lesson-split-overview" aria-label="분할 패턴 요약"><strong>{pattern?`${pattern.count}분할 패턴 후보`:'분할 패턴 확인 중'}</strong><p>{pattern?pattern.sequence.join(' → '):'부위 구성을 아래에 표시했어요. 2·3·4·5분할은 같은 부위 순서가 두 번 이상 반복될 때 후보로 표시합니다.'}</p>{pattern&&<small>{pattern.from} ~ {pattern.to} · 부위 순서 2회 반복 기준. 트레이너가 정한 분할 계획과는 다를 수 있어요.</small>}</aside><nav className="previous-lessons-pagination" aria-label="이전 수업 날짜 탐색"><button disabled={(currentPage+1)*2>=allDates.length} onClick={()=>setPage(currentPage+1)}>← 더 이전 수업</button><span>{currentPage*2+1}–{Math.min(currentPage*2+2,allDates.length)} / {allDates.length}개 수업 날짜</span><button disabled={currentPage===0} onClick={()=>setPage(currentPage-1)}>최근 수업 →</button></nav></>}{!loaded?<p role="status">수업 기록을 불러오고 있어요.</p>:!dates.length?<p className="empty-state">날짜가 확인된 이전 수업이 아직 없어요. 기록 수정에서 수업 날짜를 확인해주세요.</p>:dates.map((date,index)=>{const exercises=rows.filter(row=>row.input.date===date),note=notes.find(note=>note.date===date)?.text,program=lessonProgramSummary(exercises);return <article className="previous-lesson" key={date}><header><div><small>{currentPage===0?(index===0?'가장 최근 수업':'그 이전 수업'):'이전 수업'}</small><h3>{date}</h3></div><span>운동 {exercises.length}개</span></header><div className="lesson-program-summary"><strong>{program.title}</strong><dl>{program.groups.map(group=><div key={group.part}><dt>{group.part==='미분류'?'부위 확인 필요':group.part}</dt><dd>{group.names.join(' · ')}</dd></div>)}</dl>{program.uncertain&&<small>확인이 필요한 판독 내용이 포함되어 있어요.</small>}</div>{note&&<p className="previous-lesson-note"><strong>수업 메모</strong>{note}</p>}<ol>{exercises.map(row=><li key={row.id}><button onClick={()=>onEdit(row.id)} aria-label={`${date} ${row.input.exerciseName||row.input.rawName} 기록 수정`}><span><strong>{row.input.exerciseName||row.input.rawName||'운동명 확인 필요'}</strong>{row.review==='needs-review'&&<small className="previous-lesson-review">판독 확인 필요</small>}</span><span className="previous-lesson-dose">{row.input.sets.length?`${row.input.sets.length}${row.input.measurementType&&row.input.measurementType!=='repetitions'?'구간':'세트'} · ${row.input.sets.map(set=>formatWorkoutSet(row.input,set)).join(' / ')}`:'세트·횟수 미기록'}</span></button>{row.input.trainerNote&&<p>{row.input.trainerNote}</p>}</li>)}</ol></article>;})}<p className="previous-lessons-footnote">원본에 기록된 내용입니다. 확인이 필요한 운동은 눌러서 수정할 수 있어요.</p></div></section>;
}
