"use client";
import {cardioDistribution,isCardioWorkout} from '../lib/cardio-distribution';
import {measurementLabels} from '../lib/workout-measurements';
import type {WorkoutRecord} from '../lib/workout-records';
import {formatWorkoutSet,measurementType} from '../lib/workout-measurements';
import {trainingGoalTitle,TRAINING_PARTS,progressStats,type SavedTrainingGoal} from '../lib/training-goals';
import {allocation,exerciseGroups,performanceDays,performanceLabels,weekSets,type PerformanceMetric} from '../lib/progress-analysis';
import {WorkoutSelect} from './workout-select';
import {BodyMap} from './body-map';
import {bodyStats} from './member-analysis';
import {ChartRecordHover} from './chart-record-hover';
const fmt=(n:number|null)=>n===null?'—':n.toLocaleString('ko-KR',{maximumFractionDigits:1});
type Props={records:WorkoutRecord[];goal:SavedTrainingGoal|null;onGoal:()=>void;onEvidence:(id:string)=>void;onTrend:(key:string,metric?:PerformanceMetric)=>void};
import {RecordLines} from './workout-record-lines';

export function BodyDistribution({records,goal,onEvidence,onTrend,part,onPart}:{part:string;onPart:(part:string)=>void;records:WorkoutRecord[];goal:SavedTrainingGoal|null;onEvidence:(id:string)=>void;onTrend:(key:string,metric?:PerformanceMetric)=>void}){
 const cardio=cardioDistribution(records),strength=records.filter(r=>measurementType(r)==='repetitions'&&!isCardioWorkout(r)),chosen=part||TRAINING_PARTS.find(p=>strength.some(r=>r.bodyPart===p))||'하체';
 const selected=strength.filter(r=>r.bodyPart===chosen),stats=progressStats(selected),share=allocation(strength,goal,chosen),weeks=weekSets(selected),groups=exerciseGroups(selected),max=Math.max(1,...weeks.map(([,n])=>n));
 if(chosen==='유산소')return <div className="pa-details"><BodyMap stats={bodyStats(strength)} cardio={cardio} sourceLabel="선택 기간의 운동 기록" hideDetails onPartSelect={onPart} selectedPart={chosen} onSource={()=>{}}/><section className="pa-section"><div className="pa-heading"><h3>유산소</h3><span>근육별 세트 비중과 별도 집계</span></div><div className="pa-kpis"><div><span>기록된 시간</span><strong>{fmt(cardio.seconds===null?null:cardio.seconds/60)}<small>분</small></strong></div><div><span>수행 구간</span><strong>{cardio.segments}<small>구간</small></strong></div><div><span>훈련한 수업일</span><strong>{cardio.days}<small>일</small></strong></div></div>{!!cardio.missingTime&&<p className="record-help">시간 미기록 {cardio.missingTime}구간 · 시간 합계에서 제외</p>}<p className="record-help">운동·회복 구간 중 기록된 시간 합계. 구간 수는 완료 라운드 수와 다름.</p></section><section className="pa-section"><h3>운동별 구성</h3>{exerciseGroups(cardio.records).map(g=><details className="pa-exercise" key={g.key}><summary><span><strong>{g.name}</strong><small>{g.records.reduce((n,r)=>n+r.sets.length,0)}구간 · {g.sessionDays}일</small></span></summary><button className="pa-link" onClick={()=>onTrend(g.key,g.kind==='repetitions'?'reps':g.kind==='distance'?'distance':'duration')}>이 운동의 변화 보기 →</button><RecordLines records={g.records} onEvidence={onEvidence}/></details>)}{!cardio.records.length&&<p className="record-help">선택 기간에 유산소 기록이 없어요.</p>}</section></div>;
 return <div className="pa-details"><BodyMap cardio={cardio} stats={bodyStats(strength)} sourceLabel="선택 기간 · 중량·횟수 기록" hideDetails onPartSelect={onPart} selectedPart={chosen} onSource={()=>{}}/>
 <section className="pa-section"><div className="pa-heading"><h3>{chosen}</h3><span>{share.context}</span></div><div className="pa-kpis"><div><span>목표 / 실제 비중</span><strong>{fmt(share.target)} / {fmt(share.actual)}<small>%</small></strong></div><div><span>총 세트</span><strong>{stats.sets}<small>세트</small></strong></div><div><span>훈련한 수업일</span><strong>{stats.days}<small>일</small></strong></div></div>
 {share.target!==null&&share.actual!==null&&<p className="pa-comment">목표 대비 {Math.abs(share.actual-share.target)<.1?'같은 비중이에요.':`${fmt(Math.abs(share.actual-share.target))}%p ${share.actual>share.target?'높아요':'낮아요'}.`} 회원의 반응과 의도한 조정을 함께 확인해주세요.</p>}
 <h4 title="월요일 시작 · 기간 양끝 주는 일부 날짜만 포함">주별 세트 배분</h4>{weeks.length?<div className="pa-weeks">{weeks.map(([date,n])=><div key={date}><span>{date.slice(5)} 주</span><div><i style={{width:n/max*100+'%'}}/></div><strong>{n}세트</strong></div>)}</div>:<p className="record-help">선택 기간에 이 부위의 중량·횟수 기록이 없어요.</p>}
 </section><section className="pa-section"><h3>운동별 구성</h3>{groups.map(g=><details className="pa-exercise" key={g.key}><summary><span><strong>{g.name}</strong><small>{g.records.reduce((n,r)=>n+r.sets.length,0)}세트 · {g.sessionDays}일</small></span><span>{formatWorkoutSet(g.records.at(-1)!,g.records.at(-1)!.sets.at(-1)!)}<small>최근 기록의 마지막 세트</small></span></summary><button className="pa-link" onClick={()=>onTrend(g.key)}>이 운동의 변화 보기 →</button><RecordLines records={g.records} onEvidence={onEvidence}/></details>)}</section></div>;
}
export function PerformanceTrend({records,selection,onSelect,onEvidence,goal,requested,onMetric}:{requested:PerformanceMetric;onMetric:(metric:PerformanceMetric)=>void;records:WorkoutRecord[];selection:string;onSelect:(key:string)=>void;onEvidence:(id:string)=>void;goal:SavedTrainingGoal|null}){
 const groups=exerciseGroups(records),group=groups.find(g=>g.key===selection)??groups[0];
 if(!group)return <p className="file-empty">선택 기간에 비교할 운동 기록이 없어요.</p>;
 const cardio=group.kind!=='repetitions',sided=group.records.some(r=>r.sets.some(s=>s.leftReps!==undefined));
 const options:PerformanceMetric[]=group.kind==='incline_speed_time'?['duration','incline','speed']:cardio?[...(group.kind!=='duration'?['distance' as const]:[]),...(group.kind!=='distance'?['duration' as const]:[])]:[...(group.hasWeighted?['volume' as const,'kg' as const]:[]),'sets','reps',...(sided?['left' as const,'right' as const]:[])];
 const metric=options.includes(requested)?requested:options[0],days=performanceDays(group.records,metric),min=Math.min(0,...days.map(d=>d.value??0))*1.15,max=Math.max(1,...days.map(d=>d.value??0))*1.15,x=(i:number)=>60+(days.length>1?i/(days.length-1):.5)*560,y=(v:number)=>220-(v-min)/(max-min)*175;
 let path='';let gap=true;days.forEach((d,i)=>{if(d.value===null){gap=true;return;}path+=`${gap?'M':'L'}${x(i)} ${y(d.value)} `;gap=false;});
 const goalIndex=goal?.startMode==='date'?days.findIndex(d=>d.date>=goal.startDate):-1;
 const first=days.find(d=>d.value!==null),last=days.findLast(d=>d.value!==null),delta=first&&last&&first!==last?last.value!-first.value!:null;
 return <div className="pa-details"><div className="pa-select-label"><span>비교할 운동</span><WorkoutSelect label="비교할 운동" value={group.key} onChange={onSelect} options={groups.map(g=>({value:g.key,label:`${g.name} · ${g.part} · ${g.loadTypes.length>1?'조건 혼합':g.hasWeighted?'중량':g.load==='bodyweight'?'맨몸':g.kind==='repetitions'?'중량 미상':measurementLabels[g.kind]} (${g.sessionDays}회)`}))}/></div><div className="pa-part-picker" aria-label="수행 지표">{options.map(m=><button key={m} aria-pressed={metric===m} onClick={()=>onMetric(m)}>{performanceLabels[m][0]}</button>)}</div>
 <div className="pa-kpis"><div><span>첫 기록 · {first?.date??'—'}</span><strong>{fmt(first?.value??null)}<small>{performanceLabels[metric][1]}</small></strong></div><div><span>최근 · {last?.date??'—'}</span><strong>{fmt(last?.value??null)}<small>{performanceLabels[metric][1]}</small></strong></div><div><span>기록 차이</span><strong>{delta!==null&&delta>0?'+':''}{fmt(delta)}<small>{performanceLabels[metric][1]}</small></strong></div></div>
 <ChartRecordHover metric="volume" valueLabel={performanceLabels[metric][0]} valueUnit={performanceLabels[metric][1]} points={days.map((d,i)=>({date:d.date,sets:0,volume:d.value,x:x(i)/680*100,y:d.value===null?null:y(d.value)/266*100}))}><svg className="pa-chart" viewBox="0 0 680 266" role="img" aria-label={`${group.name} ${performanceLabels[metric][0]} 변화`}>{[0,.5,1].map(v=><g key={v}><line x1="55" x2="635" y1={y(min+v*(max-min))} y2={y(min+v*(max-min))} stroke="#e2e8de"/><text x="45" y={y(min+v*(max-min))+4} textAnchor="end" fill="#7e897b" fontSize="11">{fmt(Math.round(min+v*(max-min)))}</text></g>)}{goalIndex>0&&<g><line x1={(x(goalIndex-1)+x(goalIndex))/2} x2={(x(goalIndex-1)+x(goalIndex))/2} y1="25" y2="220" stroke="#a2b494" strokeDasharray="4 4"/><text x={(x(goalIndex-1)+x(goalIndex))/2} y="18" textAnchor="middle" fontSize="11" fill="#708074">목표 적용</text></g>}<path d={path} stroke="#355d43" strokeWidth="2.5" fill="none"/>{days.map((d,i)=><g key={d.date}>{d.value!==null&&<circle cx={x(i)} cy={y(d.value)} r="4" stroke="#355d43" fill="white" strokeWidth="2"/>}</g>)}</svg></ChartRecordHover>
 <details className="analysis-calculation-details"><summary>비교 조건</summary><p className="record-help">{days.length<2?'비교 가능한 다른 날짜의 기록 필요. ':''}운동명·부위·기록 방식 기준으로 묶음. 중량·맨몸 기록 함께 표시. 볼륨·최고 중량은 숫자 중량이 기록된 세트만 집계. 중량 미기록은 0으로 처리하지 않음. 기구·자세·가동 범위는 원본·메모로 확인. {metric==='left'||metric==='right'?'좌우가 기록된 세트의 횟수만 합산.':''}{metric==='kg'?'날짜별 최고 기록 중량.':''}{group.kind==='incline_speed_time'?'경사·속도는 구간 시간으로 가중 평균. 경사·속도·구간 구성과 휴식이 같은 기록끼리 수행 비교.':cardio?'거리·시간 합계: 수행 구간 수와 조건에 따라 차이 발생.':''}</p></details>
 {goal?.startMode==='date'&&days.some(d=>d.date>=goal.startDate)&&days.some(d=>d.date<goal.startDate)&&<p className="pa-comment">{goal.startDate} 목표 적용 시작 · {trainingGoalTitle(goal)}</p>}
 <section className="pa-section"><h3>수업별 수행</h3><RecordLines records={group.records} onEvidence={onEvidence}/></section></div>;
}
export {GoalEvaluation} from './goal-evaluation';
