"use client";
import {useEffect,useId,useRef,useState} from 'react';
import {Icon} from './icons';
export function ReportOutline(){
 const id=useId(),rail=useRef<HTMLDivElement>(null),trigger=useRef<HTMLButtonElement>(null),menu=useRef<HTMLDivElement>(null),[items,setItems]=useState<HTMLElement[]>([]),[active,setActive]=useState(0),[position,setPosition]=useState({left:0,top:0}),timer=useRef<ReturnType<typeof setTimeout>|null>(null);
 useEffect(()=>{const section=rail.current?.closest('.coaching-journey'),scroll=section?.closest('.journey-scroll');if(!section||!scroll)return;const headings=Array.from(section.querySelectorAll<HTMLElement>('h3')).filter(h=>!h.closest('dialog'));setItems(headings);function sync(){const top=scroll!.getBoundingClientRect().top+90;let current=0;headings.forEach((h,i)=>{if(h.getBoundingClientRect().top<=top)current=i;});if(scroll!.scrollHeight-scroll!.scrollTop-scroll!.clientHeight<8)current=Math.max(0,headings.length-1);setActive(current);}sync();scroll.addEventListener('scroll',sync,{passive:true});return()=>{scroll.removeEventListener('scroll',sync);if(timer.current)clearTimeout(timer.current);};},[]);
 function show(){if(timer.current)clearTimeout(timer.current);const r=trigger.current?.getBoundingClientRect();if(r){setPosition({left:Math.max(12,r.left-194),top:Math.max(12,Math.min(r.top-64,window.innerHeight-292))});menu.current?.showPopover();}}
 function leave(){timer.current=setTimeout(()=>menu.current?.hidePopover(),180);}
 function jump(h:HTMLElement){const scroll=h.closest('.journey-scroll');if(!scroll)return;const top=scroll.scrollTop+h.getBoundingClientRect().top-scroll.getBoundingClientRect().top-24;menu.current?.hidePopover();trigger.current?.focus({preventScroll:true});scroll.scrollTo({top,behavior:matchMedia('(prefers-reduced-motion: reduce)').matches?'instant':'smooth'});}
 return <div ref={rail} className="report-outline" onPointerLeave={leave} onKeyDown={e=>{if(e.key==='Escape'){menu.current?.hidePopover();trigger.current?.focus({preventScroll:true});}}}>{items.length>1&&<><button ref={trigger} type="button" className="report-outline-trigger" aria-label="회원 변화 목차" aria-controls={id} onPointerEnter={show} onClick={show} onKeyDown={e=>{if(e.key==='ArrowDown'){e.preventDefault();show();menu.current?.querySelector<HTMLButtonElement>('button')?.focus();}}}><Icon name="sort" size={18}/><span className="sr-only">현재 {items[active]?.textContent}</span></button><nav id={id} ref={menu} popover="auto" className="report-outline-menu" style={position} aria-label="회원 변화 목차" onPointerEnter={()=>{if(timer.current)clearTimeout(timer.current);}}><small>목차</small>{items.map((h,i)=><button type="button" key={i} aria-current={active===i?'location':undefined} onClick={()=>jump(h)}>{i+1}. {h.textContent}</button>)}</nav></>}</div>;
}
