"use client";
import {useEffect,useRef,useState} from 'react';
import {Icon} from './icons';
import {RecordEditor} from './member-records';
import {readMemberFile,type MemberFile} from '../lib/member-files';
import {aiMessage,callAi,listenImports,type SavedImport,type ImportRow} from '../lib/server-ai';
export function SavedRecordImport({file,memberId,memberName,online,onClose}:{file:MemberFile;memberId:string;memberName:string;online:boolean;onClose:()=>void}){
 const ref=useRef<HTMLDialogElement>(null),working=useRef(false),alive=useRef(true);
 const [data,setData]=useState<SavedImport|null>(null),[loaded,setLoaded]=useState(false),[error,setError]=useState(''),[busy,setBusy]=useState(false),[all,setAll]=useState(false),[year,setYear]=useState(''),[editor,setEditor]=useState<{row:ImportRow;revision:number;blob:Blob}|null>(null);
 useEffect(()=>{alive.current=true;const previous=document.activeElement as HTMLElement|null;ref.current?.showModal();const off=listenImports(memberId,rows=>{setData(rows.find(r=>r.id===file.id)??null);setLoaded(true);},e=>setError(aiMessage(e)));return()=>{alive.current=false;off();previous?.focus();};},[memberId,file.id]);
 async function act(payload:Record<string,unknown>){if(working.current||!online)return;working.current=true;setBusy(true);setError('');try{await callAi({memberId,fileId:file.id,...payload});}catch(e){if(alive.current)setError(aiMessage(e));}finally{working.current=false;if(alive.current)setBusy(false);}}
 async function open(row:ImportRow){if(!data||busy)return;setBusy(true);setError('');try{const blob=await readMemberFile(memberId,file.id,file.contentType);if(alive.current)setEditor({row,revision:data.revision,blob});}catch(e){setError(aiMessage(e));}finally{if(alive.current)setBusy(false);}}
 const [now,setNow]=useState(Date.now());useEffect(()=>{const timer=setInterval(()=>setNow(Date.now()),30000);return()=>clearInterval(timer);},[]);
 const pending=data?.rows.filter(r=>r.review==='needs-review')??[],visible=all?data?.rows??[]:pending;
 const stale=data?.status==='processing'&&!!data.startedAt&&now-data.startedAt.toMillis()>180000;
 return <><dialog className="ai-import-dialog" ref={ref} onCancel={e=>{e.preventDefault();if(!busy)onClose();}}><div className="record-editor-heading"><div><small>{memberName} · 저장된 판독 결과</small><h2>필요한 부분만 확인하세요</h2></div><button className="icon-button" aria-label="판독 화면 닫기" disabled={busy} onClick={onClose}><Icon name="close"/></button></div><div className="ai-import-body"><div className="ai-source-card"><Icon name="file"/><strong>{file.name}</strong></div>
 {!loaded&&<p role="status">저장된 결과를 불러오고 있어요.</p>}
 {loaded&&!data&&<><p>이 파일은 아직 자동 판독 전이에요. 한 번 읽은 결과는 저장해 다시 사용해요.</p><button className="primary" disabled={busy||!online} onClick={()=>void act({action:'read'})}>{busy?'읽는 중…':'처음 판독하기'}</button></>}
 {data?.status==='processing'&&<div className="ai-reading" role="status"><span className="ai-reading-dot"/><h3>기록을 읽고 점검하고 있어요</h3><p>닫아도 서버에서 계속 처리해요. 끝나면 진행 분석과 수업 초안까지 준비합니다.</p></div>}
 {(data?.status==='error'||data?.status==='limited'||stale)&&<div className="ai-review-issues"><p>{data?.error||'처리가 지연되고 있어요. 다시 시도할 수 있어요.'}</p><button disabled={busy||!online} onClick={()=>void act({action:'read',retry:true})}>판독 다시 시도</button><small>실제 AI 재호출은 이용량에 포함됩니다.</small></div>}
 {data?.status==='ready'&&<><div className="ai-result-heading"><div><strong>자동 반영 {data.rows.filter(r=>r.review==='auto').length}개 · 확인 필요 {pending.length}개</strong><p>자동 반영은 AI와 형식 점검을 통과한 잠정 기록이에요. 모든 기록을 열어 수정할 수 있어요.</p></div></div>
 {pending.length>0&&<div className="ai-bulk-controls"><label className="field-label">빠진 연도 한 번에 입력<input type="number" min={1900} max={2100} value={year} placeholder="예: 2026" onChange={e=>setYear(e.target.value)}/></label><button disabled={busy||!online||!/^\d{4}$/.test(year)||+year<1900||+year>2100} onClick={()=>void act({action:'review',operation:'year',year:+year,revision:data.revision})}>연도 적용</button>{!data.memberConfirmed&&pending.some(r=>r.issues.some(s=>s.includes('이름')))&&<button disabled={busy||!online} onClick={()=>void act({action:'review',operation:'member',revision:data.revision})}>{memberName} 회원의 일지 맞아요</button>}<small>연도·회원 확인은 저장된 판독을 수정하므로 AI를 다시 호출하지 않아요. 분석 대상이 달라지면 종합 의견만 갱신돼요.</small></div>}
 <div className="saved-ai-tabs"><button aria-pressed={!all} onClick={()=>setAll(false)}>확인 필요 {pending.length}</button><button aria-pressed={all} onClick={()=>setAll(true)}>전체 기록 {data.rows.length}</button></div>
 {!visible.length&&<p className="file-empty">개별 확인이 필요한 기록이 없어요. 진행 분석을 바로 볼 수 있어요.</p>}
 <ol className="ai-draft-list">{visible.map(row=><li key={row.id}><div><small>{row.input.sourcePage}쪽 · {row.input.date||'날짜 확인 필요'} · {{auto:'자동 반영',confirmed:'트레이너 확인',ignored:'분석 제외','needs-review':'확인 필요'}[row.review]}</small><h3>{row.input.exerciseName||row.input.rawName||'운동명 확인 필요'}</h3><p>{row.input.sets.length}세트 · {row.input.bodyPart}</p>{row.issues.map((s,i)=><p className="ai-draft-warning" key={i}>{s}</p>)}</div><div className="saved-file-actions"><button disabled={busy||!online} onClick={()=>void open(row)}>원본·수정</button>{row.review==='needs-review'&&<button disabled={busy||!online} onClick={()=>void act({action:'review',operation:'ignore',rowId:row.id,revision:data.revision})}>분석에서 제외</button>}</div></li>)}</ol>
 {data.unparsed.length>0&&<div className="ai-review-issues"><strong>별도 확인 {data.unparsed.length}개</strong><p>거리·시간 등 세트 기록으로 변환하지 않은 원문이에요.</p><ul>{data.unparsed.map((v,i)=><li key={i}>{v.page}쪽 · {v.text} — {v.reason}</li>)}</ul></div>}
 <p className="record-help">닫아도 판독 결과와 수정 사항이 남아요. 같은 파일을 다시 열 때 AI 사용량은 늘지 않아요.</p></>}
 {error&&<p className="file-error" role="alert">{error}</p>}<div className="dialog-footer"><button disabled={busy} onClick={onClose}>닫고 분석 보기</button></div></div></dialog>
 {editor&&<RecordEditor key={editor.row.id} memberId={memberId} memberName={memberName} initial={editor.row.input} sourceBlob={editor.blob} issues={editor.row.issues} online={online} onClose={()=>setEditor(null)} onSaved={()=>setEditor(null)} onCommit={async input=>{await callAi({action:'review',memberId,fileId:file.id,operation:'row',rowId:editor.row.id,revision:editor.revision,input,reason:input.notes});}}/>}</>;
}
