"use client";
import {useEffect,useRef,useState} from 'react';
import {AccountControl,useTrainer} from './auth-gate';
import {Icon} from './icons';
import {defaultDisplayPreferences,type DisplayPreferences} from '../lib/display-preferences';
import {listenUsage,serverAiEnabled,aiMessage,type AiUsage} from '../lib/server-ai';
const tabs=[['display','화면 설정','panel'],['account','계정','users'],['usage','AI 이용량','spark'],['feedback','개선 의견','edit']] as const;
export function SettingsDialog({open,onClose,preferences,onChange,saveError,beforeLogout}:{open:boolean;onClose:()=>void;preferences:DisplayPreferences;onChange:(patch:Partial<DisplayPreferences>)=>void;saveError:string;beforeLogout:()=>boolean}){
 const user=useTrainer(),dialog=useRef<HTMLDialogElement>(null);const [tab,setTab]=useState<string>('display'),[usage,setUsage]=useState<AiUsage|null>(null),[usageError,setUsageError]=useState(''),[topic,setTopic]=useState('회원 홈'),[message,setMessage]=useState(''),[contact,setContact]=useState(user.email||''),[copyStatus,setCopyStatus]=useState('');
 useEffect(()=>{if(!open){dialog.current?.close();return;}const previous=document.activeElement as HTMLElement|null;dialog.current?.showModal();return()=>{dialog.current?.close();previous?.focus();};},[open]);
 useEffect(()=>{if(!open||tab!=='usage'||!serverAiEnabled)return;setUsage(null);setUsageError('');try{return listenUsage(setUsage,e=>setUsageError(aiMessage(e)));}catch(e){setUsageError(aiMessage(e));}},[open,tab,user.uid]);
 const feedback=`문의 화면: ${topic}\n\n${message.trim()}\n\n답장 받을 연락처: ${contact.trim()||'미입력'}`;
 async function copy(){try{await navigator.clipboard.writeText(feedback);setCopyStatus('의견을 복사했어요.');}catch{setCopyStatus('복사하지 못했어요. 입력한 내용을 직접 선택해 복사해주세요.');}}
 return <dialog ref={dialog} className="settings-dialog" aria-labelledby="settings-title" onCancel={e=>{e.preventDefault();onClose();}}><header className="settings-header"><h2 id="settings-title">설정</h2><button className="icon-button" aria-label="설정 닫기" onClick={onClose}><Icon name="close" size={22}/></button></header><div className="settings-layout"><nav className="settings-nav" aria-label="설정 메뉴">{tabs.map(([id,label,icon])=><button key={id} aria-current={tab===id?'page':undefined} onClick={()=>setTab(id)}><Icon name={icon} size={19}/><span>{label}</span></button>)}</nav><div className="settings-content">
 {tab==='display'&&<section><h3>화면 설정</h3><div className="settings-row"><div><strong>회원 카드 크기</strong></div><div className="segmented" aria-label="설정 회원 카드 크기">{[['small','작게'],['medium','보통'],['large','크게']].map(([value,label])=><button key={value} className={preferences.cardSize===value?'selected':''} aria-pressed={preferences.cardSize===value} onClick={()=>onChange({cardSize:value as DisplayPreferences['cardSize']})}>{label}</button>)}</div></div><div className={'settings-card-preview preview-'+preferences.cardSize} aria-label="카드 크기 미리보기"><Icon name="users" size={23}/><span>회원 카드<small>이름 · 운동 목표 · 기록 수</small></span></div><div className="settings-row"><div><strong>회원 정렬</strong></div><select aria-label="설정 회원 정렬" value={preferences.sort} onChange={e=>onChange({sort:e.target.value as DisplayPreferences['sort']})}><option value="recent">최근 등록순</option><option value="name">이름순</option></select></div><div className="settings-row"><div><strong>작업실 기본 보기</strong><p>새로 여는 회원 작업실에 적용돼요.</p></div><div className="segmented" aria-label="기본 작업실 보기">{([2,3] as const).map(mode=><button key={mode} className={preferences.viewMode===mode?'selected':''} aria-pressed={preferences.viewMode===mode} onClick={()=>onChange({viewMode:mode})}>{mode}뷰{mode===3?' · AI':''}</button>)}</div></div><p className="settings-note">이 브라우저에서 로그인 계정별로 저장돼요.</p>{saveError&&<p className="file-error" role="status">{saveError}</p>}<button className="settings-reset" onClick={()=>onChange({...defaultDisplayPreferences})}>화면 설정 초기화</button></section>}
 {tab==='account'&&<section><h3>계정</h3><AccountControl beforeLogout={beforeLogout}/><div className="settings-info"><strong>회원 기록은 계정에 연결돼요</strong><p>다른 기기에서도 같은 Google 계정으로 로그인하면 저장한 회원과 운동일지를 볼 수 있어요.</p></div></section>}
 {tab==='usage'&&<section><h3>AI 이용량</h3><p className="settings-intro">무료 베타</p><div className="settings-info"><strong>저장된 분석은 다시 사용해요</strong><p>파일 열기·카드 크기 변경·기록 탐색은 AI를 호출하지 않아요. 기록이 바뀌어 분석을 갱신하거나 도우미에게 질문할 때 이용량이 늘어납니다.</p></div>{!serverAiEnabled?<p className="settings-note">AI 서버 연결을 준비하고 있어요.</p>:usageError?<p className="file-error" role="alert">{usageError}</p>:!usage?<p role="status">이번 달 이용량을 불러오고 있어요…</p>:<><div className="settings-usage"><div><span>이번 달 요청</span><strong>{(usage.calls??0).toLocaleString()}<small>회</small></strong></div><div><span>입력 토큰</span><strong>{(usage.inputTokens??0).toLocaleString()}</strong></div><div><span>출력 토큰</span><strong>{(usage.outputTokens??0).toLocaleString()}</strong></div></div><p className="settings-note">무료 테스트에는 이용 한도가 있어요. 한도에 도달해도 저장된 원본과 기록은 확인할 수 있어요.</p></>}</section>}
 {tab==='feedback'&&<section><h3>개선 의견</h3><label className="settings-field">관련 화면<select value={topic} onChange={e=>setTopic(e.target.value)}>{['회원 홈','기록 수정','진행 분석','다음 수업','AI 도우미','업로드','기타'].map(v=><option key={v}>{v}</option>)}</select></label><label className="settings-field">의견<textarea rows={5} maxLength={2000} value={message} onChange={e=>{setMessage(e.target.value);setCopyStatus('');}} placeholder="어떤 화면에서 무엇이 불편했는지 알려주세요."/></label><label className="settings-field">답장 받을 연락처 <small>선택</small><input maxLength={150} value={contact} onChange={e=>setContact(e.target.value)} placeholder="이메일 또는 연락처"/></label><p className="settings-note">메일 앱에서 내용을 확인한 뒤 직접 보내주세요. 스크린샷은 메일에 첨부할 수 있어요.</p><div className="settings-feedback-actions"><button disabled={!message.trim()} onClick={()=>void copy()}>내용 복사</button><a aria-disabled={!message.trim()} className={'settings-mail '+(!message.trim()?'is-disabled':'')} href={message.trim()?`mailto:trainer.note.app@gmail.com?subject=${encodeURIComponent('[트레이너 노트] '+topic+' 개선 의견')}&body=${encodeURIComponent(feedback)}`:undefined}>메일 앱에서 작성 <Icon name="arrow" size={15}/></a></div>{copyStatus&&<p className="settings-note" role="status">{copyStatus}</p>}</section>}
 </div></div></dialog>;
}
