import {test} from 'node:test';
import assert from 'node:assert/strict';
import {changeEvidence,validateChanges,cycleOptions,validateCycle} from '../coaching-workflow.mjs';
const row=(id,date,exerciseName,kg,reps,bodyPart='하체')=>({id,date,exerciseName,bodyPart,loadType:'weighted',sets:reps.map(reps=>({kg,reps})),notes:''});
export const sample=[row('s1','2026-06-20','고블릿 스쿼트',12,[10,10,10]),row('s2','2026-09-02','고블릿 스쿼트',6,[10,10,12]),row('s3','2026-10-03','고블릿 스쿼트',8,[12,12,12]),row('r1','2026-06-30','시티드 로우',14.5,[15,15],'등'),row('r2','2026-09-30','시티드 로우',14.5,[12,12,12],'등')];
test('earlier evidence reverses overall squat trend while recent recovery stays visible',()=>{const evidence=changeEvidence(sample),s=evidence.find(e=>e.name==='고블릿 스쿼트'&&e.metric==='volume');assert.deepEqual(s.points.map(p=>p.value),[360,192,288]);assert.equal(s.overall.percent,-20);assert.equal(s.recent.percent,50);assert.equal(s.peak.date,'2026-06-20');});
test('row total volume gain survives changed set count and is not muscle gain',()=>{const evidence=changeEvidence(sample),e=evidence.find(e=>e.name==='시티드 로우'&&e.metric==='volume');assert.equal(e.overall.percent,20);const report=validateChanges({headline:'총운동량 변화',findings:[{evidenceId:e.id,interpretation:'세트 추가에 따른 총량 증가',uncertainty:'같은 기구인지 확인 필요'}],directions:[{kind:'check',text:'기구와 자세 확인',evidenceIds:[e.id]}]},evidence);assert.equal(report.findings[0].interpretation,'세트 추가에 따른 총량 증가');assert.match(e.observation,/20%/);});
test('cardio stays separate; unknown load does not become zero volume; repeated sources show composition',()=>{const rows=[...sample,{...sample[0],id:'u',date:'2026-10-04',loadType:'unknown',sets:[{kg:null,reps:12}]},{id:'c',date:'2026-10-04',exerciseName:'인터벌',bodyPart:'유산소',measurementType:'incline_speed_time',loadType:'unknown',sets:[{kg:null,reps:0,inclinePercent:20,speedKph:5,durationSeconds:60},{kg:null,reps:0,inclinePercent:0,speedKph:3,durationSeconds:60}]},row('r3','2026-09-30','바벨 로우',12.5,[10,10,10],'등')];const e=changeEvidence(rows);assert.equal(e.find(e=>e.name==='고블릿 스쿼트'&&e.metric==='volume').points.length,3);assert(!e.some(e=>e.name==='인터벌'&&e.metric==='volume'));assert.equal(e.find(e=>e.name==='인터벌'&&e.metric==='speed').points[0].value,4);assert(e.some(e=>e.label==='유사 동작 집중'));});
test('foreign findings and duplicate evidence cannot enter a report',()=>{const e=changeEvidence(sample),v={headline:'변화',findings:[{evidenceId:'other',interpretation:'해석',uncertainty:'확인'}],directions:[{kind:'check',text:'확인',evidenceIds:[e[0].id]}]};assert.throws(()=>validateChanges(v,e));v.findings=[{evidenceId:e[0].id,interpretation:'해석',uncertainty:'확인'},{evidenceId:e[0].id,interpretation:'해석',uncertainty:'확인'}];assert.throws(()=>validateChanges(v,e));});
const options=cycleOptions({count:4,frequency:2,minutes:50,equipment:'',directions:[{id:'direction-1',text:'기본 동작 유지'}]});
const candidate={id:'a',exerciseName:'스쿼트',measurementType:'repetitions',loadType:'weighted',referenceSegments:[{kg:8,reps:12}]};
const valid=()=>({title:'4회 계획',sessions:Array.from({length:4},(_,i)=>({number:i+1,focus:'기본 동작',progressWhen:'같은 자세와 회복 확인 후',adjustWhen:'피로가 크면 유지',checks:['수행 여유 기록'],items:[{candidateId:'a',reason:'선택한 방향',recovery:'',segments:[{kg:8,reps:12,durationSeconds:null,leftReps:null,rightReps:null}]}]}))});
test('cycle count, references, units and source values remain distinct',()=>{const plan=validateCycle(valid(),[candidate],options);assert.equal(plan.sessions.length,4);assert.deepEqual(plan.sessions[0].items[0].referenceSegments,[{kg:8,reps:12}]);const invalid=valid();invalid.sessions[0].items[0].segments[0].durationSeconds=60;assert.throws(()=>validateCycle(invalid,[candidate],options));assert.throws(()=>validateCycle({...valid(),sessions:valid().sessions.slice(0,3)},[candidate],options));invalid.sessions[0].items[0].candidateId='foreign';assert.throws(()=>validateCycle(invalid,[candidate],options));assert.throws(()=>cycleOptions({...options,count:5}));});

test('single-day interpretation cannot claim improvement and muscle growth claims are rejected',()=>{const e=changeEvidence([sample[0]]),value={headline:'기록 확인',findings:[{evidenceId:e[0].id,interpretation:'향상되었습니다',uncertainty:''}],directions:[{kind:'check',text:'동일 조건 기록',evidenceIds:[e[0].id]}]};assert.match(validateChanges(value,e).findings[0].interpretation,/단일 날짜/);value.findings[0].interpretation='근육 성장이 확인됩니다';assert.throws(()=>validateChanges(value,e));});
