import {test} from 'node:test';
import assert from 'node:assert/strict';
import {costMicros,classify,validInput,summarize,reportFingerprint,validateReport,hash} from '../domain.mjs';
const input=()=>({date:'2026-06-09',rawName:'squat',exerciseName:'스쿼트',bodyPart:'하체',loadType:'weighted',sets:[{kg:40,reps:10}],sourceHash:'a'.repeat(64),sourceName:'일지.png',sourcePage:1,notes:''});
test('cost includes output/thinking at distinct rates, rounds upward',()=>{assert.equal(costMicros(10000,2000),5500);assert.equal(costMicros(1,0),1);});
test('byte fingerprint uses bytes, not JSON serialization',()=>assert.equal(hash(Buffer.from('abc')),hash('abc')));
test('clean record auto accepts, unknown unit never auto accepts',()=>{assert.equal(classify({input:input(),issues:[]}).review,'auto');assert.equal(classify({input:{...input(),loadType:'unknown',sets:[{kg:null,reps:10}]},issues:[]}).review,'needs-review');});
test('confidence bypass cannot auto accept impossible calendar and missing values',()=>{assert.equal(classify({input:{...input(),date:'2025-02-29'},issues:[]}).review,'needs-review');assert.throws(()=>validInput({...input(),sets:[{kg:40,reps:0}]}));});
test('weight anomaly uses same exercise and earlier date only',()=>{const r={input:input(),issues:[]};assert.equal(classify(r,[{...input(),date:'2026-06-01',sets:[{kg:10,reps:10}]}]).review,'needs-review');assert.equal(classify(r,[{...input(),exerciseName:'다른 운동',date:'2026-06-01',sets:[{kg:10,reps:10}]}]).review,'auto');});
test('explicit member/year fixes do not suppress unrelated warnings',()=>{const v=classify({input:input(),issues:['원본 이름 다름','지정한 2026년','세트 판독 모호']},[],{yearConfirmed:true,memberConfirmed:true});assert.deepEqual(v.issues,['세트 판독 모호']);});
test('stats distinguish provisional records and bodyweight volume',()=>{const s=summarize([{...input(),id:'1',origin:'ai-auto',status:'provisional'},{...input(),id:'2',origin:'manual',loadType:'bodyweight',sets:[{kg:null,reps:20}]}]);assert.equal(s.sets,2);assert.equal(s.volume,400);assert.equal(s.autoRecords,1);assert.equal(s.days,1);});
test('report fingerprint ignores timestamps but changes for edits and goal',()=>{const m={goal:'근력',notes:''},r=[{...input(),id:'a',revision:1,status:'confirmed'}];assert.equal(reportFingerprint(m,r,[]),reportFingerprint({...m,updatedAt:123},r,[]));assert.notEqual(reportFingerprint(m,r,[]),reportFingerprint({...m,goal:'지구력'},r,[]));assert.notEqual(reportFingerprint(m,r,[]),reportFingerprint(m,[{...r[0],revision:2}],[]));});
test('report rejects invented evidence or inflated set prescription',()=>{const r={...input(),id:'a'},v={headline:'기록 요약',overview:'요약',findings:[{title:'관찰',detail:'기록',evidenceIds:['a']}],limitations:[],questions:[],program:[{recordId:'a',exerciseName:r.exerciseName,bodyPart:r.bodyPart,sets:1,reps:'10',loadGuide:'컨디션 확인',reason:'이전 기록'}],quests:[]};assert.equal(validateReport(v,[r]).program.length,1);assert.throws(()=>validateReport({...v,findings:[{...v.findings[0],evidenceIds:['fake']}]},[r]));assert.throws(()=>validateReport({...v,program:[{...v.program[0],sets:9}]},[r]));});

test('extra set fields are rejected before server writes',()=>assert.throws(()=>validInput({...input(),sets:[{kg:40,reps:10,admin:true}]})));
test('report cannot invent higher reps, duplicate an exercise or omit evidence',()=>{const r={...input(),id:'a'},v={headline:'요약',overview:'',findings:[],limitations:[],questions:[],program:[{recordId:'a',exerciseName:r.exerciseName,bodyPart:r.bodyPart,sets:1,reps:'10',loadGuide:'조건 확인',reason:'기록'}],quests:[]};assert.throws(()=>validateReport({...v,program:[{...v.program[0],reps:'100'}]},[r]));assert.throws(()=>validateReport({...v,program:[v.program[0],v.program[0]]},[r]));assert.throws(()=>validateReport({...v,findings:[{title:'관찰',detail:'근거 없음',evidenceIds:[]}]},[r]));});
