import {test} from 'node:test';
import assert from 'node:assert/strict';
import {goalVisualCandidates,goalVisualInputKey,eligibleAnalysisRecords} from '../generated/goal-visual.mjs';
import {blankTrainingGoal} from '../generated/training-goals.mjs';
import {validateGoalVisual} from '../goal-visual.mjs';
const goal={...blankTrainingGoal(),revision:1,primary:'근력',startMode:'first'};
const row=(id,date,kg=20)=>({id,date,revision:1,status:'confirmed',origin:'manual',rawName:'sq',exerciseName:'스쿼트',bodyPart:'하체',loadType:kg===null?'unknown':'weighted',sets:[{kg,reps:10}],notes:'',sourceName:'',sourceHash:'',sourcePage:0});
test('goal visuals use the same latest-date windows and exclude review records',()=>{const records=[row('old','2026-01-01'),row('recent','2026-08-01'),row('last','2026-08-28')];const eligible=eligibleAnalysisRecords(records,[{rows:[{id:'recent',review:'needs-review'}]}]);const d=goalVisualCandidates(eligible,goal,[],[],'28');assert.equal(d.from,'2026-08-01');assert.equal(d.to,'2026-08-28');assert.equal(d.days,1);assert(d.candidates.every(c=>c.points.every(p=>p.date==='2026-08-28')));assert(!d.candidates.some(c=>c.kind==='assessment'));});
test('unknown load never becomes zero volume and notes stay on their actual date',()=>{const records=[row('a','2026-08-01',null),row('b','2026-08-28',20)];const d=goalVisualCandidates(records,goal,[],[{date:'2026-08-28',text:'피로 호소'}],'all');assert.deepEqual(d.candidates.find(c=>c.id==='summary-volume').points.map(p=>p.value),[200]);assert.equal(d.candidates.find(c=>c.metric==='reps').points[0].notes.length,0);assert.deepEqual(d.candidates.find(c=>c.metric==='reps').points[1].notes,['피로 호소']);});
test('model cannot invent candidate ids and a single measurement cannot be improvement',()=>{const d=goalVisualCandidates([row('a','2026-08-28')],goal,[],[],'all'),c=d.candidates[0],value={headline:'변화 확인',status:'progress',cards:[{candidateId:c.id,format:'trend',goal:'근력',status:'progress',interpretation:'기록 확인',nextStep:'다음 기록 확인'}],missing:[]};const checked=validateGoalVisual(value,d.candidates);assert.equal(checked.cards[0].format,'comparison');assert.equal(checked.status,'insufficient');assert.throws(()=>validateGoalVisual({...value,cards:[{...value.cards[0],candidateId:'invented'}]},d.candidates));assert.equal(validateGoalVisual({...value,cards:[{...value.cards[0],format:'target'}]},d.candidates).cards[0].format,'comparison');});
test('cache input changes with memo, period, goal and record revision',()=>{const rows=[row('a','2026-08-28')],key=goalVisualInputKey(rows,goal,[],[],'all');assert.notEqual(key,goalVisualInputKey(rows,goal,[],[{date:rows[0].date,text:'피로'}],'all'));assert.notEqual(key,goalVisualInputKey(rows,goal,[],[],'28'));assert.notEqual(key,goalVisualInputKey(rows,{...goal,revision:2},[],[],'all'));assert.notEqual(key,goalVisualInputKey([{...rows[0],revision:2}],goal,[],[],'all'));});

test('total reps never claim single-set improvement and mismatched loads block progress',()=>{const first=row('a','2026-08-01',20),last={...row('b','2026-08-28',25),sets:[{kg:25,reps:15},{kg:25,reps:15}]};const d=goalVisualCandidates([first,last],goal,[],[],'all'),c=d.candidates.find(c=>c.metric==='reps');assert.equal(c.conditionsMatch,false);assert.match(c.label,/합계/);const v={headline:'향상됨',status:'progress',cards:[{candidateId:c.id,format:'trend',goal:'근력',status:'progress',interpretation:'수행 능력이 향상됨',nextStep:'조건 확인'}],missing:[]};const safe=validateGoalVisual(v,d.candidates);assert.equal(safe.cards[0].format,'conditions');assert.equal(safe.status,'insufficient');assert(!safe.cards[0].interpretation.includes('향상됨'));const one=goalVisualCandidates([last],goal,[],[],'all'),single=one.candidates.find(x=>x.metric==='reps');const out=validateGoalVisual({...v,cards:[{...v.cards[0],candidateId:single.id}]},one.candidates);assert.match(out.cards[0].interpretation,/단일 날짜/);assert(!out.headline.includes('향상됨'));assert.equal(out.cards[0].interpretationSource,'record-check');assert.match(out.cards[0].nextStep,/같은 수행 조건/);assert.match(single.points[0].condition,/2세트/);});

// Reproduces an unsupported conclusion observed in a live, synthetic model comparison.
test('push-up repetition gains cannot establish hypertrophy even with matching conditions',()=>{
 const c={id:'pushup',name:'푸시업',label:'단일 세트 횟수',unit:'회',kind:'assessment',conditionsMatch:true,target:20,points:[{date:'2026-09-01',value:12},{date:'2026-09-14',value:14}]};
 const v={headline:'푸시업 기록 변화',status:'progress',cards:[{candidateId:c.id,format:'comparison',goal:'근비대',status:'progress',interpretation:'동일한 가동 범위 내에서 안정적인 횟수 증가를 보이며 근비대 및 근지구력 향상이 확인됩니다.',nextStep:'휴식 단축'}],missing:[]};
 const out=validateGoalVisual(v,[c]);assert.equal(out.status,'insufficient');assert.equal(out.cards[0].interpretationSource,'record-check');assert.match(out.cards[0].interpretation,/판단 보류/);assert(!out.cards[0].nextStep.includes('휴식 단축'));
 const qualified=validateGoalVisual({...v,cards:[{...v.cards[0],interpretation:'반복수 증가가 관찰되나 근비대 향상은 확인할 수 없음.'}]},[c]);assert.equal(qualified.cards[0].interpretation,'반복수 증가가 관찰되나 근비대 향상은 확인할 수 없음.');
});
