import {test} from 'node:test';
import assert from 'node:assert/strict';
import {validateGoalProposal,validateGoalCoaching} from '../generated/goal-coaching.mjs';
import {validateAssessmentFields,validateAssessmentResult,assessmentProtocol,assessmentConditions,comparableResults,resultTrend} from '../generated/assessment-results.mjs';
const fields=[{label:'완료 라운드',unit:'라운드',direction:'up',target:10}];
const input={date:'2026-09-01',values:[6],conditions:'속도5, 회복1분',stopReason:'',effort:null,note:''};
test('explicit fields preserve zero, missing values and reject malformed data',()=>{assert.equal(validateAssessmentResult({...input,values:[0]},fields,'2026-09-14').values[0],0);for(const patch of [{values:[null]},{values:[-1]},{values:[Infinity]},{date:'2026-02-30'},{date:'2026-09-15'},{conditions:''},{effort:11}])assert.throws(()=>validateAssessmentResult({...input,...patch},fields,'2026-09-14'));assert.throws(()=>validateAssessmentFields([{...fields[0],direction:'observe'}]));assert.throws(()=>validateAssessmentFields([...fields,...fields]));});
test('comparison never merges changed protocols, conditions, missing values or dates outside period',()=>{const row=(id,date,v,key='a',conditions='same')=>({id,date,values:[v],protocolKey:key,conditions});const selected=comparableResults([row('a','2026-09-01',6),row('b','2026-09-03',8),row('c','2026-09-05',10,'b'),row('d','2026-09-06',10,'a','changed'),row('e','2026-09-07',null)],'a','same','2026-09-01','2026-09-30');assert.equal(selected.length,3);const trend=resultTrend(selected,0,fields[0]);assert.equal(trend.change,2);assert.equal(trend.atTarget,false);assert.equal(trend.last,8);assert.equal(resultTrend(selected,0,{...fields[0],target:null}).atTarget,null);});
test('changing only the target preserves measurement comparability; protocol or unit edits do not',()=>{const a={draft:{title:'인터벌',steps:[{name:'회복',details:'1분'}],conditions:['동일 기기']}};assert.equal(assessmentProtocol(a,fields),assessmentProtocol(a,[{...fields[0],target:12}]));assert.notEqual(assessmentProtocol(a,fields),assessmentProtocol(a,[{...fields[0],unit:'회'}]));assert.notEqual(assessmentProtocol(a,fields),assessmentProtocol({...a,draft:{...a.draft,steps:[{name:'회복',details:'2분'}]}},fields));});
test('goal proposals retain gaps; confirmation and reusable rules have explicit validation',()=>{const p={primary:'심폐·체력',secondary:['근비대'],detail:'10라운드',initialState:'6라운드',reviewAfter:0,alignment:[{goal:'심폐·체력',assessment:'라운드',gap:''},{goal:'근비대',assessment:'확인 지표 미정',gap:'체력 평가만으로 판단 불가'}],questions:['목표 기간?'],assessment:null};assert.equal(validateGoalProposal(p).reviewAfter,0);assert.throws(()=>validateGoalProposal({...p,reviewAfter:80}));assert.throws(()=>validateGoalCoaching({proposalId:'bad',reason:'',remember:false,principle:''}));assert.throws(()=>validateGoalCoaching({proposalId:'11111111-1111-4111-a111-111111111111',reason:'',remember:true,principle:''}));});

import {openApiSchema} from '../domain.mjs';
import {GOAL_SCHEMA} from '../goal-coaching.mjs';
test('Gemini schema keeps absent assessments and numeric targets nullable',()=>{const schema=openApiSchema(GOAL_SCHEMA);assert.equal(schema.properties.assessment.nullable,true);assert.equal(schema.properties.assessment.properties.fields.items.properties.target.nullable,true);});

test('canonical goal conditions are explicit and a changed recovery protocol cannot inherit the target',()=>{const a={draft:{steps:[{name:'운동',details:'1분'},{name:'회복',details:'1분'}],conditions:['동일 기기']}};assert.equal(assessmentConditions(a),'운동: 1분\n회복: 1분\n동일 기기');assert.notEqual(assessmentConditions(a),'운동: 1분\n회복: 2분\n동일 기기');});
