import {test} from 'node:test';
import assert from 'node:assert/strict';
import {evaluateJudgment,validateCriteria,selectCases,validateJudgments,KNOWLEDGE_VERSION,modelJudgmentContext} from '../judgment.mjs';
import {reportFingerprint} from '../domain.mjs';
const rec=(id,date,reps=10)=>({id,date,exerciseName:'스쿼트',loadType:'weighted',sets:[{kg:40,reps}],notes:''});
const input={scope:'general-adult',conditionsConfirmed:true,exerciseName:'스쿼트',equipment:'바벨',loadBasis:'합계',side:'양측',setPurpose:'본 세트',loadKg:40,targetReps:15,minSessions:3,windowDays:28};
const records=[rec('a','2026-09-01'),rec('b','2026-09-05'),rec('c','2026-09-09')];
const criteria=()=>validateCriteria(input,records,'근력',null);
const evaluate=(r=records,c=criteria(),goal='근력')=>evaluateJudgment({records:r,criteria:c,goal,cases:[]});
const card=(c,id)=>c.cards.find(v=>v.id===id);
const reply=c=>c.cards.map(v=>({cardId:v.id,version:v.version,status:v.status,observation:'관찰',interpretation:'해석',question:'',action:'확인',evidenceIds:v.evidenceIds,caseIds:[]}));
test('no invented judgment thresholds when criteria absent',()=>{const c=evaluate(records,null);assert.equal(card(c,'comparison').status,'needs_information');assert.equal(card(c,'plateau').status,'needs_information');});
test('expert plan scope must be explicitly confirmed',()=>{assert.throws(()=>validateCriteria({...input,scope:'rehab'},records,'근력',null));assert.throws(()=>validateCriteria({...input,conditionsConfirmed:false},records,'근력',null));});
test('same name is insufficient when conditions or records change',()=>{const c=criteria();assert.equal(card(evaluate(records,c),'comparison').status,'candidate');assert.equal(card(evaluate([...records,rec('d','2026-09-10')],c),'comparison').status,'needs_information');assert.equal(card(evaluate([{...records[0],notes:'다른 기구'},...records.slice(1)],c),'comparison').status,'needs_information');assert.equal(card(evaluate(records,c,'다른 목표'),'comparison').status,'needs_information');});
test('plateau requires trainer-defined sessions within window, not blank periods',()=>{assert.equal(card(evaluate(),'plateau').status,'candidate');assert.equal(card(evaluate(records,{...criteria(),minSessions:4}),'plateau').status,'needs_information');assert.equal(card(evaluate(records,{...criteria(),windowDays:2}),'plateau').status,'needs_information');});
test('multiple exercises on same day never count as separate sessions',()=>{const r=[rec('a','2026-09-01'),rec('b','2026-09-01'),rec('c','2026-09-01')],c=validateCriteria(input,r,'근력',null);assert.equal(card(evaluate(r,c),'plateau').status,'needs_information');});
test('different load not summed into performance trend',()=>{const r=[records[0],{...records[1],sets:[{kg:60,reps:20}]}],c=validateCriteria(input,r,'근력',null);assert.equal(card(evaluate(r,c),'progress').status,'needs_information');});
test('progress uses measured repetition delta, a decrease is not progress',()=>{const r=[records[0],rec('b','2026-09-09',15)],c=validateCriteria(input,r,'근력',null),p=card(evaluate(r,c),'progress');assert.equal(p.status,'candidate');assert.equal(p.metrics.delta,5);assert.equal(p.metrics.reachedTarget,true);const r2=[rec('a','2026-09-01',15),rec('b','2026-09-09',10)],c2=validateCriteria(input,r2,'근력',null);assert.equal(card(evaluate(r2,c2),'progress').status,'not_applicable');});
test('future plan never explains previous sessions',()=>{const c={...criteria(),planDate:'2026-09-09',planSnapshot:{savedAt:Date.parse('2026-09-10'),program:[{exerciseName:'스쿼트',sets:3}]}};assert.equal(card(evaluate(records,c),'plan').status,'needs_information');c.planSnapshot.savedAt=Date.parse('2026-09-08');assert.equal(card(evaluate(records,c),'plan').metrics.differences[0].recordedSets,1);});
test('unseen cards, versions, promoted status and fake record/case evidence rejected',()=>{const c=evaluate(),v=reply(c);assert.equal(validateJudgments(v,c).length,5);for(const patch of [{cardId:'invented'},{version:'fake'},{status:'diagnosed'},{evidenceIds:['fake']},{caseIds:['unseen']}])assert.throws(()=>validateJudgments([{...v[0],...patch},...v.slice(1)],c));assert.throws(()=>validateJudgments(v.slice(1),c));});
test('case retrieval respects as-of time and includes contrary outcomes',()=>{const t=Date.parse('2026-09-10'),d={id:'d',createdAt:t-1000,snapshot:{records:[records[0]]},reason:'확인',cardId:'comparison'},o={id:'o',decisionId:'d',createdAt:t-500,observedDate:'2026-09-10',result:'different',note:'기대와 다름'};assert.equal(selectCases([d,{...d,id:'future',createdAt:t+1}],[o,{...o,id:'future-o',createdAt:t+1}],records,t).length,1);assert.equal(selectCases([d],[o],records,t)[0].outcomes[0].result,'different');assert.equal(selectCases([d],[o],records,t-700)[0].outcomes.length,0);});
test('changing knowledge or correction reason changes report cache',()=>{const m={goal:'근력',notes:''};assert.notEqual(reportFingerprint(m,records,[],{reason:'유지'}),reportFingerprint(m,records,[],{reason:'변경'}));assert.equal(evaluate().version,KNOWLEDGE_VERSION);});

test('model input omits server-only signatures but keeps decision conditions',()=>{const c=evaluate(),model=modelJudgmentContext(c);assert.equal(model.criteria.confirmedRecordSignatures,undefined);assert.equal(model.criteria.equipment,'바벨');assert.ok(c.criteria.confirmedRecordSignatures.length);});

test('unilateral performance uses weaker side, never the total or mixed counting modes',()=>{const r=[{...rec('a','2026-09-01'),sets:[{kg:40,reps:20,leftReps:12,rightReps:8}]},{...rec('b','2026-09-09'),sets:[{kg:40,reps:22,leftReps:12,rightReps:10}]}],c=validateCriteria(input,r,'근력',null),p=card(evaluate(r,c),'progress');assert.equal(p.metrics.firstReps,8);assert.equal(p.metrics.latestReps,10);assert.equal(p.metrics.reachedTarget,false);const mixed=[r[0],rec('b','2026-09-09')];assert.equal(card(evaluate(mixed,validateCriteria(input,mixed,'근력',null)),'comparison').status,'needs_information');});
