import {test,before,after,beforeEach} from 'node:test';
import assert from 'node:assert/strict';
import {initializeApp,deleteApp} from 'firebase-admin/app';
import {getFirestore,Timestamp} from 'firebase-admin/firestore';
import {createService} from '../service.mjs';
import {LIMITS,costMicros} from '../domain.mjs';
const judgments=facts=>facts.judgmentContext.cards.map(c=>({cardId:c.id,version:c.version,status:c.status,observation:c.reason,interpretation:'조건 범위 내 참고',question:'',action:'트레이너 확인',evidenceIds:c.evidenceIds,caseIds:[]}));
let app,db,service,calls,queued,answer,provider,clock;
const uid='service-test',mid='member',fileId='a'.repeat(64),base=`trainers/${uid}/members/${mid}`;
const raw=(patch={})=>({records:[{page:1,memberName:'회원 A',year:2026,month:6,day:9,rawName:'BB squat',exerciseName:'바벨 스쿼트',bodyPart:'하체',loadType:'weighted',sets:[{kg:40,reps:12},{kg:60,reps:10}],notes:'',issues:[],...patch}],unparsed:[]});
function make(limits=LIMITS){return createService({db,now:()=>clock,limits,readSource:async()=>'',enqueue:async(...v)=>queued.push(v),model:async request=>{calls.push(request);if(provider)return provider(request);if(request.parts[1])return {value:answer,usage:{inputTokens:2000,outputTokens:600}};const facts=JSON.parse(request.parts[0].text),r=facts.records[0];return {value:{judgments:judgments(facts),headline:'최근 기록',overview:'기록에 근거한 분석',findings:[{title:'세트',detail:'수행 기록 확인',evidenceIds:[r.id]}],limitations:['컨디션 확인 필요'],questions:[],program:[{recordId:r.id,exerciseName:r.exerciseName,bodyPart:r.bodyPart,sets:1,reps:'10',loadGuide:'이전 수행 조건 확인',reason:'최근 기록'}],quests:[]},usage:{inputTokens:1500,outputTokens:500}};}});}
const imported=async()=> (await db.doc(base+'/imports/'+fileId).get()).data();
const records=async()=> (await db.collection(base+'/records').get()).docs.map(d=>({id:d.id,...d.data()}));
before(()=>{if(!process.env.FIRESTORE_EMULATOR_HOST)throw Error('Emulator required; never run against live data');app=initializeApp({projectId:'demo-trainer-note'},'service-tests');db=getFirestore(app);});
after(async()=>{await deleteApp(app);});
beforeEach(async()=>{const host=process.env.FIRESTORE_EMULATOR_HOST;const r=await fetch(`http://${host}/emulator/v1/projects/demo-trainer-note/databases/(default)/documents`,{method:'DELETE'});assert.ok(r.ok);calls=[];queued=[];provider=null;answer=raw();clock=Date.parse('2026-09-11T00:00:00Z');service=make();await db.doc(base).set({name:'회원 A',goal:'꾸준한 운동',notes:'',recordCount:0});await db.doc(base+'/files/'+fileId).set({name:'일지.png',contentType:'image/png',size:100,status:'ready'});});
test('one extraction persists, reopening and simultaneous read reuse it',async()=>{await Promise.all([service.startImport(uid,mid,fileId),service.startImport(uid,mid,fileId)]);assert.equal(calls.length,1);assert.equal((await imported()).status,'ready');assert.equal((await records())[0].status,'provisional');assert.equal((await db.doc(base).get()).data().recordCount,1);await service.startImport(uid,mid,fileId,true);assert.equal(calls.length,1);});
test('only ambiguous rows wait, clean rows flow to analysis',async()=>{answer.records.push({...raw({rawName:'unknown',exerciseName:'모호한 운동',issues:['운동명 확인']}).records[0]});await service.startImport(uid,mid,fileId);assert.equal((await records()).length,1);assert.equal((await imported()).rows.filter(r=>r.review==='needs-review').length,1);await service.buildReport(uid,mid);const a=(await db.doc(base+'/analysis/current').get()).data();assert.equal(a.excludedCount,1);assert.equal(a.summary.sets,2);assert.equal(a.report.program.length,1);});
test('missing year and member are bulk corrected without rereading model',async()=>{answer=raw({year:null,memberName:''});await service.startImport(uid,mid,fileId);assert.equal((await records()).length,0);let v=await imported();await service.reviewImport(uid,mid,fileId,{operation:'year',year:2025,revision:v.revision});v=await imported();assert.equal(v.rows[0].review,'needs-review');await service.reviewImport(uid,mid,fileId,{operation:'member',revision:v.revision});assert.equal((await records())[0].performedAt.toDate().getUTCFullYear(),2025);assert.equal(calls.length,1);v=await imported();await service.reviewImport(uid,mid,fileId,{operation:'year',year:2026,revision:v.revision});assert.equal((await records())[0].performedAt.toDate().getUTCFullYear(),2026);assert.equal((await db.doc(base).get()).data().recordCount,1);});
test('trainer edit wins over later bulk corrections and stale editor cannot overwrite',async()=>{answer=raw({year:null});await service.startImport(uid,mid,fileId);let v=await imported();await service.reviewImport(uid,mid,fileId,{operation:'year',year:2025,revision:v.revision});v=await imported();const input={...v.rows[0].input,exerciseName:'트레이너 확인 스쿼트'};await service.reviewImport(uid,mid,fileId,{operation:'row',rowId:v.rows[0].id,input,revision:v.revision,reason:'변형 확인'});await assert.rejects(service.reviewImport(uid,mid,fileId,{operation:'row',rowId:v.rows[0].id,input,revision:v.revision}));v=await imported();await service.reviewImport(uid,mid,fileId,{operation:'year',year:2026,revision:v.revision});const r=(await records())[0];assert.equal(r.exerciseName,'트레이너 확인 스쿼트');assert.equal(r.performedAt.toDate().getUTCFullYear(),2025);assert.equal(r.status,'confirmed');assert.equal((await db.collection(base+'/corrections').get()).size,1);});
test('invalid year correction removes only provisional data from analysis',async()=>{answer=raw({year:null,month:2,day:29});await service.startImport(uid,mid,fileId);let v=await imported();await service.reviewImport(uid,mid,fileId,{operation:'year',year:2024,revision:v.revision});assert.equal((await records()).length,1);v=await imported();await service.reviewImport(uid,mid,fileId,{operation:'year',year:2025,revision:v.revision});assert.equal((await records()).length,0);assert.equal((await db.doc(base).get()).data().recordCount,0);});
test('combined report and program cached without further paid calls',async()=>{await service.startImport(uid,mid,fileId);await service.buildReport(uid,mid);assert.equal(calls.length,2);await service.buildReport(uid,mid);assert.equal(calls.length,2);const usage=(await db.doc(`trainers/${uid}/aiUsage/2026-09`).get()).data();assert.equal(usage.usedMicros,costMicros(3500,1100));assert.equal(usage.reservedMicros,0);assert.equal(usage.inputTokens,3500);});
test('empty or pending-only reports never cost tokens',async()=>{answer=raw({year:null});await service.startImport(uid,mid,fileId);await service.buildReport(uid,mid);assert.equal(calls.length,1);assert.equal((await db.doc(base+'/analysis/current').get()).data().report.program.length,0);});
test('goal changes invalidate report, saved trainer plan is preserved',async()=>{await service.startImport(uid,mid,fileId);await service.buildReport(uid,mid);const a=(await db.doc(base+'/analysis/current').get()).data();await service.savePlan(uid,mid,{program:a.report.program,reason:'오늘 컨디션 반영',revision:0,basedOn:a.fingerprint});await assert.rejects(service.savePlan(uid,mid,{program:a.report.program,reason:'오래된 화면',revision:0}));await db.doc(base).update({goal:'새 목표'});await service.buildReport(uid,mid);assert.equal(calls.length,3);assert.equal((await db.doc(base+'/plans/current').get()).data().reason,'오늘 컨디션 반영');});
test('concurrent paid requests cannot race beyond daily allowance',async()=>{service=make({...LIMITS,dailyCalls:1});const result=await Promise.allSettled([service.paid(uid,'test',{parts:[{},{}]},100),service.paid(uid,'test',{parts:[{},{}]},100)]);assert.equal(result.filter(v=>v.status==='fulfilled').length,1);assert.equal(calls.length,1);});
for(const cap of ['monthlyMicros','globalMonthlyMicros'])test(`${cap} reserves before provider call`,async()=>{service=make({...LIMITS,[cap]:1});await assert.rejects(service.paid(uid,'test',{parts:[{},{}]},100),/AI_USAGE_LIMIT/);assert.equal(calls.length,0);});
test('unknown provider failure conservatively charges reservation and releases lock',async()=>{provider=async()=>{throw Error('timeout');};await assert.rejects(service.paid(uid,'test',{},100));const v=(await db.doc(`trainers/${uid}/aiUsage/2026-09`).get()).data();assert.equal(v.usedMicros,costMicros(LIMITS.maxInputTokens,100));assert.equal(v.reservedMicros,0);});
test('preflight rejection charges no model cost',async()=>{provider=async()=>{throw Object.assign(Error('input too large'),{notBillable:true});};await assert.rejects(service.paid(uid,'test',{},100));assert.equal((await db.doc(`trainers/${uid}/aiUsage/2026-09`).get()).data().usedMicros,0);});
test('malformed response usage is charged once and retry is explicit',async()=>{provider=async()=>({value:{bad:true},usage:{inputTokens:1000,outputTokens:300}});await service.startImport(uid,mid,fileId);assert.equal((await imported()).status,'error');await service.startImport(uid,mid,fileId);assert.equal(calls.length,1);provider=null;await service.startImport(uid,mid,fileId,true);assert.equal(calls.length,2);assert.equal((await imported()).status,'ready');});
test('generation changed during model call cannot publish stale report',async()=>{await service.startImport(uid,mid,fileId);provider=async request=>{const facts=JSON.parse(request.parts[0].text),r=facts.records[0];await db.doc(base).update({goal:'수정된 목표'});return {value:{judgments:judgments(facts),headline:'오래된 분석',overview:'',findings:[],limitations:[],questions:[],program:[],quests:[]},usage:{inputTokens:100,outputTokens:100}};};const r=await service.buildReport(uid,mid);assert.equal(r.stale,true);assert.notEqual((await db.doc(base+'/analysis/current').get()).data().report?.headline,'오래된 분석');assert.equal((await db.doc(base+'/analysis/current').get()).data().status,'queued');});
test('large file gives visible error without paying provider',async()=>{await db.doc(base+'/files/'+fileId).update({size:11*1024*1024});await service.startImport(uid,mid,fileId);assert.equal(calls.length,0);assert.match((await imported()).error,/10MB/);});
test('deleted member never generates or saves results',async()=>{await db.doc(base).delete();await assert.rejects(service.startImport(uid,mid,fileId));await service.buildReport(uid,mid);assert.equal(calls.length,0);assert.equal((await db.doc(base+'/analysis/current').get()).exists,false);});
test('queue combines edits before worker starts but permits follow-up while processing',async()=>{await service.scheduleReport(uid,mid);await service.scheduleReport(uid,mid);assert.equal(queued.length,1);await db.doc(base+'/analysis/current').update({status:'processing'});await service.scheduleReport(uid,mid);assert.equal(queued.length,2);assert.notEqual(queued[0][1],queued[1][1]);});

test('record corrections reuse extraction; unchanged analysis fields reuse report',async()=>{await service.startImport(uid,mid,fileId);await service.buildReport(uid,mid);const r=(await records())[0];await db.doc(base+'/records/'+r.id).update({revision:2,rawName:'cosmetic original text fix'});await service.buildReport(uid,mid);assert.equal(calls.length,2);await db.doc(base+'/records/'+r.id).update({revision:3,sets:[{kg:40,reps:12},{kg:70,reps:10}]});await service.buildReport(uid,mid);assert.equal(calls.length,3);assert.equal(calls.filter(c=>c.parts[1]).length,1);assert.equal((await db.doc(base+'/analysis/current').get()).data().summary.volume,1180);});

const decisionInput=(fingerprint,patch={})=>({requestId:'11111111-1111-4111-a111-111111111111',fingerprint,cardId:'goal-data',choice:'check',reason:'목표 측정을 먼저 확인',alternative:'바로 증량',changeCondition:'수행 조건이 같으면 재검토',followUpMetric:'같은 무게의 횟수',followUpDate:'2026-09-15',...patch});
test('judgment cards are supplied to model and validated in report',async()=>{await service.startImport(uid,mid,fileId);await service.buildReport(uid,mid);const facts=JSON.parse(calls[1].parts[0].text),a=(await db.doc(base+'/analysis/current').get()).data();assert.equal(facts.judgmentContext.cards.length,5);assert.equal(a.report.judgments.length,5);assert.ok(a.report.judgments.every(j=>j.status==='needs_information'));});
test('decision snapshot, failure outcome and reason are reused without another extraction',async()=>{await service.startImport(uid,mid,fileId);await service.buildReport(uid,mid);const a=(await db.doc(base+'/analysis/current').get()).data(),d=decisionInput(a.fingerprint);await service.saveJudgmentDecision(uid,mid,d);await service.saveJudgmentDecision(uid,mid,d);assert.equal((await db.collection(base+'/judgmentDecisions').get()).size,1);await service.buildReport(uid,mid);let facts=JSON.parse(calls.at(-1).parts[0].text);assert.equal(facts.judgmentContext.cases[0].reason,d.reason);const original=(await db.doc(base+'/judgmentDecisions/'+d.requestId).get()).data().snapshot;clock+=86400000;await service.saveJudgmentOutcome(uid,mid,{requestId:'22222222-2222-4222-a222-222222222222',decisionId:d.requestId,result:'different',note:'같은 무게에서 횟수 감소',observedDate:'2026-09-12'});await service.buildReport(uid,mid);facts=JSON.parse(calls.at(-1).parts[0].text);assert.equal(facts.judgmentContext.cases[0].outcomes[0].result,'different');assert.deepEqual((await db.doc(base+'/judgmentDecisions/'+d.requestId).get()).data().snapshot,original);assert.equal(calls.filter(c=>c.parts[1]).length,1);const charged=calls.length;await service.buildReport(uid,mid);assert.equal(calls.length,charged);});
test('unowned member decision, nonexistent outcome parent and future outcome rejected',async()=>{await service.startImport(uid,mid,fileId);await service.buildReport(uid,mid);const a=(await db.doc(base+'/analysis/current').get()).data();await assert.rejects(service.saveJudgmentDecision('other-trainer',mid,decisionInput(a.fingerprint)));await service.saveJudgmentDecision(uid,mid,decisionInput(a.fingerprint));await assert.rejects(service.saveJudgmentOutcome(uid,mid,{requestId:'22222222-2222-4222-a222-222222222222',decisionId:'33333333-3333-4333-a333-333333333333',result:'unclear',note:'관찰',observedDate:'2026-09-11'}));await assert.rejects(service.saveJudgmentOutcome(uid,mid,{requestId:'22222222-2222-4222-a222-222222222222',decisionId:decisionInput('').requestId,result:'unclear',note:'관찰',observedDate:'2026-09-20'}));});
test('criteria stored with record signatures and stale revisions rejected',async()=>{await service.startImport(uid,mid,fileId);const input={scope:'general-adult',conditionsConfirmed:true,exerciseName:'바벨 스쿼트',equipment:'같은 바벨',loadBasis:'양측 합',side:'양측',setPurpose:'본 운동',loadKg:40,targetReps:15,minSessions:3,windowDays:28,planDate:''};await service.saveJudgmentCriteria(uid,mid,{revision:0,input});await assert.rejects(service.saveJudgmentCriteria(uid,mid,{revision:0,input}));await service.buildReport(uid,mid);let a=(await db.doc(base+'/analysis/current').get()).data();assert.equal(a.judgmentContext.cards[0].status,'candidate');const r=(await records())[0];await db.doc(base+'/records/'+r.id).update({revision:2,notes:'기구 변경'});await service.buildReport(uid,mid);a=(await db.doc(base+'/analysis/current').get()).data();assert.equal(a.judgmentContext.cards[0].status,'needs_information');});
test('correction reason alone invalidates report cache',async()=>{await service.startImport(uid,mid,fileId);await service.buildReport(uid,mid);await db.doc(base+'/corrections/reason').set({before:{exerciseName:'스쿼트'},after:{exerciseName:'스쿼트'},reason:'중량 감소는 자세 집중 때문',createdAt:Timestamp.fromMillis(clock)});await service.buildReport(uid,mid);assert.equal(calls.length,3);assert.equal(JSON.parse(calls[2].parts[0].text).corrections[0].reason,'중량 감소는 자세 집중 때문');});

test('outcome on current Korean morning is valid and previous day is rejected',async()=>{
 clock=Date.parse('2026-09-10T23:00:00Z');await service.startImport(uid,mid,fileId);await service.buildReport(uid,mid);
 const a=(await db.doc(base+'/analysis/current').get()).data(),d=decisionInput(a.fingerprint);await service.saveJudgmentDecision(uid,mid,d);
 const result={requestId:'44444444-4444-4444-a444-444444444444',decisionId:d.requestId,result:'unclear',note:'당일 상태 관찰',observedDate:'2026-09-11'};
 await service.saveJudgmentOutcome(uid,mid,result);await service.buildReport(uid,mid);
 assert.equal(JSON.parse(calls.at(-1).parts[0].text).judgmentContext.cases[0].outcomes[0].observedDate,'2026-09-11');
 await assert.rejects(service.saveJudgmentOutcome(uid,mid,{...result,requestId:'55555555-5555-4555-a555-555555555555',observedDate:'2026-09-10'}));
});

test('compound extraction writes two provisional records with no duplicate parent count',async()=>{answer.records=[{...raw().records[0],rawName:'Cable ext + DB curl',sets:[],issues:[],components:[{rawName:'Cable ext',exerciseName:'케이블 익스텐션',bodyPart:'삼두',loadType:'weighted',sets:[{kg:20,reps:8}],notes:'',issues:[],mapping:'20/5 첫 무게, 8/10 첫 횟수'},{rawName:'DB curl',exerciseName:'덤벨 컬',bodyPart:'이두',loadType:'weighted',sets:[{kg:5,reps:10}],notes:'',issues:[],mapping:'20/5 둘째 무게, 8/10 둘째 횟수'}]}];await service.startImport(uid,mid,fileId);assert.equal((await records()).length,2);assert.equal((await db.doc(base).get()).data().recordCount,2);await service.startImport(uid,mid,fileId);assert.equal(calls.length,1);assert.equal((await records()).length,2);});
const chatInput=(patch={})=>({requestId:'77777777-7777-4777-a777-777777777777',question:'무엇이 달라졌나요?',fileId,...patch});
test('chat uses current owned records, persists answer and reuses same request without payment',async()=>{await service.startImport(uid,mid,fileId);provider=async request=>{const facts=JSON.parse(request.parts[0].text);assert.equal(facts.records.length,1);return {value:{answer:'기록을 먼저 비교해보세요.',references:[facts.records[0].id],questions:[]},usage:{inputTokens:100,outputTokens:50}};};const a=await service.chat(uid,mid,chatInput());assert.equal(a.references.length,1);const n=calls.length;await service.chat(uid,mid,chatInput());assert.equal(calls.length,n);assert.equal((await db.doc(base+'/chats/'+chatInput().requestId).get()).data().status,'ready');await assert.rejects(service.chat(uid,mid,chatInput({question:'다른 내용'})));});
test('chat cannot read another trainer, member source or foreign conversation',async()=>{await service.startImport(uid,mid,fileId);const n=calls.length;await assert.rejects(service.chat('foreign',mid,chatInput()));await assert.rejects(service.chat(uid,mid,chatInput({fileId:'b'.repeat(64)})));await assert.rejects(service.chat(uid,mid,chatInput({previousId:'88888888-8888-4888-a888-888888888888'})));assert.equal(calls.length,n);});
test('chat enforces existing cost cap and rejects fabricated citations',async()=>{await service.startImport(uid,mid,fileId);provider=async()=>({value:{answer:'없는 기록',references:['foreign'],questions:[]},usage:{inputTokens:100,outputTokens:10}});await assert.rejects(service.chat(uid,mid,chatInput()));assert.equal((await db.doc(base+'/chats/'+chatInput().requestId).get()).data().status,'error');const n=calls.length;await assert.rejects(service.chat(uid,mid,chatInput()));assert.equal(calls.length,n);service=make({...LIMITS,dailyCalls:0});await assert.rejects(service.chat(uid,mid,chatInput({requestId:'99999999-9999-4999-a999-999999999999'})));assert.equal(calls.length,n);});
