import {test} from 'node:test';
import assert from 'node:assert/strict';
import {blankTrainingGoal,trainingGoalNotes,TRAINING_METRICS,trainingGoalTitle,validateTrainingGoal,validDate,progressStats,applicableRange,observedRange,goalMetricIds} from '../generated/training-goals.mjs';
const goal=()=>({...blankTrainingGoal(),primary:'근비대',metrics:goalMetricIds('근비대'),startDate:'2026-09-01'});
const row=(patch={})=>({id:'one',date:'2026-09-01',loadType:'weighted',bodyPart:'하체',sets:[{kg:20,reps:10}],...patch});
test('goals select relevant metrics and reject impossible dates',()=>{assert.deepEqual(goalMetricIds('다이어트(체지방 감소)'),['composition','strength']);assert.equal(validDate('2026-99-01'),false);assert.equal(validDate('2026-02-29'),false);assert.equal(validDate('2024-02-29'),true);assert.equal(validateTrainingGoal(goal()).primary,'근비대');});
test('planned ranges require dates, trainer confirmation and rationale',()=>{const g=goal();g.plan={sets:{min:10,max:20},volume:null,from:'2026-09-01',to:'2026-09-30',reason:'단계별 수행량 유지',confirmed:true};assert.doesNotThrow(()=>validateTrainingGoal(g));for(const patch of [{confirmed:false},{reason:''},{from:'2026-08-31'},{to:'2026-08-30'},{sets:{min:20,max:10}},{sets:{min:10,max:Infinity}}])assert.throws(()=>validateTrainingGoal({...g,plan:{...g.plan,...patch}}));assert.throws(()=>validateTrainingGoal({...g,route:'existing',startMode:'unknown'}));assert.equal(applicableRange({...g,revision:1},'2026-10-01','sets'),null);assert.deepEqual(applicableRange({...g,revision:1},'2026-09-30','sets'),{min:10,max:20});});
test('body part percentages require a complete valid split',()=>{const g=goal();g.distribution={mode:'percent',upper:50,parts:['등','하체'],shares:{등:40,하체:60}};assert.doesNotThrow(()=>validateTrainingGoal(g));g.distribution.shares.하체=50;assert.throws(()=>validateTrainingGoal(g));});
test('averages keep cardio and unknown loads separate and aggregate dates',()=>{const stats=progressStats([row(),row({id:'two',loadType:'bodyweight',sets:[{kg:null,reps:15}]}),row({id:'three',exerciseName:'러닝머신',bodyPart:'유산소',date:'2026-09-02',measurementType:'duration',loadType:'unknown',sets:[{kg:null,reps:0,durationSeconds:60}]}),row({pending:true}),row({date:'2026-99-01'}),row({sets:[{kg:-1,reps:10}]})]);assert.equal(stats.days,2);assert.equal(stats.averageSets,2);assert.equal(stats.averageVolume,200);assert.equal(stats.cardio,1);assert.equal(stats.excludedVolume,1);assert.equal(stats.excludedRecords,1);assert.equal(stats.trend[1].volume,null);assert.equal(progressStats([row({loadType:'bodyweight',sets:[{kg:null,reps:10}]})]).averageVolume,null);});
test('L/R pairs retain one set and use both side repetitions for volume',()=>{const stats=progressStats([row({sets:[{kg:20,reps:18,leftReps:10,rightReps:8}]})]);assert.equal(stats.sets,1);assert.equal(stats.volume,360);assert.equal(progressStats([row()], '2026-09-02').days,0);});
test('observed range needs five samples and describes middle half only',()=>{assert.equal(observedRange([1,2,3,4]),null);assert.deepEqual(observedRange([5,1,4,2,3]),{min:2,max:4});});

test('custom goal title and separate initial state survive validation, including legacy goals',()=>{const g={...goal(),primary:'직접 설정',detail:'  오른쪽 둔근 강화  ',initialState:'  L 12회 / R 8회  '};const clean=validateTrainingGoal(g);assert.equal(trainingGoalTitle(clean),'오른쪽 둔근 강화');assert.equal(clean.initialState,'L 12회 / R 8회');assert.throws(()=>validateTrainingGoal({...g,detail:'  '}),/직접 입력할 목표/);assert.throws(()=>validateTrainingGoal({...g,initialState:'a'.repeat(501)}));const legacy={...g};delete legacy.initialState;assert.equal(validateTrainingGoal(legacy).initialState,'');assert.equal(trainingGoalTitle(goal()),'근비대');});

test('evaluation fields are optional, empty by default and preserve trainer input',()=>{
 const blank=blankTrainingGoal();assert.equal(blank.observation,'');assert.equal(blank.protocol,'');
 const custom={...goal(),metrics:['observation'],observation:'',protocol:''};assert.doesNotThrow(()=>validateTrainingGoal(custom));
 const legacy={observation:'동작의 질, 피로와 회원 반응 확인',protocol:TRAINING_METRICS.map(m=>m.description).join('\n')};assert.deepEqual(trainingGoalNotes(legacy),{observation:'',protocol:''});
 const written={observation:'오른쪽 지지 시 골반 흔들림',protocol:'같은 중량·깊이로 L/R 비교'};assert.deepEqual(trainingGoalNotes(written),written);assert.equal(validateTrainingGoal({...custom,...written}).protocol,written.protocol);
 const mixed={...written,protocol:TRAINING_METRICS[0].description+'\n트레이너 추가 조건'};assert.deepEqual(trainingGoalNotes(mixed),mixed);
});
