import {readFileSync,writeFileSync,mkdtempSync,rmSync} from 'node:fs';
import {tmpdir} from 'node:os';
import {join} from 'node:path';
import {pathToFileURL} from 'node:url';
import ts from 'typescript';
const root=new URL('../../',import.meta.url);
import assert from 'node:assert/strict';
const dir=mkdtempSync(join(tmpdir(),'analysis-test-'));
for(const name of ['cardio-distribution','goal-coaching','assessment-results','training-assessment','workout-measurements','training-goals','progress-analysis'])writeFileSync(join(dir,name+'.mjs'),ts.transpileModule(readFileSync(new URL('src/lib/'+name+'.ts',root),'utf8'),{compilerOptions:{module:ts.ModuleKind.ESNext,target:ts.ScriptTarget.ES2022}}).outputText.replace(/from '\.\/(cardio-distribution|goal-coaching|assessment-results|training-assessment|training-goals|workout-measurements)'/g,"from './$1.mjs'"));
const {sessionChartContext,displayWorkoutNotes,analysisWindow,exerciseGroups,exerciseFamilies,performanceMetrics,performanceChartDays,companionMetric,performanceDays,allocation}=await import(pathToFileURL(join(dir,'progress-analysis.mjs')));
const {blankTrainingGoal}=await import(pathToFileURL(join(dir,'training-goals.mjs')));
const base={id:'a',date:'2026-09-10',exerciseName:'스쿼트',bodyPart:'하체',loadType:'weighted',sets:[{kg:10,reps:18,leftReps:10,rightReps:8}],status:'confirmed',pending:false};
const cardio={...base,id:'cardio',exerciseName:'로잉',bodyPart:'전신',loadType:'unknown',measurementType:'distance_time',sets:[{kg:null,reps:0,distanceMeters:500,durationSeconds:140}]};
const old={...base,id:'old',date:'2026-08-01'},bad={...base,id:'bad',sets:[{kg:10,reps:0}]};
const w=analysisWindow([base,cardio,old,bad],'28');
assert.equal(w.sets,1);assert.equal(w.volume,180);assert.equal(w.cardio,1);assert.equal(w.excludedRecords,1);assert.equal(w.records.length,2);
assert.equal(analysisWindow([base,old],'all').sets,2);
assert.equal(performanceDays([base],'left')[0].value,10);assert.equal(performanceDays([base],'right')[0].value,8);
assert.equal(performanceDays([{...base,sets:[{kg:null,reps:10}],loadType:'bodyweight'}],'volume')[0].value,null);
assert.equal(performanceDays([cardio],'duration')[0].value,140);
assert.equal(exerciseGroups([base,{...base,id:'b',loadType:'bodyweight'},{...base,id:'c',bodyPart:'등'}]).length,2);
const air={...base,exerciseName:'에어 바이크',bodyPart:'전신'};
const aliasRows=[air,{...air,id:'alias',exerciseName:'에어바이크'},{...air,id:'later',exerciseName:'에어\u00a0바이크',date:'2026-09-11'}];
assert.equal(exerciseGroups(aliasRows).length,1);
assert.equal(exerciseGroups(aliasRows)[0].sessionDays,2);
assert.equal(exerciseGroups(aliasRows)[0].records.length,3);
assert.equal(exerciseGroups(analysisWindow(aliasRows,'1').records)[0].sessionDays,1);
assert.equal(exerciseGroups([...aliasRows,{...air,id:'different',exerciseName:'바이크'}]).length,2);
assert.equal(exerciseGroups([{...air,exerciseName:'AIR Bike'},{...air,exerciseName:'airbike'}]).length,1);
assert.equal(air.exerciseName,'에어 바이크');
const walkDistance={...base,id:'walk-distance',exerciseName:'덤벨 워킹런지',measurementType:'distance',loadType:'unknown',sets:[{kg:null,reps:0,distanceMeters:160}]};
const walkLoaded={...walkDistance,id:'walk-loaded',date:'2026-09-11',exerciseName:'덤벨 워킹 런지',measurementType:'weight_distance',loadType:'weighted',sets:[{kg:2,reps:0,distanceMeters:160}]};
const beforeWalk=JSON.stringify([walkDistance,walkLoaded]);
const walks=exerciseFamilies([walkDistance,walkLoaded,{...walkDistance,id:'same-date',exerciseName:'덤벨  워킹 런지'}]);
assert.equal(walks.length,1);assert.equal(walks[0].sessionDays,2);assert.equal(walks[0].variants.length,2);
assert.equal(exerciseGroups([walkDistance,walkLoaded]).length,2);
assert.deepEqual(performanceDays(walks[0].variants.find(v=>v.kind==='weight_distance').records,'kg').map(d=>d.value),[2]);
assert.equal(JSON.stringify([walkDistance,walkLoaded]),beforeWalk);
assert.equal(exerciseFamilies([walkDistance,{...walkDistance,exerciseName:'케틀벨 워킹 런지'},{...walkDistance,exerciseName:'덤벨 사이드 런지'}]).length,3);
assert.equal(exerciseFamilies([walkDistance,{...walkDistance,bodyPart:'등'}]).length,2);

const combined=exerciseFamilies([walkDistance,walkLoaded])[0];
assert.deepEqual(performanceDays(combined.records,'distance').map(d=>[d.date,d.value]),[['2026-09-10',160],['2026-09-11',160]]);
assert.deepEqual(performanceDays(combined.records,'kg').map(d=>d.value),[null,2]);
assert.deepEqual(performanceDays(combined.records,'volume').map(d=>d.value),[null,null]);
assert.deepEqual(performanceDays(combined.records,'reps').map(d=>d.value),[null,null]);
assert.deepEqual(new Set(performanceMetrics(combined.records)),new Set(['distance','kg']));
const zeroWeight={...walkLoaded,id:'zero',date:'2026-09-12',sets:[{kg:0,reps:0,distanceMeters:160}]};
assert.deepEqual(performanceDays([...combined.records,zeroWeight,{...walkDistance,id:'gap',date:'2026-09-13'}],'kg').map(d=>d.value),[null,2,0,null]);
assert.deepEqual(performanceDays([base,{...walkLoaded,date:base.date}],'volume').map(d=>d.value),[180]);
assert.equal(combined.records.length,2);
assert.equal(JSON.stringify([walkDistance,walkLoaded]),beforeWalk);

assert.deepEqual(performanceChartDays([...combined.records,zeroWeight],'kg').map(d=>[d.value,d.plotValue,d.missing]),[[null,0,true],[2,2,false],[0,0,false]]);
assert.equal(companionMetric(performanceMetrics(combined.records),'distance'),'kg');
assert.equal(companionMetric(performanceMetrics([base]),'volume'),'kg');
assert.equal(companionMetric(performanceMetrics([cardio]),'distance'),'duration');
assert.equal(companionMetric(performanceMetrics([{...base,loadType:'bodyweight',sets:[{kg:null,reps:10}]}]),'reps'),'sets');
assert.equal(companionMetric(performanceMetrics([walkDistance]),'distance'),null);
assert.deepEqual(performanceChartDays([{...base,loadType:'bodyweight',sets:[{kg:null,reps:12}]}, {...base,date:'2026-09-11'}],'kg').map(d=>d.plotValue),[0,10]);

const memo={...base,trainerNote:'무릎 통증 호소로 세트 축소',sourceHash:'a',sourceName:'일지.png',sourcePage:2};
const context=sessionChartContext([memo,{...memo,id:'second'},{...memo,id:'other',date:'2026-09-09'}],base.date);
assert.equal(context.notes.length,1);assert.equal(context.notes[0].text,memo.trainerNote);assert.equal(context.sources.length,1);assert.equal(context.sources[0].id,base.id);
assert.equal(sessionChartContext([{...memo,sourceHash:'b'},memo],base.date).sources.length,2);
assert.equal(sessionChartContext([{...base,notes:'kg란에 X 표기되어 있어 맨몸으로 간주함'}],base.date).notes.length,0);
assert.equal(sessionChartContext([{...base,notes:'통증 없음'}],base.date).notes[0].text,'통증 없음');
assert.equal(sessionChartContext([{...base,trainerNote:'',notes:'통증 없음'}],base.date).notes.length,0);
const goal={...blankTrainingGoal(),startDate:'2026-09-01',distribution:{mode:'percent',parts:['하체'],shares:{하체:100}}};
assert.equal(allocation([base],goal,'하체').target,100);assert.equal(allocation([base,old],goal,'하체').target,null);
assert.equal(analysisWindow([],'28').days,0);
assert.equal(displayWorkoutNotes('kg란에 X 표기되어 있어 맨몸으로 간주함'),'');
assert.equal(displayWorkoutNotes('kg란에 X 표기되어 있어 맨몸으로 간주함.\n통증 확인'), '통증 확인');
assert.equal(displayWorkoutNotes('X 표기만으로 맨몸으로 간주하지 않음'), 'X 표기만으로 맨몸으로 간주하지 않음');
for(const period of ['28','84','112']){
 const to='2026-09-10',cutoff=new Date(Date.parse(to+'T12:00:00Z')-(Number(period)-1)*86400000).toISOString().slice(0,10);
 const before=new Date(Date.parse(cutoff+'T12:00:00Z')-86400000).toISOString().slice(0,10);
 const scope=analysisWindow([base,{...base,id:'boundary',date:cutoff},{...base,id:'before',date:before}],period);
 assert.equal(scope.from,cutoff);assert.equal(scope.records.length,2);
}
const mixed=exerciseGroups([base,{...base,id:'bw',date:'2026-09-11',loadType:'bodyweight',sets:[{kg:null,reps:12}]}]);
assert.equal(mixed.length,1);assert.equal(mixed[0].hasWeighted,true);
assert.deepEqual(performanceDays(mixed[0].records,'volume').map(d=>d.value),[180,null]);
assert.deepEqual(performanceDays(mixed[0].records,'sets').map(d=>d.value),[1,1]);
const mountain={...cardio,id:'mountain',measurementType:'incline_speed_time',sets:[{kg:null,reps:0,inclinePercent:20,speedKph:5,durationSeconds:60},{kg:null,reps:0,inclinePercent:0,speedKph:3,durationSeconds:180}]};
assert.equal(performanceDays([mountain],'incline')[0].value,5);
assert.equal(performanceDays([mountain],'speed')[0].value,3.5);
assert.equal(performanceDays([mountain],'duration')[0].value,240);
assert.equal(performanceDays([mountain],'distance')[0].value,null);
assert.equal(analysisWindow([mountain],'all').volume,0);
assert.equal(analysisWindow([mountain],'all').sets,0);
console.log('Passed: shared date scope, invalid records, L/R totals, cardio isolation, missing load, exercise grouping, goal applicability, empty state.');
rmSync(dir,{recursive:true});

const dayContext=sessionChartContext([memo],base.date,{text:'수면 부족'});
assert.equal(dayContext.notes[0].label,'수업 메모');assert.equal(dayContext.notes[0].text,'수면 부족');
assert.equal(dayContext.notes[1].label,`운동 메모 · ${memo.exerciseName}`);
